const PALAUTTEET = [
  {
    id: 1,
    aikaleima: '2026-02-15T09:23:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Etusivu',
    nimi: 'Matti Virtanen',
    sahkoposti: 'matti.virtanen@email.fi',
    palaute: 'Etusivun hakutoiminto ei löydä oikeustapauksia riittävän tarkasti. Pitäisi pystyä hakemaan asian numerolla.',
    kategoria: 'hakutoiminto',
    tunne: 'negatiivinen'
  },
  {
    id: 2,
    aikaleima: '2026-01-16T14:05:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Tiedotteet',
    nimi: 'Liisa Korhonen',
    sahkoposti: '',
    palaute: 'Tiedotteet-sivulta löytyy ajankohtaiset uutiset, mutta vanhempia tiedotteita on vaikea löytää arkistosta.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 3,
    aikaleima: '2026-01-18T10:30:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Yhteystiedot',
    nimi: '',
    sahkoposti: '',
    palaute: 'Vankiloiden yhteystiedot ovat vanhentuneet. Hämeenlinnan vankilan puhelinnumero on väärä.',
    kategoria: 'sisalto',
    tunne: 'negatiivinen'
  },
  {
    id: 4,
    aikaleima: '2026-02-01T08:15:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Maksujärjestelyt',
    nimi: 'Jukka Mäkinen',
    sahkoposti: 'jukka.makinen@gmail.com',
    palaute: 'Maksujärjestelyjen hakeminen verkossa onnistuu, mutta prosessissa on turhia välivaiheita.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 5,
    aikaleima: '2026-01-22T16:45:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusapu',
    nimi: 'Anna Laine',
    sahkoposti: '',
    palaute: 'Sivustolla pitäisi olla chat-palvelu, jossa voisi kysyä oikeusavusta reaaliaikaisesti. Nykyinen lomake on liian hidas.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 6,
    aikaleima: '2026-02-10T11:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Rekisterit',
    nimi: '',
    sahkoposti: '',
    palaute: 'Rekisterihaku on hyvä, mutta toivoisin mahdollisuutta rajata hakutuloksia päivämäärän mukaan.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 7,
    aikaleima: '2026-01-25T13:20:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Etusivu',
    nimi: 'Pekka Heikkinen',
    sahkoposti: 'pekka.heikkinen@outlook.com',
    palaute: 'Sivusto on todella sekava. En löytänyt tietosuojavaltuutetun sivuja millään.',
    kategoria: 'navigointi',
    tunne: 'negatiivinen'
  },
  {
    id: 8,
    aikaleima: '2026-03-01T09:00:00',
    virpiId: 'oikeus_fi',
    sivu: 'Etusivu',
    nimi: 'Sari Nieminen',
    sahkoposti: '',
    palaute: 'Oikeus.fi on hyvä kokoava portaali. Löysin helposti tarvitsemani tiedon tuomioistuimista.',
    kategoria: 'kaytettavyys',
    tunne: 'positiivinen'
  },
  {
    id: 9,
    aikaleima: '2026-02-05T15:30:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Käsittelyajat',
    nimi: 'Mikko Järvinen',
    sahkoposti: '',
    palaute: 'Käsittelyaikojen tilastot ovat hyödyllisiä, mutta tiedot ovat kolme kuukautta vanhoja.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 10,
    aikaleima: '2026-01-30T12:10:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Mobiiliversio on käyttökelvoton. Valikot menevät päällekkäin puhelimen näytöllä.',
    kategoria: 'mobiili',
    tunne: 'negatiivinen'
  },
  {
    id: 11,
    aikaleima: '2026-02-18T10:45:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Tapaamiset',
    nimi: 'Tuula Koivisto',
    sahkoposti: 'tuula.koivisto@email.fi',
    palaute: 'Tapaamisten ajanvaraus verkossa on periaatteessa toimiva, mutta vapaat ajat päivittyvät viiveellä.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 12,
    aikaleima: '2026-03-05T08:30:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Ulosottohakemus',
    nimi: 'Ville Salonen',
    sahkoposti: '',
    palaute: 'Ulosottohakemus-lomake kaatuu aina kun yritän liittää PDF-tiedostoa. Selaimena Chrome.',
    kategoria: 'lomakkeet',
    tunne: 'negatiivinen'
  },
  {
    id: 13,
    aikaleima: '2026-02-22T14:15:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Edunvalvonta',
    nimi: 'Kaisa Hämäläinen',
    sahkoposti: '',
    palaute: 'Edunvalvontaa koskevat ohjeet ovat olemassa, mutta konkreettisia esimerkkejä puuttuu.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 14,
    aikaleima: '2026-01-20T11:30:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Rikosrekisteriote',
    nimi: '',
    sahkoposti: '',
    palaute: 'Rikosrekisteriotteen tilaaminen on liian monimutkaista. Vaatii viisi eri vaihetta ja tunnistautumisen kahdesti.',
    kategoria: 'kaytettavyys',
    tunne: 'negatiivinen'
  },
  {
    id: 15,
    aikaleima: '2026-02-28T16:00:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Tietosuojavaltuutettu',
    nimi: 'Hanna Koskinen',
    sahkoposti: 'hanna.koskinen@yritys.fi',
    palaute: 'Tietosuojavaltuutetun sivuilla ei ole riittävästi käytännön esimerkkejä GDPR:n soveltamisesta.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 16,
    aikaleima: '2026-03-10T09:45:00',
    virpiId: 'oikeus_fi',
    sivu: 'Sanasto',
    nimi: 'Risto Lahtinen',
    sahkoposti: '',
    palaute: 'Oikeudellinen sanasto on erittäin hyödyllinen. Toivoisin kuitenkin enemmän esimerkkejä termeille.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 17,
    aikaleima: '2026-01-28T07:50:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Asiointi',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston latausnopeus on todella heikko aamuisin. Sivut latautuvat yli 10 sekuntia.',
    kategoria: 'latausnopeus',
    tunne: 'negatiivinen'
  },
  {
    id: 18,
    aikaleima: '2026-02-12T13:40:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Syyttäjät',
    nimi: 'Eeva Karjalainen',
    sahkoposti: 'eeva.karjalainen@email.fi',
    palaute: 'Syyttäjien yhteystiedot löytyvät hakutoiminnolla, mutta haku voisi ehdottaa korjauksia kirjoitusvirheille.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 19,
    aikaleima: '2026-03-02T10:20:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Etusivu',
    nimi: 'Jarmo Tuominen',
    sahkoposti: '',
    palaute: 'Ruotsinkielinen versio on pahasti vanhentunut. Monet sivut ovat vain suomeksi.',
    kategoria: 'kieliversiot',
    tunne: 'negatiivinen'
  },
  {
    id: 20,
    aikaleima: '2026-02-08T15:55:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Velkajärjestely',
    nimi: 'Maria Leppänen',
    sahkoposti: '',
    palaute: 'Velkajärjestelyä koskeva informaatio on olemassa, mutta FAQ-osio kaipaa enemmän käytännön esimerkkejä.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 21,
    aikaleima: '2026-01-19T09:10:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston värikontrasti on heikko. Vaaleanharmaata tekstiä valkoisella pohjalla on vaikea lukea.',
    kategoria: 'saavutettavuus',
    tunne: 'negatiivinen'
  },
  {
    id: 22,
    aikaleima: '2026-02-25T11:25:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Etusivu',
    nimi: 'Timo Aalto',
    sahkoposti: 'timo.aalto@firma.fi',
    palaute: 'Navigointi on loogista pääsivuilla, mutta alisivuilla rakenne muuttuu sekavaksi.',
    kategoria: 'navigointi',
    tunne: 'neutraali'
  },
  {
    id: 23,
    aikaleima: '2026-03-08T14:30:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Kuluttajariitalautakunta',
    nimi: 'Johanna Virtanen',
    sahkoposti: '',
    palaute: 'Valituslomake ei toimi Safari-selaimella. Kenttiin ei pysty kirjoittamaan.',
    kategoria: 'lomakkeet',
    tunne: 'negatiivinen'
  },
  {
    id: 24,
    aikaleima: '2026-01-23T08:00:00',
    virpiId: 'oikeus_fi',
    sivu: 'Tuomioistuimet',
    nimi: 'Antti Korhonen',
    sahkoposti: '',
    palaute: 'Etkö voisi lisätä karttanäkymän, jossa näkee lähimmän tuomioistuimen? Olisi todella hyödyllinen.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 25,
    aikaleima: '2026-02-03T16:20:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Oikeustapaukset',
    nimi: 'Päivi Mäkelä',
    sahkoposti: 'paivi.makela@email.fi',
    palaute: 'Oikeustapaushaku on erinomainen työkalu. Suodattimet toimivat hyvin ja tulokset ovat relevantteja.',
    kategoria: 'hakutoiminto',
    tunne: 'positiivinen'
  },
  {
    id: 26,
    aikaleima: '2026-01-31T12:45:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Rikosasiat',
    nimi: '',
    sahkoposti: '',
    palaute: 'Rikosasioiden käsittelyprosessin kuvaus on epäselvä. Tarvitsisin selkeämmän vaiheittaisen esityksen.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 27,
    aikaleima: '2026-02-20T10:00:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Yhdyskuntaseuraamukset',
    nimi: 'Seppo Lindström',
    sahkoposti: '',
    palaute: 'Yhdyskuntaseuraamuksia koskeva sivu latautuu todella hitaasti. Kesti yli 15 sekuntia.',
    kategoria: 'latausnopeus',
    tunne: 'negatiivinen'
  },
  {
    id: 28,
    aikaleima: '2026-03-12T13:15:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Etusivu',
    nimi: 'Katri Rantanen',
    sahkoposti: 'katri.rantanen@email.fi',
    palaute: 'Toivoisin automaattista ilmoitusta sähköpostiin kun ulosottoasiani etenee. Nyt pitää aina käydä tarkistamassa itse.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 29,
    aikaleima: '2026-01-26T15:00:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusaputoimistot',
    nimi: 'Markku Salo',
    sahkoposti: '',
    palaute: 'Oikeusaputoimistojen hakutoiminto löytää toimistot, mutta ei näytä etäisyyksiä omasta sijainnista.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 30,
    aikaleima: '2026-02-14T08:40:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Konkurssirekisteri',
    nimi: '',
    sahkoposti: '',
    palaute: 'Konkurssirekisterin tiedot eivät ole ajan tasalla. Löysin tietoja jotka olivat kuukausia vanhoja.',
    kategoria: 'sisalto',
    tunne: 'negatiivinen'
  },
  {
    id: 31,
    aikaleima: '2026-03-03T11:50:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Yhdenvertaisuusvaltuutettu',
    nimi: 'Laura Niemi',
    sahkoposti: 'laura.niemi@email.fi',
    palaute: 'Yhdenvertaisuusvaltuutetun sivuilla on hyvää materiaalia syrjinnästä. Kiitos kattavista ohjeista.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 32,
    aikaleima: '2026-01-17T14:25:00',
    virpiId: 'oikeus_fi',
    sivu: 'Asiointi',
    nimi: 'Kari Lehto',
    sahkoposti: '',
    palaute: 'Asiointipalvelun kirjautuminen Suomi.fi-tunnistautumisella on hankalaa. Usein tulee virheilmoitus.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 33,
    aikaleima: '2026-02-07T09:35:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Yhteystiedot',
    nimi: 'Helena Mikkonen',
    sahkoposti: '',
    palaute: 'Tuomioistuinten yhteystiedot ovat esillä, mutta sähköpostiosoitteet puuttuvat useimmilta tuomioistuimilta.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 34,
    aikaleima: '2026-03-14T12:00:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston fonttikoko on liian pieni. Ikänäköisenä on vaikea lukea tekstiä ilman suurennusta.',
    kategoria: 'saavutettavuus',
    tunne: 'negatiivinen'
  },
  {
    id: 35,
    aikaleima: '2026-01-29T16:40:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Vankilat',
    nimi: 'Raimo Kinnunen',
    sahkoposti: 'raimo.kinnunen@email.fi',
    palaute: 'Vankiloiden esittelysivut sisältävät perustiedot, mutta vierailuaikojen ajantasaisuudesta ei ole varmuutta.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 36,
    aikaleima: '2026-02-16T10:10:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Usein kysytyt kysymykset',
    nimi: 'Tiina Pesonen',
    sahkoposti: '',
    palaute: 'UKK-sivulta puuttuu paljon yleisiä kysymyksiä. Esimerkiksi palkan ulosmittauksesta ei löydy tietoa.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 37,
    aikaleima: '2026-03-07T07:55:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Talous- ja velkaneuvonta',
    nimi: '',
    sahkoposti: '',
    palaute: 'Talous- ja velkaneuvonnan ajanvarausjärjestelmä on rikki. Ei näytä vapaita aikoja vaikka soittaessa niitä on.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 38,
    aikaleima: '2026-01-21T13:30:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Etusivu',
    nimi: 'Arto Väisänen',
    sahkoposti: '',
    palaute: 'Sivusto näyttää todella vanhanaikaiselta. Ulkoasu kaipaa päivitystä nykypäivään.',
    kategoria: 'ulkoasu',
    tunne: 'negatiivinen'
  },
  {
    id: 39,
    aikaleima: '2026-02-24T15:15:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Lapsiasiavaltuutettu',
    nimi: 'Elina Toivonen',
    sahkoposti: 'elina.toivonen@email.fi',
    palaute: 'Lapsiasiavaltuutetun sivuilla on hyvää materiaalia lasten oikeuksista. Sopii hyvin myös koulujen käyttöön.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 40,
    aikaleima: '2026-03-11T08:20:00',
    virpiId: 'oikeus_fi',
    sivu: 'Lait ja asetukset',
    nimi: 'Pentti Niskanen',
    sahkoposti: '',
    palaute: 'Lakien hakutoiminto voisi olla kehittyneempi. Haluaisin hakea lakia sen sisällön perusteella, ei pelkällä numerolla.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 41,
    aikaleima: '2026-02-02T11:00:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston navigaatiopalkki on liian monimutkainen. Alavalikot aukeavat hitaasti ja katoavat liian nopeasti.',
    kategoria: 'navigointi',
    tunne: 'negatiivinen'
  },
  {
    id: 42,
    aikaleima: '2026-01-24T14:50:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Asiointi',
    nimi: 'Olli Nurmi',
    sahkoposti: 'olli.nurmi@yritys.fi',
    palaute: 'Sähköisen asioinnin lomakkeet toimivat pääosin, mutta muutamassa kentässä syöte hylätään ilman selitystä.',
    kategoria: 'lomakkeet',
    tunne: 'neutraali'
  },
  {
    id: 43,
    aikaleima: '2026-03-09T10:35:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Mobiili',
    nimi: 'Sanna Pitkänen',
    sahkoposti: '',
    palaute: 'Mobiilisivusto on todella hankala käyttää. Painikkeet ovat liian pieniä ja teksti menee reunojen yli.',
    kategoria: 'mobiili',
    tunne: 'negatiivinen'
  },
  {
    id: 44,
    aikaleima: '2026-02-11T16:30:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Yhteystiedot',
    nimi: 'Juha Laaksonen',
    sahkoposti: '',
    palaute: 'Ulosottomiesten yhteystiedot ovat esillä, mutta aluejaon selittäminen jää epäselväksi.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 45,
    aikaleima: '2026-01-27T09:00:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Haluaisin tekoälyavustajan joka auttaisi valitsemaan oikean palvelun. Nykyisellään en tiedä mitä tarvitsen.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 46,
    aikaleima: '2026-02-19T13:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Liiketoimintakieltorekisteri',
    nimi: 'Minna Kallio',
    sahkoposti: 'minna.kallio@email.fi',
    palaute: 'Liiketoimintakieltorekisterin haku toimii, mutta hakutulosten esitystapa voisi olla selkeämpi.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 47,
    aikaleima: '2026-03-13T15:45:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Etusivu',
    nimi: 'Harri Lehtonen',
    sahkoposti: '',
    palaute: 'Erityisviranomaisten etusivulta on vaikea hahmottaa, mikä viranomainen vastaa mistäkin asiasta.',
    kategoria: 'navigointi',
    tunne: 'neutraali'
  },
  {
    id: 48,
    aikaleima: '2026-01-15T10:20:00',
    virpiId: 'oikeus_fi',
    sivu: 'Etusivu',
    nimi: 'Terhi Mäntylä',
    sahkoposti: '',
    palaute: 'Sivusto toimii ruudunlukuohjelmalla, mutta joidenkin painikkeiden nimet puuttuvat.',
    kategoria: 'saavutettavuus',
    tunne: 'neutraali'
  },
  {
    id: 49,
    aikaleima: '2026-02-06T08:15:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Lomakkeet',
    nimi: 'Ilkka Saarinen',
    sahkoposti: 'ilkka.saarinen@email.fi',
    palaute: 'Haastehakemuslomake on todella monimutkainen. Tavallinen kansalainen ei ymmärrä mitä kenttiä pitää täyttää.',
    kategoria: 'lomakkeet',
    tunne: 'negatiivinen'
  },
  {
    id: 50,
    aikaleima: '2026-03-06T12:30:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Yhteystiedot',
    nimi: '',
    sahkoposti: '',
    palaute: 'Syyttäjänvirastojen karttanäkymä olisi hyödyllinen. Nyt pitää tietää tarkkaan mikä virasto hoitaa omaa aluetta.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 51,
    aikaleima: '2026-01-18T14:10:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Etusivu',
    nimi: 'Esa Mattila',
    sahkoposti: '',
    palaute: 'Englanninkielinen versio on puutteellinen. Ulkomaalaistaustaisille vangille tämä on ongelma.',
    kategoria: 'kieliversiot',
    tunne: 'negatiivinen'
  },
  {
    id: 52,
    aikaleima: '2026-02-27T09:50:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Asiointi',
    nimi: 'Leena Hiltunen',
    sahkoposti: 'leena.hiltunen@gmail.com',
    palaute: 'Sähköisen asioinnin tunnistautuminen toimii useimmiten, mutta mobiilivarmenteella tulee ajoittain virheitä.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 53,
    aikaleima: '2026-03-15T11:20:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusapu',
    nimi: 'Aki Laitinen',
    sahkoposti: '',
    palaute: 'Oikeusapulaskuri ei toimi oikein. Antaa eri tuloksen kuin mitä oikeusaputoimistossa kerrottiin.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 54,
    aikaleima: '2026-01-22T16:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Asiointitili',
    nimi: '',
    sahkoposti: '',
    palaute: 'Asiointitilin luominen onnistui, mutta ohjeet olisivat voineet olla selkeämmät vaiheittain.',
    kategoria: 'kaytettavyys',
    tunne: 'neutraali'
  },
  {
    id: 55,
    aikaleima: '2026-02-09T13:45:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Onnettomuustutkintakeskus',
    nimi: 'Veikko Koivunen',
    sahkoposti: '',
    palaute: 'Onnettomuustutkintaraporttien haku on hyvä, mutta PDF-tiedostot ovat todella suuria ja latautuvat hitaasti.',
    kategoria: 'latausnopeus',
    tunne: 'neutraali'
  },
  {
    id: 56,
    aikaleima: '2026-03-04T07:30:00',
    virpiId: 'oikeus_fi',
    sivu: 'Oikeudenkäynti',
    nimi: 'Ritva Heikkilä',
    sahkoposti: 'ritva.heikkila@email.fi',
    palaute: 'Oikeudenkäyntiä koskevat ohjeet ovat todella hyvät ja ymmärrettävät. Kiitos selkokielisestä sisällöstä!',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 57,
    aikaleima: '2026-02-04T10:30:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Asiointi',
    nimi: 'Hannu Rantala',
    sahkoposti: '',
    palaute: 'Sähköinen asiointi vaatii Java-lisäosan joka ei toimi uusilla selaimilla. Tämä pitäisi päivittää.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 58,
    aikaleima: '2026-01-30T15:25:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Tiedotteet',
    nimi: 'Kristiina Jokinen',
    sahkoposti: '',
    palaute: 'Tiedotteiden RSS-syöte olisi kätevä. Haluaisin seurata uusia tiedotteita automaattisesti.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 59,
    aikaleima: '2026-02-21T08:00:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Lomakkeet',
    nimi: '',
    sahkoposti: '',
    palaute: 'Tapaamisen varauslomake on epäselvä. Ei käy ilmi mitkä kentät ovat pakollisia.',
    kategoria: 'lomakkeet',
    tunne: 'negatiivinen'
  },
  {
    id: 60,
    aikaleima: '2026-03-10T14:00:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Etusivu',
    nimi: 'Tarja Koskela',
    sahkoposti: 'tarja.koskela@email.fi',
    palaute: 'Sivuston ulkoasu on asiallinen, mutta visuaalisesti melko yksinkertainen verrattuna muihin viranomaisiin.',
    kategoria: 'ulkoasu',
    tunne: 'neutraali'
  },
  {
    id: 61,
    aikaleima: '2026-01-25T11:40:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Yhteystiedot',
    nimi: 'Pertti Manninen',
    sahkoposti: '',
    palaute: 'Yhteystietosivulla voisi olla myös yhteydenottolomake. Ei aina jaksa soittaa.',
    kategoria: 'lomakkeet',
    tunne: 'neutraali'
  },
  {
    id: 62,
    aikaleima: '2026-02-17T16:15:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Kaupparekisteri',
    nimi: '',
    sahkoposti: '',
    palaute: 'Kaupparekisteritietojen haku on kohtalaisen nopea, mutta tulosten suodatus on puutteellinen.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 63,
    aikaleima: '2026-03-01T09:30:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Tasa-arvovaltuutettu',
    nimi: 'Ulla Jokela',
    sahkoposti: 'ulla.jokela@email.fi',
    palaute: 'Tasa-arvovaltuutetun sivuilla navigointi on hankalaa. Päävalikko ei kerro selkeästi mitä mistäkin löytyy.',
    kategoria: 'navigointi',
    tunne: 'negatiivinen'
  },
  {
    id: 64,
    aikaleima: '2026-01-20T13:00:00',
    virpiId: 'oikeus_fi',
    sivu: 'Etusivu',
    nimi: 'Jari Honkanen',
    sahkoposti: '',
    palaute: 'Sivusto latautuu hitaasti mobiililla. Erityisesti kuvat vievät kauan.',
    kategoria: 'latausnopeus',
    tunne: 'negatiivinen'
  },
  {
    id: 65,
    aikaleima: '2026-02-13T10:45:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Käsittelyajat',
    nimi: 'Pirjo Mäkinen',
    sahkoposti: '',
    palaute: 'Käsittelyajat pitäisi esittää graafisesti, ei pelkkinä lukuina taulukossa. Olisi helpompi hahmottaa.',
    kategoria: 'ulkoasu',
    tunne: 'neutraali'
  },
  {
    id: 66,
    aikaleima: '2026-03-08T15:30:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston tietoturvaseloste on vaikeasti löydettävissä. Pitäisi olla selkeämmin esillä alatunnisteessa.',
    kategoria: 'tietoturva',
    tunne: 'neutraali'
  },
  {
    id: 67,
    aikaleima: '2026-01-16T08:30:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Etusivu',
    nimi: 'Maija Hakala',
    sahkoposti: 'maija.hakala@email.fi',
    palaute: 'Hienoa, että sivusto on nyt myös selkosuomella! Tämä auttaa monia.',
    kategoria: 'saavutettavuus',
    tunne: 'positiivinen'
  },
  {
    id: 68,
    aikaleima: '2026-02-26T12:20:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Palkan ulosmittaus',
    nimi: 'Kimmo Lahtinen',
    sahkoposti: '',
    palaute: 'Palkan ulosmittauksen laskuri olisi todella tarpeellinen. Haluaisin tietää etukäteen paljonko palkasta menee.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 69,
    aikaleima: '2026-03-14T10:00:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivusto on hyvin rakennettu. Löysin tarvitsemani tiedon alle minuutissa.',
    kategoria: 'kaytettavyys',
    tunne: 'positiivinen'
  },
  {
    id: 70,
    aikaleima: '2026-01-28T14:30:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Oikeushallinnon rekisterit',
    nimi: 'Heikki Kujala',
    sahkoposti: '',
    palaute: 'Rekisterien käyttöehdot ovat epäselviä. Mihin tarkoituksiin tietoja saa käyttää?',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 71,
    aikaleima: '2026-02-08T09:15:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Konkurssiasiamies',
    nimi: 'Riitta Valtonen',
    sahkoposti: 'riitta.valtonen@yritys.fi',
    palaute: 'Konkurssiasiamiehen sivuille toivoisin enemmän ohjeita velkojille. Nykyiset ohjeet ovat liian yleisiä.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 72,
    aikaleima: '2026-03-05T16:45:00',
    virpiId: 'oikeus_fi',
    sivu: 'Sovittelu',
    nimi: 'Jaakko Peltonen',
    sahkoposti: '',
    palaute: 'Sovittelua koskeva sivu on todella informatiivinen. En tiennyt, että sovittelu on mahdollista niin monessa asiassa.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 73,
    aikaleima: '2026-01-23T11:10:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston hakutoiminto on todella hidas. Pitäisi saada tulokset alle sekunnissa.',
    kategoria: 'hakutoiminto',
    tunne: 'negatiivinen'
  },
  {
    id: 74,
    aikaleima: '2026-02-15T14:40:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Rikosasiat',
    nimi: 'Marjo Karhu',
    sahkoposti: '',
    palaute: 'Toivoisin videoita jotka selittävät rikosprosessin vaiheet. Teksti on liian kuivaa.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 75,
    aikaleima: '2026-03-12T08:50:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Kuntoutus',
    nimi: 'Paavo Virkkunen',
    sahkoposti: 'paavo.virkkunen@email.fi',
    palaute: 'Kuntoutusohjelmien esittely on hyvä lisäys sivustolle. Näyttää lupaavilta ohjelmilta.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 76,
    aikaleima: '2026-01-19T15:20:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Maksujärjestelyt',
    nimi: '',
    sahkoposti: '',
    palaute: 'Maksujärjestelylomakkeessa on bugi: kun valitsee maksusuunnitelman pituuden, sivu nollautuu ja kaikki tiedot häviävät.',
    kategoria: 'lomakkeet',
    tunne: 'negatiivinen'
  },
  {
    id: 77,
    aikaleima: '2026-02-23T10:05:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Yleinen edunvalvonta',
    nimi: 'Sirpa Heinonen',
    sahkoposti: '',
    palaute: 'Yleisen edunvalvonnan prosessikuvaus on olemassa, mutta kaikkia vaiheita ei selitetä riittävästi.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 78,
    aikaleima: '2026-03-02T13:35:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Etusivu',
    nimi: 'Tapani Saari',
    sahkoposti: '',
    palaute: 'Evästekysely tulee aina uudestaan vaikka olen jo hyväksynyt evästeet. Tämä on ärsyttävää.',
    kategoria: 'tietoturva',
    tunne: 'negatiivinen'
  },
  {
    id: 79,
    aikaleima: '2026-01-26T09:40:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Tietosuojavaltuutettu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Tietosuojavaltuutetun sivuille pitäisi lisätä mahdollisuus tehdä tietosuojailmoitus kokonaan verkossa.',
    kategoria: 'lomakkeet',
    tunne: 'neutraali'
  },
  {
    id: 80,
    aikaleima: '2026-02-14T16:50:00',
    virpiId: 'oikeus_fi',
    sivu: 'Etusivu',
    nimi: 'Aila Koivunen',
    sahkoposti: 'aila.koivunen@email.fi',
    palaute: 'Sivuston hakutoiminto antaa liikaa tuloksia. Pitäisi voida rajata tarkemmin esim. viranomaisen mukaan.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 81,
    aikaleima: '2026-03-09T11:15:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Oikeustapaukset',
    nimi: 'Veli Turunen',
    sahkoposti: '',
    palaute: 'Oikeustapauksien PDF-tiedostot eivät avaudu suoraan selaimessa. Joutuu aina lataamaan.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 82,
    aikaleima: '2026-01-17T12:00:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Syyttäjät',
    nimi: 'Irma Aaltonen',
    sahkoposti: '',
    palaute: 'Syyttäjien kuvat ja tittelit ovat esillä, mutta kaikilla ei ole profiilikuvaa mikä tekee sivusta epätasaisen.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 83,
    aikaleima: '2026-02-10T07:45:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Yhteystiedot',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston tietoturva huolestuttaa. HTTP-yhteys ei ole salattu kaikilla alasivuilla.',
    kategoria: 'tietoturva',
    tunne: 'negatiivinen'
  },
  {
    id: 84,
    aikaleima: '2026-03-07T14:20:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Velkajärjestely',
    nimi: 'Raija Ahonen',
    sahkoposti: 'raija.ahonen@email.fi',
    palaute: 'Velkajärjestelyn hakemisesta olisi hyvä olla lyhyt video-ohje. Teksti on pitkä ja monimutkainen.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 85,
    aikaleima: '2026-01-31T10:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusapu',
    nimi: 'Erkki Rautiainen',
    sahkoposti: '',
    palaute: 'Oikeusavun tulorajat pitäisi esittää selkeämmin. Nyt joutuu laskemaan monesta eri kohdasta.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 86,
    aikaleima: '2026-02-22T15:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Sakkorekisteri',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sakkorekisterin tietojen tarkistaminen onnistuu, mutta ohjeteksti on melko suppeaa.',
    kategoria: 'kaytettavyys',
    tunne: 'neutraali'
  },
  {
    id: 87,
    aikaleima: '2026-03-13T09:10:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Yhdenvertaisuusvaltuutettu',
    nimi: 'Niina Laine',
    sahkoposti: '',
    palaute: 'Syrjintäilmoituksen tekeminen verkossa on liian monimutkaista. Lomake on 8 sivua pitkä.',
    kategoria: 'lomakkeet',
    tunne: 'negatiivinen'
  },
  {
    id: 88,
    aikaleima: '2026-01-21T14:15:00',
    virpiId: 'oikeus_fi',
    sivu: 'Perheoikeus',
    nimi: 'Satu Rinne',
    sahkoposti: 'satu.rinne@email.fi',
    palaute: 'Huoltajuusasioita koskeva osio on kattava ja hyvin kirjoitettu. Löysin vastaukset kysymyksiini.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 89,
    aikaleima: '2026-02-05T11:50:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Etusivu',
    nimi: 'Olavi Mikkola',
    sahkoposti: '',
    palaute: 'Sivusto ei toimi kunnolla Internet Explorerilla. Tiedän, että se on vanha selain, mutta silti.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 90,
    aikaleima: '2026-03-04T16:30:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston kuvituskuvat ovat liian geneerisiä. Voisi käyttää oikeita kuvia syyttäjänvirastoista.',
    kategoria: 'ulkoasu',
    tunne: 'neutraali'
  },
  {
    id: 91,
    aikaleima: '2026-01-29T08:20:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Tapaamiset',
    nimi: 'Anneli Virtanen',
    sahkoposti: '',
    palaute: 'Tapaamisten ajanvarausjärjestelmä on hankala. Vapaat ajat eivät päivity reaaliaikaisesti.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 92,
    aikaleima: '2026-02-18T13:00:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Ulosottohakemus',
    nimi: 'Taisto Penttilä',
    sahkoposti: 'taisto.penttila@yritys.fi',
    palaute: 'Ulosottohakemuksen täyttäminen onnistui, mutta lomakkeen vaiheet voisivat olla paremmin numeroituja.',
    kategoria: 'lomakkeet',
    tunne: 'neutraali'
  },
  {
    id: 93,
    aikaleima: '2026-03-11T10:40:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Talous- ja velkaneuvonta',
    nimi: '',
    sahkoposti: '',
    palaute: 'Toivoisin verkkopohjaista velkaneuvontaa, esim. videotapaamisia. Toimistoon on pitkä matka.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 94,
    aikaleima: '2026-01-24T15:50:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Etusivu',
    nimi: 'Martti Laakso',
    sahkoposti: '',
    palaute: 'Sivuston hakutoiminto ei löydä mitään kun hakee ä- tai ö-kirjaimilla. Skandinaaviset kirjaimet eivät toimi.',
    kategoria: 'hakutoiminto',
    tunne: 'negatiivinen'
  },
  {
    id: 95,
    aikaleima: '2026-02-12T08:35:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Etusivu',
    nimi: 'Kirsi Juvonen',
    sahkoposti: 'kirsi.juvonen@email.fi',
    palaute: 'Sivuston latausnopeus on parantunut huomattavasti. Ennen sivu latautui yli 10 sekuntia, nyt alle 2.',
    kategoria: 'latausnopeus',
    tunne: 'positiivinen'
  },
  {
    id: 96,
    aikaleima: '2026-03-03T14:45:00',
    virpiId: 'oikeus_fi',
    sivu: 'Rikosasiat',
    nimi: 'Anssi Karjalainen',
    sahkoposti: '',
    palaute: 'Rikosasioita koskeva osio on liian juridinen. Tavallinen kansalainen ei ymmärrä kaikkia termejä.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 97,
    aikaleima: '2026-01-27T11:00:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Asiointi',
    nimi: '',
    sahkoposti: '',
    palaute: 'Haluaisin voida seurata oman oikeusasiain etenemistä verkossa, kuten pakettiseurantaa.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 98,
    aikaleima: '2026-02-20T09:20:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Rikosasiat',
    nimi: 'Kaarina Mustonen',
    sahkoposti: '',
    palaute: 'Rikosasioiden käsittelyvaiheet on esitetty selkeästi. Ymmärsin prosessin hyvin.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 99,
    aikaleima: '2026-03-15T12:30:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Etusivu',
    nimi: 'Jouko Hyvärinen',
    sahkoposti: 'jouko.hyvarinen@email.fi',
    palaute: 'Sivuston breadcrumb-navigaatio on rikki. Ei näytä oikein missä kohtaa sivustoa ollaan.',
    kategoria: 'navigointi',
    tunne: 'negatiivinen'
  },
  {
    id: 100,
    aikaleima: '2026-01-18T16:10:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Etusivu',
    nimi: 'Merja Koivisto',
    sahkoposti: '',
    palaute: 'Toivoisin sivustolle laskuria jolla voi arvioida ulosoton keston ja kokonaiskustannukset.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 101,
    aikaleima: '2026-02-03T10:00:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusaputoimistot',
    nimi: '',
    sahkoposti: '',
    palaute: 'Oikeusaputoimistojen aukioloajat eivät ole ajan tasalla. Joensuun toimisto oli kiinni vaikka sivuilla luki auki.',
    kategoria: 'sisalto',
    tunne: 'negatiivinen'
  },
  {
    id: 102,
    aikaleima: '2026-03-06T15:20:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Rikosrekisteriote',
    nimi: 'Lauri Heikkinen',
    sahkoposti: '',
    palaute: 'Rikosrekisteriotteen tilaaminen verkossa on mahdollista, mutta toimitusaika voisi olla lyhyempi.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 103,
    aikaleima: '2026-01-22T08:45:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Tietosuojavaltuutettu',
    nimi: 'Tuomas Ojala',
    sahkoposti: 'tuomas.ojala@email.fi',
    palaute: 'Tietosuojavaltuutetun sivujen mobiiliversio on hyvä. Toimii hyvin puhelimella.',
    kategoria: 'mobiili',
    tunne: 'positiivinen'
  },
  {
    id: 104,
    aikaleima: '2026-02-16T12:40:00',
    virpiId: 'oikeus_fi',
    sivu: 'Etusivu',
    nimi: 'Seija Parviainen',
    sahkoposti: '',
    palaute: 'Sivuston kielivalinta on vaikeasti löydettävissä. Ruotsinkielinen versio pitäisi olla helpommin saatavilla.',
    kategoria: 'kieliversiot',
    tunne: 'negatiivinen'
  },
  {
    id: 105,
    aikaleima: '2026-03-01T10:15:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Yhteystiedot',
    nimi: '',
    sahkoposti: '',
    palaute: 'Tuomioistuinten karttanäkymä on olemassa, mutta kartta latautuu hitaasti ja zoom-toiminto on kankea.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 106,
    aikaleima: '2026-01-15T14:30:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Etusivu',
    nimi: 'Keijo Rantanen',
    sahkoposti: '',
    palaute: 'Sivustolla pitäisi olla mahdollisuus antaa nimettömänä vihje rikoksesta suoraan verkossa.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 107,
    aikaleima: '2026-02-07T16:00:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Vankilat',
    nimi: 'Esko Toivonen',
    sahkoposti: 'esko.toivonen@email.fi',
    palaute: 'Vankiloiden esittelysivuilla voisi olla kuvia tiloista. Auttaisi omaisia valmistautumaan vierailuun.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 108,
    aikaleima: '2026-03-10T08:00:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Asiointi',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sähköisen asioinnin istunto katkeaa liian nopeasti. 15 minuutin aikakatkaisu on liian lyhyt pitkissä lomakkeissa.',
    kategoria: 'kaytettavyys',
    tunne: 'negatiivinen'
  },
  {
    id: 109,
    aikaleima: '2026-01-30T09:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Edunvalvonta',
    nimi: 'Aino Kemppainen',
    sahkoposti: '',
    palaute: 'Edunvalvonnan hakemuslomake on selkeä ja helppo täyttää. Kiitos!',
    kategoria: 'lomakkeet',
    tunne: 'positiivinen'
  },
  {
    id: 110,
    aikaleima: '2026-02-24T13:15:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Etusivu',
    nimi: 'Arvo Salmi',
    sahkoposti: '',
    palaute: 'Sivuston hakutulokset pitäisi voida järjestää päivämäärän, relevanssin tai aakkosellisen järjestyksen mukaan.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 111,
    aikaleima: '2026-03-14T15:40:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Lapsiasiavaltuutettu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Lapsiasiavaltuutetun sivuilta puuttuu yhteystiedot alueellisille edustajille.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 112,
    aikaleima: '2026-01-20T11:00:00',
    virpiId: 'oikeus_fi',
    sivu: 'Asiointi',
    nimi: 'Teuvo Nieminen',
    sahkoposti: 'teuvo.nieminen@email.fi',
    palaute: 'Suomi.fi-tunnistautuminen on liian monimutkainen. Mobiilivarmenteella kirjautuminen epäonnistuu usein.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 113,
    aikaleima: '2026-02-11T08:50:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Lomakkeet',
    nimi: 'Anja Koivula',
    sahkoposti: '',
    palaute: 'Lomakkeiden täyttöohjeet ovat hyvät. Esimerkkitäytetty lomake on erityisen hyödyllinen.',
    kategoria: 'lomakkeet',
    tunne: 'positiivinen'
  },
  {
    id: 114,
    aikaleima: '2026-03-08T12:10:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Tiedotteet',
    nimi: '',
    sahkoposti: '',
    palaute: 'Tiedotteiden hakutoiminto on puutteellinen. Ei voi hakea päivämäärän mukaan.',
    kategoria: 'hakutoiminto',
    tunne: 'negatiivinen'
  },
  {
    id: 115,
    aikaleima: '2026-01-25T15:30:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Etusivu',
    nimi: 'Unto Korhonen',
    sahkoposti: '',
    palaute: 'Sivusto on teknisesti toimiva mutta visuaalisesti vanhanaikainen. Päivitys olisi paikallaan.',
    kategoria: 'ulkoasu',
    tunne: 'neutraali'
  },
  {
    id: 116,
    aikaleima: '2026-02-19T10:20:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Usein kysytyt kysymykset',
    nimi: 'Paula Mäenpää',
    sahkoposti: 'paula.maenpaa@email.fi',
    palaute: 'UKK-osio on kohtalaisen hyödyllinen, mutta kysymykset voisivat olla käytännönläheisempiä.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 117,
    aikaleima: '2026-03-05T14:55:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Etusivu',
    nimi: 'Kalevi Tuominen',
    sahkoposti: '',
    palaute: 'Sivuston mobiiliversio on käyttökelpoinen, mutta alavalikot ovat ahtaita pienellä näytöllä.',
    kategoria: 'mobiili',
    tunne: 'neutraali'
  },
  {
    id: 118,
    aikaleima: '2026-01-28T12:45:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Rekisterit',
    nimi: '',
    sahkoposti: '',
    palaute: 'Rekisterien API-rajapinta olisi hyödyllinen yrityksille. Nyt tiedot pitää hakea manuaalisesti.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 119,
    aikaleima: '2026-02-06T09:00:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Kuluttajariitalautakunta',
    nimi: 'Hilkka Leppänen',
    sahkoposti: '',
    palaute: 'Kuluttajariitalautakunnan ratkaisujen haku löytää tuloksia, mutta hakukriteerien yhdistely on rajallista.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 120,
    aikaleima: '2026-03-02T16:20:00',
    virpiId: 'oikeus_fi',
    sivu: 'Etusivu',
    nimi: 'Ismo Hakkinen',
    sahkoposti: 'ismo.hakkinen@email.fi',
    palaute: 'Sivuston navigaatio on kohtalainen. Pääsivut löytyvät, mutta syvemmällä rakenne hajoaa.',
    kategoria: 'navigointi',
    tunne: 'neutraali'
  },
  {
    id: 121,
    aikaleima: '2026-01-16T10:15:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Käsittelyajat',
    nimi: 'Marja Järvinen',
    sahkoposti: '',
    palaute: 'Käsittelyaikojen vertailu eri tuomioistuinten välillä olisi hyödyllinen ominaisuus.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 122,
    aikaleima: '2026-02-09T14:00:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Asiointi',
    nimi: '',
    sahkoposti: '',
    palaute: 'Asiointilomakkeen kenttien virheviestit ovat epäselviä. Ei kerro mitä pitäisi korjata.',
    kategoria: 'lomakkeet',
    tunne: 'negatiivinen'
  },
  {
    id: 123,
    aikaleima: '2026-03-09T09:25:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Yhdyskuntaseuraamukset',
    nimi: 'Veijo Huttunen',
    sahkoposti: '',
    palaute: 'Yhdyskuntaseuraamusten tietosivu on selkeä ja kattava. Hyvä kokonaisuus.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 124,
    aikaleima: '2026-01-23T16:30:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Etusivu',
    nimi: 'Mirja Halonen',
    sahkoposti: 'mirja.halonen@gmail.com',
    palaute: 'Sivuston hakutoiminto ei ymmärrä kirjoitusvirheitä. Pitäisi olla "tarkoititko..."-toiminto.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 125,
    aikaleima: '2026-02-25T08:10:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusapu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Oikeusavun hakeminen on tehty liian byrokraattiseksi. Prosessi pitäisi yksinkertaistaa.',
    kategoria: 'kaytettavyys',
    tunne: 'negatiivinen'
  },
  {
    id: 126,
    aikaleima: '2026-03-12T11:45:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Asiointitili',
    nimi: 'Jorma Hämäläinen',
    sahkoposti: '',
    palaute: 'Asiointitilin salasanan vaihto ei toimi. Saan virheilmoituksen joka kerta.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 127,
    aikaleima: '2026-01-19T09:40:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Onnettomuustutkintakeskus',
    nimi: 'Outi Karjalainen',
    sahkoposti: 'outi.karjalainen@email.fi',
    palaute: 'Tutkintaraporttien hakemisto on hyvin järjestetty. Löysin etsimäni raportin nopeasti.',
    kategoria: 'navigointi',
    tunne: 'positiivinen'
  },
  {
    id: 128,
    aikaleima: '2026-02-13T15:30:00',
    virpiId: 'oikeus_fi',
    sivu: 'Tuomioistuimet',
    nimi: 'Reino Saarela',
    sahkoposti: '',
    palaute: 'Tuomioistuinten esittelysivut voisivat olla kattavammat. Tietoa on niukasti.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 129,
    aikaleima: '2026-03-06T08:30:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston värit ovat liian tummia. Kokonaisilme on synkkä ja painostava.',
    kategoria: 'ulkoasu',
    tunne: 'neutraali'
  },
  {
    id: 130,
    aikaleima: '2026-01-30T13:20:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Syyttäjät',
    nimi: 'Saila Niskanen',
    sahkoposti: '',
    palaute: 'Syyttäjien haku alueittain on käyttökelpoinen, mutta hakutulosten järjestystä ei voi muuttaa.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 131,
    aikaleima: '2026-02-21T11:50:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Lomakkeet',
    nimi: 'Jari Pennanen',
    sahkoposti: 'jari.pennanen@email.fi',
    palaute: 'Vierailu-lomaketta ei voi täyttää mobiililla. Pudotusvalikot eivät toimi kosketusnäytöllä.',
    kategoria: 'mobiili',
    tunne: 'negatiivinen'
  },
  {
    id: 132,
    aikaleima: '2026-03-14T14:10:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Velkajärjestely',
    nimi: '',
    sahkoposti: '',
    palaute: 'Velkajärjestelyn etenemistä pitäisi pystyä seuraamaan verkossa. Nyt ei tiedä missä vaiheessa asia on.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 133,
    aikaleima: '2026-01-17T15:00:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Talous- ja velkaneuvonta',
    nimi: 'Marita Salminen',
    sahkoposti: '',
    palaute: 'Velkaneuvonnan verkkomateriaalit ovat erinomaisia. Erityisesti budjetointiopas on hyödyllinen.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 134,
    aikaleima: '2026-02-08T10:30:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Etusivu',
    nimi: 'Kalle Aaltonen',
    sahkoposti: '',
    palaute: 'Sivusto tarvitsisi paremman hakukoneoptimoinnin. Googlesta ei löydy sivustoa helposti.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 135,
    aikaleima: '2026-03-03T16:50:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Tasa-arvovaltuutettu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Tasa-arvovaltuutetun sivujen sisältö on hyvää mutta sivusto on visuaalisesti ankea.',
    kategoria: 'ulkoasu',
    tunne: 'neutraali'
  },
  {
    id: 136,
    aikaleima: '2026-01-26T12:15:00',
    virpiId: 'oikeus_fi',
    sivu: 'Sanasto',
    nimi: 'Sinikka Kinnunen',
    sahkoposti: 'sinikka.kinnunen@email.fi',
    palaute: 'Sanasto on erinomainen! Vihdoin ymmärrän mitä kaikki lakitermit tarkoittavat.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 137,
    aikaleima: '2026-02-17T09:00:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Oikeustapaukset',
    nimi: 'Reijo Laitinen',
    sahkoposti: '',
    palaute: 'Oikeustapaushaussa pitäisi pystyä hakemaan usealla hakusanalla kerralla AND/OR-operaattoreilla.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 138,
    aikaleima: '2026-03-11T13:25:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Rikosasiat',
    nimi: '',
    sahkoposti: '',
    palaute: 'Rikosasian käsittelyn aikajanaa olisi hyvä voida seurata verkossa. Nyt en tiedä missä vaiheessa asia on.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 139,
    aikaleima: '2026-01-21T08:00:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Kuntoutus',
    nimi: 'Liisa Mattila',
    sahkoposti: '',
    palaute: 'Kuntoutusohjelmista olisi hyvä olla enemmän tietoa. Mitä ohjelmia on tarjolla ja kenelle?',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 140,
    aikaleima: '2026-02-28T14:40:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Palkan ulosmittaus',
    nimi: 'Samuli Virtanen',
    sahkoposti: 'samuli.virtanen@email.fi',
    palaute: 'Palkan ulosmittausta koskeva informaatio on saatavilla, mutta taulukoiden tulkitseminen vaatii paneutumista.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 141,
    aikaleima: '2026-03-08T10:00:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Yleinen edunvalvonta',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston lomakkeet eivät toimi Firefox-selaimella. Kenttiin ei voi syöttää tekstiä.',
    kategoria: 'lomakkeet',
    tunne: 'negatiivinen'
  },
  {
    id: 142,
    aikaleima: '2026-01-24T10:45:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Konkurssirekisteri',
    nimi: 'Eero Hänninen',
    sahkoposti: '',
    palaute: 'Konkurssirekisterin tiedot ovat hyödyllisiä. Toivoisin kuitenkin reaaliaikaista päivitystä.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 143,
    aikaleima: '2026-02-15T16:30:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Yhdenvertaisuusvaltuutettu',
    nimi: 'Vuokko Leppänen',
    sahkoposti: 'vuokko.leppanen@email.fi',
    palaute: 'Sivuston kieliversiot ovat puutteelliset. Saamen kieli puuttuu kokonaan.',
    kategoria: 'kieliversiot',
    tunne: 'negatiivinen'
  },
  {
    id: 144,
    aikaleima: '2026-03-01T12:00:00',
    virpiId: 'oikeus_fi',
    sivu: 'Lait ja asetukset',
    nimi: 'Petteri Niemi',
    sahkoposti: '',
    palaute: 'Lakien ajantasaisuus on epäselvää. Pitäisi näkyä selkeästi milloin laki on viimeksi päivitetty.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 145,
    aikaleima: '2026-01-29T14:00:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Etusivu',
    nimi: 'Lea Miettinen',
    sahkoposti: '',
    palaute: 'Sivuston saavutettavuusseloste on kattava ja rehellinen. Hyvä käytäntö.',
    kategoria: 'saavutettavuus',
    tunne: 'positiivinen'
  },
  {
    id: 146,
    aikaleima: '2026-02-23T09:15:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston haku ei löydä tuloksia jos käyttää lainausmerkkejä hakulausekkeessa.',
    kategoria: 'hakutoiminto',
    tunne: 'negatiivinen'
  },
  {
    id: 147,
    aikaleima: '2026-03-13T11:30:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Tapaamiset',
    nimi: 'Juhani Koskinen',
    sahkoposti: '',
    palaute: 'Toivoisin videotapaamisten mahdollisuutta vankiloissa. Pitkien matkojen päästä vierailu on hankalaa.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 148,
    aikaleima: '2026-01-18T11:20:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Ulosottohakemus',
    nimi: 'Tuija Laaksonen',
    sahkoposti: 'tuija.laaksonen@email.fi',
    palaute: 'Ulosottohakemuksen sähköinen allekirjoitus onnistui, mutta ohjeita joutui etsimään pitkään.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 149,
    aikaleima: '2026-02-10T15:45:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston navigaatiossa on liikaa tasoja. Kolme klikkausta ennen kuin löytää oikean sivun.',
    kategoria: 'navigointi',
    tunne: 'negatiivinen'
  },
  {
    id: 150,
    aikaleima: '2026-03-07T08:40:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Liiketoimintakieltorekisteri',
    nimi: 'Tero Lähteenmäki',
    sahkoposti: '',
    palaute: 'Sivuston tulostusversio on huono. Taustavärit tulevat tulosteeseen ja teksti on liian pientä.',
    kategoria: 'ulkoasu',
    tunne: 'negatiivinen'
  },
  {
    id: 151,
    aikaleima: '2026-01-22T13:50:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Konkurssiasiamies',
    nimi: 'Marketta Nikulainen',
    sahkoposti: '',
    palaute: 'Konkurssiasiamiehen päätökset pitäisi olla helpommin haettavissa. Nykyinen haku on kömpelö.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 152,
    aikaleima: '2026-02-04T10:10:00',
    virpiId: 'oikeus_fi',
    sivu: 'Oikeudenkäynti',
    nimi: 'Ari Partanen',
    sahkoposti: 'ari.partanen@yritys.fi',
    palaute: 'Oikeudenkäyntiprosessin kuvaus on liian yleinen. Haluaisin tarkempaa tietoa eri oikeusasteista.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 153,
    aikaleima: '2026-03-04T14:20:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Asiointi',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sähköisen asiointipalvelun ohje on liian pitkä. Pitäisi tiivistää oleelliset kohdat alkuun.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 154,
    aikaleima: '2026-01-27T16:15:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Yhteystiedot',
    nimi: 'Inkeri Salmela',
    sahkoposti: '',
    palaute: 'Yhteystiedoissa pitäisi olla myös sähköpostiosoitteet. Nyt näkyy vain puhelinnumerot.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 155,
    aikaleima: '2026-02-19T12:00:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Vankilat',
    nimi: 'Pentti Matikainen',
    sahkoposti: 'pentti.matikainen@email.fi',
    palaute: 'Vankiloiden sijaintitiedot ovat pääosin tarkat, mutta karttaupotuksen osoitetiedot kaipaavat tarkistusta.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 156,
    aikaleima: '2026-03-10T16:00:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston fontti on liian ohut. Heikkonäköisenä on vaikea lukea.',
    kategoria: 'saavutettavuus',
    tunne: 'negatiivinen'
  },
  {
    id: 157,
    aikaleima: '2026-01-15T12:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusaputoimistot',
    nimi: 'Kauko Väänänen',
    sahkoposti: '',
    palaute: 'Oikeusaputoimistojen lista voisi olla järjestetty myös maakunnittain, ei vain aakkosittain.',
    kategoria: 'navigointi',
    tunne: 'neutraali'
  },
  {
    id: 158,
    aikaleima: '2026-02-27T08:20:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Sakkorekisteri',
    nimi: 'Virpi Suominen',
    sahkoposti: 'virpi.suominen@email.fi',
    palaute: 'Sakkorekisteriotteen tilaaminen onnistui, mutta tilauksen edistymistä ei voi seurata.',
    kategoria: 'kaytettavyys',
    tunne: 'neutraali'
  },
  {
    id: 159,
    aikaleima: '2026-03-15T10:30:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Tietosuojavaltuutettu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Tietosuojavaltuutetun päätökset pitäisi olla avoimesti saatavilla hakukoneella. Nyt ne ovat piilossa.',
    kategoria: 'hakutoiminto',
    tunne: 'negatiivinen'
  },
  {
    id: 160,
    aikaleima: '2026-01-20T15:40:00',
    virpiId: 'oikeus_fi',
    sivu: 'Perheoikeus',
    nimi: 'Elsa Lehtinen',
    sahkoposti: '',
    palaute: 'Perheoikeutta koskevat sivut ovat liian juridisia. Selkokielinen versio olisi tarpeen.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 161,
    aikaleima: '2026-02-14T11:00:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Etusivu',
    nimi: 'Toivo Nurmi',
    sahkoposti: '',
    palaute: 'Sivusto toimii tabletilla kohtalaisesti, mutta osa lomakkeista ei skaalaudu oikein.',
    kategoria: 'mobiili',
    tunne: 'neutraali'
  },
  {
    id: 162,
    aikaleima: '2026-03-09T13:15:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Tiedotteet',
    nimi: '',
    sahkoposti: '',
    palaute: 'Tiedotteiden sivuttaminen on hankalaa. Pitäisi voida selata enemmän kuin 10 tiedotetta kerrallaan.',
    kategoria: 'kaytettavyys',
    tunne: 'negatiivinen'
  },
  {
    id: 163,
    aikaleima: '2026-01-25T10:25:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Etusivu',
    nimi: 'Tuija Karhu',
    sahkoposti: 'tuija.karhu@email.fi',
    palaute: 'Sivuston kielivaihtoehdoissa pitäisi olla myös venäjä ja arabia. Monella vangilla nämä ovat äidinkieliä.',
    kategoria: 'kieliversiot',
    tunne: 'neutraali'
  },
  {
    id: 164,
    aikaleima: '2026-02-07T14:50:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Maksujärjestelyt',
    nimi: 'Ville Mäkelä',
    sahkoposti: '',
    palaute: 'Maksujärjestelyjen ehdot on esitetty, mutta eri vaihtoehtojen vertailu keskenään on hankalaa.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 165,
    aikaleima: '2026-03-05T09:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusapu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Oikeusapulaskuriin pitäisi syöttää vähemmän tietoja. Nykyinen versio kysyy liikaa yksityiskohtia.',
    kategoria: 'kaytettavyys',
    tunne: 'negatiivinen'
  },
  {
    id: 166,
    aikaleima: '2026-01-28T16:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Kaupparekisteri',
    nimi: 'Ilpo Koivunen',
    sahkoposti: '',
    palaute: 'Kaupparekisterin tiedot vaikuttavat luotettavilta, mutta päivitysajankohta ei näy tuloksissa.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 167,
    aikaleima: '2026-02-22T08:35:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Lapsiasiavaltuutettu',
    nimi: 'Helmi Korhonen',
    sahkoposti: 'helmi.korhonen@email.fi',
    palaute: 'Lapsiasiavaltuutetun sivut ovat informatiiviset mutta visuaalisesti laimeita. Voisi olla värikkäämpiä kun aihe koskee lapsia.',
    kategoria: 'ulkoasu',
    tunne: 'neutraali'
  },
  {
    id: 168,
    aikaleima: '2026-03-13T14:45:00',
    virpiId: 'oikeus_fi',
    sivu: 'Sovittelu',
    nimi: 'Sakari Heikkinen',
    sahkoposti: '',
    palaute: 'Sovittelun verkkohakemus on helppokäyttöinen. Lomake on lyhyt ja selkeä.',
    kategoria: 'lomakkeet',
    tunne: 'positiivinen'
  },
  {
    id: 169,
    aikaleima: '2026-01-16T13:10:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Lomakkeet',
    nimi: '',
    sahkoposti: '',
    palaute: 'Lomakkeiden PDF-versiot ovat huonolaatuisia. Teksti on epäselvää tulostettuna.',
    kategoria: 'lomakkeet',
    tunne: 'negatiivinen'
  },
  {
    id: 170,
    aikaleima: '2026-02-11T10:40:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Etusivu',
    nimi: 'Aulikki Mäkinen',
    sahkoposti: '',
    palaute: 'Sivuston etusivulla voisi olla lyhyt esittely syyttäjälaitoksen tehtävistä. Ei kaikki tiedä mitä syyttäjä tekee.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 171,
    aikaleima: '2026-03-02T15:20:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Yhteystiedot',
    nimi: 'Hannu Karjalainen',
    sahkoposti: 'hannu.karjalainen@email.fi',
    palaute: 'Rikosseuraamuslaitoksen puhelinpalvelun tiedot löytyvät, mutta jonotusajat eivät näy sivustolla.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 172,
    aikaleima: '2026-01-23T09:00:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Etusivu',
    nimi: 'Tyyne Aho',
    sahkoposti: '',
    palaute: 'Sivuston mobiilissa hamburger-valikko ei aukea. Testattu iPhonella ja Samsungilla.',
    kategoria: 'mobiili',
    tunne: 'negatiivinen'
  },
  {
    id: 173,
    aikaleima: '2026-02-16T14:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Edunvalvonta',
    nimi: '',
    sahkoposti: '',
    palaute: 'Edunvalvonnan sivuilla voisi olla useammin kysytyt kysymykset -osio. Helpottaisi tiedon löytämistä.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 174,
    aikaleima: '2026-03-11T08:15:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Rikosrekisteriote',
    nimi: 'Jaana Tuominen',
    sahkoposti: '',
    palaute: 'Rikosrekisteriotteen toimitusaika on liian pitkä. Pitäisi saada sähköisesti heti.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 175,
    aikaleima: '2026-01-19T11:45:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Kuluttajariitalautakunta',
    nimi: 'Pia Nurmi',
    sahkoposti: 'pia.nurmi@email.fi',
    palaute: 'Kuluttajariitalautakunnan palvelu on selkeä ja helppokäyttöinen. Valituksen tekeminen onnistui hyvin.',
    kategoria: 'kaytettavyys',
    tunne: 'positiivinen'
  },
  {
    id: 176,
    aikaleima: '2026-02-01T16:00:00',
    virpiId: 'oikeus_fi',
    sivu: 'Etusivu',
    nimi: 'Ensio Mäkinen',
    sahkoposti: '',
    palaute: 'Sivustolla pitäisi olla chatbot joka ohjaa oikeaan paikkaan. En löydä tarvitsemaani tietoa.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 177,
    aikaleima: '2026-03-07T11:00:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Käsittelyajat',
    nimi: '',
    sahkoposti: '',
    palaute: 'Käsittelyaika-arviot ovat hyödyllisiä. Tiedän nyt odottaa noin 6 kuukautta.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 178,
    aikaleima: '2026-01-31T08:30:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Rikosasiat',
    nimi: 'Pauli Ojanen',
    sahkoposti: '',
    palaute: 'Rikosilmoituksen tekeminen pitäisi olla mahdollista suoraan tältä sivustolta. Nyt ohjataan poliisin sivuille.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 179,
    aikaleima: '2026-02-26T10:20:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Etusivu',
    nimi: 'Pirkko Kallio',
    sahkoposti: 'pirkko.kallio@email.fi',
    palaute: 'Sivusto ei skaalaudu oikein suurella näytöllä. 4K-monitorilla teksti on todella pientä.',
    kategoria: 'ulkoasu',
    tunne: 'negatiivinen'
  },
  {
    id: 180,
    aikaleima: '2026-03-14T09:30:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Velkajärjestely',
    nimi: 'Jouni Laakso',
    sahkoposti: '',
    palaute: 'Velkajärjestelyn prosessikuvaus on olemassa, mutta vaiheittainen esitys voisi olla visuaalisempi.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 181,
    aikaleima: '2026-01-17T14:00:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusapu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Oikeusavun hakemisessa on liian pitkät käsittelyajat. Tämä ei ole sivustoa koskeva palaute, mutta haluan sanoa.',
    kategoria: 'sisalto',
    tunne: 'negatiivinen'
  },
  {
    id: 182,
    aikaleima: '2026-02-20T13:30:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Etusivu',
    nimi: 'Kaija Koivisto',
    sahkoposti: '',
    palaute: 'Sivuston kuvat latautuvat hitaasti. Voisiko kuvia optimoida pienempiä tiedostokokoja varten?',
    kategoria: 'latausnopeus',
    tunne: 'neutraali'
  },
  {
    id: 183,
    aikaleima: '2026-03-06T15:50:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Onnettomuustutkintakeskus',
    nimi: 'Mika Lehtonen',
    sahkoposti: 'mika.lehtonen@email.fi',
    palaute: 'Onnettomuustutkintakeskuksen raporttien hakemisto on erinomainen. Selkeä jaottelu ja hyvät suodattimet.',
    kategoria: 'navigointi',
    tunne: 'positiivinen'
  },
  {
    id: 184,
    aikaleima: '2026-01-26T08:45:00',
    virpiId: 'oikeus_fi',
    sivu: 'Tuomioistuimet',
    nimi: '',
    sahkoposti: '',
    palaute: 'Tuomioistuinten toimivaltaa koskeva tieto on epäselvää. Mikä tuomioistuin käsittelee mitäkin?',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 185,
    aikaleima: '2026-02-09T11:15:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Oikeustapaukset',
    nimi: 'Marjatta Salo',
    sahkoposti: '',
    palaute: 'Oikeustapauksissa pitäisi olla tiivistelmä jokaisesta tapauksesta. Nyt joutuu lukemaan koko päätöksen.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 186,
    aikaleima: '2026-03-01T14:10:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Syyttäjät',
    nimi: 'Olga Makkonen',
    sahkoposti: '',
    palaute: 'Syyttäjien erikoisosaamisalueet voisi näkyä profiileissa. Auttaisi ymmärtämään kuka hoitaa mitäkin.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 187,
    aikaleima: '2026-01-21T15:30:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Yhdyskuntaseuraamukset',
    nimi: '',
    sahkoposti: '',
    palaute: 'Yhdyskuntapalvelun suorittamista koskeva ohje on selkeä. Ymmärsin prosessin hyvin.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 188,
    aikaleima: '2026-02-13T09:50:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Asiointi',
    nimi: 'Rauno Niemi',
    sahkoposti: 'rauno.niemi@email.fi',
    palaute: 'Sähköiseen asiointiin kirjautuminen kestää liian kauan. Suomi.fi-tunnistautuminen vie aikaa.',
    kategoria: 'kaytettavyys',
    tunne: 'negatiivinen'
  },
  {
    id: 189,
    aikaleima: '2026-03-04T12:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Talous- ja velkaneuvonta',
    nimi: 'Irene Mäkelä',
    sahkoposti: '',
    palaute: 'Velkaneuvonnan ajanvaraus toimii periaatteessa, mutta aikoja on tarjolla hyvin vähän.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 190,
    aikaleima: '2026-01-29T10:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Oikeushallinnon rekisterit',
    nimi: '',
    sahkoposti: '',
    palaute: 'Rekisterihaussa tuloslistaus on sekava. Tulokset pitäisi ryhmitellä selkeämmin.',
    kategoria: 'hakutoiminto',
    tunne: 'negatiivinen'
  },
  {
    id: 191,
    aikaleima: '2026-02-18T16:20:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Tasa-arvovaltuutettu',
    nimi: 'Pirjo Haapanen',
    sahkoposti: '',
    palaute: 'Tasa-arvoasia kannustaisin ottamaan suoremmin kantaa sivustolla. Neutraali tyyli jättää kylmäksi.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 192,
    aikaleima: '2026-03-10T10:45:00',
    virpiId: 'oikeus_fi',
    sivu: 'Asiointi',
    nimi: 'Heimo Karvonen',
    sahkoposti: 'heimo.karvonen@email.fi',
    palaute: 'Sähköinen asiointi on kohentunut, mutta kehitettävää on edelleen erityisesti lomakkeiden käytettävyydessä.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 193,
    aikaleima: '2026-01-18T12:30:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Asiointi',
    nimi: 'Asta Virtanen',
    sahkoposti: '',
    palaute: 'Toivoisin mahdollisuutta lähettää asiakirjoja tuomioistuimeen suoraan sivuston kautta sähköisesti.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 194,
    aikaleima: '2026-02-01T15:00:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston tekstit ovat liian pitkiä. Pitäisi tiivistää ja käyttää enemmän väliotsikoita.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 195,
    aikaleima: '2026-03-08T07:30:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Tapaamiset',
    nimi: 'Riitta Heikkinen',
    sahkoposti: '',
    palaute: 'Tapaamisten sähköinen ajanvaraus on olemassa, mutta kalenterinäkymä on hidas ja vapaita aikoja näkyy vähän.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 196,
    aikaleima: '2026-01-24T09:20:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Ulosottohakemus',
    nimi: 'Kari Manninen',
    sahkoposti: 'kari.manninen@yritys.fi',
    palaute: 'Ulosottohakemuksen liitteiden lataaminen on hidasta. Isommat PDF:t eivät lataudu ollenkaan.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 197,
    aikaleima: '2026-02-15T11:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Yhteystiedot',
    nimi: '',
    sahkoposti: '',
    palaute: 'Yhteystiedot ovat saatavilla, mutta hakutoiminto ei anna tuloksia paikkakunnittain.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 198,
    aikaleima: '2026-03-12T14:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Asiointitili',
    nimi: 'Veikko Saarinen',
    sahkoposti: '',
    palaute: 'Asiointitilin tiedot päivittyvät hitaasti. Muutin osoitteeni viikko sitten eikä se vieläkään näy.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 199,
    aikaleima: '2026-01-20T16:45:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Yhdenvertaisuusvaltuutettu',
    nimi: 'Aune Partanen',
    sahkoposti: 'aune.partanen@email.fi',
    palaute: 'Yhdenvertaisuusvaltuutetun sivuilla voisi olla enemmän helppoa kielimuotoa. Kaikki eivät ymmärrä lakikieltä.',
    kategoria: 'saavutettavuus',
    tunne: 'neutraali'
  },
  {
    id: 200,
    aikaleima: '2026-02-06T13:00:00',
    virpiId: 'oikeus_fi',
    sivu: 'Rikosasiat',
    nimi: 'Tapio Leppänen',
    sahkoposti: '',
    palaute: 'Rikosasioiden prosessikaavio on erittäin havainnollinen. Ymmärsin heti miten prosessi etenee.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 201,
    aikaleima: '2026-03-03T09:45:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Evästeiden hallinta on monimutkaista. Pitäisi olla yksinkertainen hyväksy/hylkää-valinta.',
    kategoria: 'tietoturva',
    tunne: 'negatiivinen'
  },
  {
    id: 202,
    aikaleima: '2026-01-27T08:10:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Asiointi',
    nimi: 'Eveliina Saarinen',
    sahkoposti: '',
    palaute: 'Sähköisen asioinnin lomakkeet ovat rakenteeltaan loogisia, mutta ohjetekstit voisivat olla kattavampia.',
    kategoria: 'lomakkeet',
    tunne: 'neutraali'
  },
  {
    id: 203,
    aikaleima: '2026-02-21T14:15:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Lomakkeet',
    nimi: 'Kalevi Jokinen',
    sahkoposti: 'kalevi.jokinen@email.fi',
    palaute: 'Lomakkeiden tallennusominaisuus puuttuu. Jos selain kaatuu, kaikki tiedot häviävät.',
    kategoria: 'lomakkeet',
    tunne: 'negatiivinen'
  },
  {
    id: 204,
    aikaleima: '2026-03-09T16:30:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Palkan ulosmittaus',
    nimi: '',
    sahkoposti: '',
    palaute: 'Suojaosan laskentaohje on hyödyllinen. Nyt tiedän paljonko palkasta jää itselle.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 205,
    aikaleima: '2026-01-15T15:00:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusapu',
    nimi: 'Marjut Mikkonen',
    sahkoposti: '',
    palaute: 'Oikeusavun myöntämisperusteet pitäisi selittää yksinkertaisemmin. Nykyinen teksti on liian monimutkaista.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 206,
    aikaleima: '2026-02-12T10:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Etusivu',
    nimi: 'Mauri Hakala',
    sahkoposti: '',
    palaute: 'Sivuston hakukone ei osaa käsitellä yhdyssanoja oikein. Hakee vain kokonaisilla sanoilla.',
    kategoria: 'hakutoiminto',
    tunne: 'negatiivinen'
  },
  {
    id: 207,
    aikaleima: '2026-03-06T11:30:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Konkurssiasiamies',
    nimi: '',
    sahkoposti: '',
    palaute: 'Konkurssiasiamiehen sivuilta löytyy hyvin tietoa pesänhoitajan velvollisuuksista.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 208,
    aikaleima: '2026-01-22T09:30:00',
    virpiId: 'oikeus_fi',
    sivu: 'Etusivu',
    nimi: 'Ritva Virtanen',
    sahkoposti: 'ritva.virtanen@email.fi',
    palaute: 'Sivuston ulkoasu on nykyaikainen ja miellyttävä. Värit ovat sopivat ja teksti helppolukuista.',
    kategoria: 'ulkoasu',
    tunne: 'positiivinen'
  },
  {
    id: 209,
    aikaleima: '2026-02-03T14:40:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Yhteystiedot',
    nimi: '',
    sahkoposti: '',
    palaute: 'Tuomioistuinten aukioloajat pitäisi olla selvemmin esillä. Jouduin etsimään pitkään.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 210,
    aikaleima: '2026-03-15T13:00:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Tiedotteet',
    nimi: 'Tauno Heikkinen',
    sahkoposti: '',
    palaute: 'Tiedotteiden jako sosiaalisen median kautta olisi kätevä ominaisuus.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 211,
    aikaleima: '2026-01-30T11:00:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Vankilat',
    nimi: 'Annikki Pesonen',
    sahkoposti: 'annikki.pesonen@email.fi',
    palaute: 'Vankiloiden vierailuohjeet ovat kattavat ja selkeät. Tiesin mitä odottaa ennen vierailua.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 212,
    aikaleima: '2026-02-17T15:00:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Maksujärjestelyt',
    nimi: '',
    sahkoposti: '',
    palaute: 'Maksujärjestely-lomakkeessa ei ole mahdollisuutta tallentaa keskeneräistä lomaketta. Kaikki tiedot häviävät jos lähtee sivulta.',
    kategoria: 'lomakkeet',
    tunne: 'negatiivinen'
  },
  {
    id: 213,
    aikaleima: '2026-03-04T08:00:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Yleinen edunvalvonta',
    nimi: 'Raili Lahtinen',
    sahkoposti: '',
    palaute: 'Edunvalvonnan palveluprosessi on kuvattu hyvin. Ymmärsin mitä prosessissa tapahtuu.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 214,
    aikaleima: '2026-01-25T14:20:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Rekisterit',
    nimi: 'Unto Partanen',
    sahkoposti: '',
    palaute: 'Rekisterien käyttöliittymä on vanhanaikainen. Tuntuu kuin olisi 2000-luvun alussa.',
    kategoria: 'ulkoasu',
    tunne: 'negatiivinen'
  },
  {
    id: 215,
    aikaleima: '2026-02-08T12:15:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Tietosuojavaltuutettu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Tietosuojailmoituksen tekeminen on nyt helpompaa kuin ennen. Prosessi on selkeä.',
    kategoria: 'kaytettavyys',
    tunne: 'positiivinen'
  },
  {
    id: 216,
    aikaleima: '2026-03-02T10:30:00',
    virpiId: 'oikeus_fi',
    sivu: 'Lait ja asetukset',
    nimi: 'Anneli Niskanen',
    sahkoposti: 'anneli.niskanen@email.fi',
    palaute: 'Lakitekstin rinnakkainen vertailu eri versioiden välillä olisi erittäin hyödyllinen ominaisuus.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 217,
    aikaleima: '2026-01-16T16:30:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Etusivu',
    nimi: 'Seppo Koivula',
    sahkoposti: '',
    palaute: 'Sivuston hakutuloksia ei voi suodattaa. Pitäisi voida rajata esim. tuomioistuimen tai ajankohdan mukaan.',
    kategoria: 'hakutoiminto',
    tunne: 'negatiivinen'
  },
  {
    id: 218,
    aikaleima: '2026-02-24T09:00:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Rikosasiat',
    nimi: 'Eila Laakso',
    sahkoposti: '',
    palaute: 'Toivoisin interaktiivista opasta joka auttaa ymmärtämään rikosprosessin eri vaiheita.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 219,
    aikaleima: '2026-03-11T15:40:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Kuntoutus',
    nimi: '',
    sahkoposti: '',
    palaute: 'Kuntoutusohjelmien tuloksia ja vaikuttavuustietoja olisi kiinnostava nähdä sivustolla.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 220,
    aikaleima: '2026-01-19T10:15:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Yhteystiedot',
    nimi: 'Matti Salonen',
    sahkoposti: 'matti.salonen@email.fi',
    palaute: 'Ulosottoviraston chat-palvelu on olemassa, mutta vastausajat vaihtelevat suuresti.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 221,
    aikaleima: '2026-02-10T14:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Etusivu',
    nimi: 'Hilma Korhonen',
    sahkoposti: '',
    palaute: 'Sivuston latausnopeus mobiilissa on hidas. Etusivu latautuu yli 8 sekuntia 4G-yhteydellä.',
    kategoria: 'latausnopeus',
    tunne: 'negatiivinen'
  },
  {
    id: 222,
    aikaleima: '2026-03-07T12:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Konkurssirekisteri',
    nimi: '',
    sahkoposti: '',
    palaute: 'Konkurssirekisterin hakutulokset voisivat sisältää enemmän tietoa suoraan listanäkymässä.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 223,
    aikaleima: '2026-01-23T13:40:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Lapsiasiavaltuutettu',
    nimi: 'Soile Koivunen',
    sahkoposti: 'soile.koivunen@email.fi',
    palaute: 'Lapsiasiavaltuutetun materiaalit ovat hyödyllisiä. Käytämme niitä päiväkodissa.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 224,
    aikaleima: '2026-02-14T08:00:00',
    virpiId: 'oikeus_fi',
    sivu: 'Sanasto',
    nimi: 'Pertti Tuominen',
    sahkoposti: '',
    palaute: 'Sanastoon voisi lisätä linkit aiheeseen liittyviin lakeihin. Olisi kätevä jatkolukemista varten.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 225,
    aikaleima: '2026-03-13T10:20:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Lomakkeet',
    nimi: 'Orvokki Mäkelä',
    sahkoposti: '',
    palaute: 'Lomakkeiden lataaminen PDF-muodossa on kätevää. Voi tulostaa ja täyttää rauhassa.',
    kategoria: 'lomakkeet',
    tunne: 'positiivinen'
  },
  {
    id: 226,
    aikaleima: '2026-01-28T11:30:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston alatunniste on täynnä linkkejä joita kukaan ei käytä. Pitäisi siivota.',
    kategoria: 'navigointi',
    tunne: 'neutraali'
  },
  {
    id: 227,
    aikaleima: '2026-02-19T15:15:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Etusivu',
    nimi: 'Asko Laine',
    sahkoposti: '',
    palaute: 'Sivuston HTTPS-sertifikaatti aiheuttaa varoituksen selaimessa. Pitäisi uusia.',
    kategoria: 'tietoturva',
    tunne: 'negatiivinen'
  },
  {
    id: 228,
    aikaleima: '2026-03-05T11:00:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Etusivu',
    nimi: 'Liisa Ahola',
    sahkoposti: 'liisa.ahola@email.fi',
    palaute: 'Sivuston etusivu on kohtalaisen informatiivinen, mutta tärkeimmät palvelut voisivat olla paremmin esillä.',
    kategoria: 'kaytettavyys',
    tunne: 'neutraali'
  },
  {
    id: 229,
    aikaleima: '2026-01-31T09:00:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusaputoimistot',
    nimi: '',
    sahkoposti: '',
    palaute: 'Oikeusaputoimistojen sivuilla pitäisi näkyä reaaliaikaiset jonotusajat.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 230,
    aikaleima: '2026-02-25T14:30:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Sakkorekisteri',
    nimi: 'Helena Miettinen',
    sahkoposti: '',
    palaute: 'Sakkorekisterin tietoja pitäisi päivittää useammin. Tiedot ovat viikkoja jäljessä.',
    kategoria: 'sisalto',
    tunne: 'negatiivinen'
  },
  {
    id: 231,
    aikaleima: '2026-03-10T13:00:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Kuluttajariitalautakunta',
    nimi: 'Pasi Hämäläinen',
    sahkoposti: 'pasi.hamalainen@email.fi',
    palaute: 'Kuluttajariitalautakunnan valituslomake on selkeä ja helppotäyttöinen.',
    kategoria: 'lomakkeet',
    tunne: 'positiivinen'
  },
  {
    id: 232,
    aikaleima: '2026-01-17T10:30:00',
    virpiId: 'oikeus_fi',
    sivu: 'Oikeudenkäynti',
    nimi: 'Raija Koskinen',
    sahkoposti: '',
    palaute: 'Oikeudenkäyntiin valmistautumisen ohje on todella hyödyllinen. Ei tiennyt mitä odottaa.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 233,
    aikaleima: '2026-02-02T12:00:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Asiointi',
    nimi: '',
    sahkoposti: '',
    palaute: 'Haluaisin sähköpostihälytyksen kun tuomioistuimen käsittelypäivä on päätetty.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 234,
    aikaleima: '2026-03-04T10:15:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Syyttäjät',
    nimi: 'Aino Väisänen',
    sahkoposti: '',
    palaute: 'Syyttäjien yhteystiedot ovat saatavilla, mutta tiedoissa ei mainita vastaanottopäiviä.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 235,
    aikaleima: '2026-01-26T15:50:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Tapaamiset',
    nimi: 'Armi Salminen',
    sahkoposti: 'armi.salminen@email.fi',
    palaute: 'Tapaamisten ajanvarausjärjestelmässä ei näy peruutuspaikkoja. Pitäisi voida varata peruutusaika.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 236,
    aikaleima: '2026-02-17T08:30:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Velkajärjestely',
    nimi: '',
    sahkoposti: '',
    palaute: 'Velkajärjestelystä pitäisi olla yksinkertainen animaatio tai video. Teksti on liian raskas luettavaksi.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 237,
    aikaleima: '2026-03-12T16:10:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Talous- ja velkaneuvonta',
    nimi: 'Marja-Leena Huttunen',
    sahkoposti: '',
    palaute: 'Velkaneuvonnan itsepalvelutyökalut ovat erinomaisia. Budjetointilaskuri on erityisen hyvä.',
    kategoria: 'toiminnallisuus',
    tunne: 'positiivinen'
  },
  {
    id: 238,
    aikaleima: '2026-01-21T10:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Etusivu',
    nimi: 'Olavi Heikkinen',
    sahkoposti: '',
    palaute: 'Sivuston navigaatio on parantunut. Ennen eksyin jatkuvasti, nyt löydän oikeat sivut.',
    kategoria: 'navigointi',
    tunne: 'positiivinen'
  },
  {
    id: 239,
    aikaleima: '2026-02-07T15:30:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Onnettomuustutkintakeskus',
    nimi: '',
    sahkoposti: '',
    palaute: 'Onnettomuustutkintaraporttien sivumäärät ovat suuria ja lataaminen kestää. Voisi olla tiivistelmäversiot.',
    kategoria: 'latausnopeus',
    tunne: 'neutraali'
  },
  {
    id: 240,
    aikaleima: '2026-03-01T14:45:00',
    virpiId: 'oikeus_fi',
    sivu: 'Etusivu',
    nimi: 'Erkki Saarela',
    sahkoposti: 'erkki.saarela@email.fi',
    palaute: 'Sivuston etusivun uutissyöte on hyödyllinen. Pysyn ajan tasalla oikeushallinnon muutoksista.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 241,
    aikaleima: '2026-01-18T08:00:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Oikeustapaukset',
    nimi: 'Maire Koskinen',
    sahkoposti: '',
    palaute: 'Oikeustapaushaussa pitäisi olla mahdollisuus tallentaa hakuja ja saada ilmoitus uusista osumista.',
    kategoria: 'hakutoiminto',
    tunne: 'neutraali'
  },
  {
    id: 242,
    aikaleima: '2026-02-11T13:00:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Asiointi',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sähköinen asiointi ei toimi viikonloppuisin. Sain virheilmoituksen lauantaina.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 243,
    aikaleima: '2026-03-09T08:15:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Yhteystiedot',
    nimi: 'Simo Koivisto',
    sahkoposti: '',
    palaute: 'Yhteystietosivulla voisi olla myös yhteydenottolomake sähköpostin sijaan. Olisi helpompaa.',
    kategoria: 'lomakkeet',
    tunne: 'neutraali'
  },
  {
    id: 244,
    aikaleima: '2026-01-24T12:30:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Asiointi',
    nimi: 'Terttu Mäkinen',
    sahkoposti: 'terttu.makinen@email.fi',
    palaute: 'Asioinnin sähköinen allekirjoitus on selkeä ja turvallinen. Hyvä toteutus.',
    kategoria: 'tietoturva',
    tunne: 'positiivinen'
  },
  {
    id: 245,
    aikaleima: '2026-02-22T11:20:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Edunvalvonta',
    nimi: '',
    sahkoposti: '',
    palaute: 'Edunvalvonnan lomakkeet eivät ole saavutettavia ruudunlukuohjelmalla. WCAG-vaatimukset eivät täyty.',
    kategoria: 'saavutettavuus',
    tunne: 'negatiivinen'
  },
  {
    id: 246,
    aikaleima: '2026-03-14T08:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Rikosrekisteriote',
    nimi: 'Aulis Mäkelä',
    sahkoposti: '',
    palaute: 'Rikosrekisteriotteen tilausvahvistus tulee liian hitaasti sähköpostiin. Kesti 3 päivää.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 247,
    aikaleima: '2026-01-29T12:45:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Tasa-arvovaltuutettu',
    nimi: 'Marjo Heikkinen',
    sahkoposti: 'marjo.heikkinen@email.fi',
    palaute: 'Tasa-arvovaltuutetun ratkaisutietokanta on hyödyllinen. Auttaa ymmärtämään miten asioita on ratkaistu.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 248,
    aikaleima: '2026-02-16T10:45:00',
    virpiId: 'oikeus_fi',
    sivu: 'Sovittelu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sovittelun hakeminen verkossa on vaikeaa. Lomake on piilotettu monen klikkauksen taakse.',
    kategoria: 'navigointi',
    tunne: 'negatiivinen'
  },
  {
    id: 249,
    aikaleima: '2026-03-03T13:30:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Käsittelyajat',
    nimi: 'Kaarlo Räsänen',
    sahkoposti: '',
    palaute: 'Käsittelyaikadatan lataaminen CSV-muodossa olisi hyödyllistä tutkijoille ja toimittajille.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 250,
    aikaleima: '2026-01-31T14:00:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Tiedotteet',
    nimi: 'Rakel Mäntylä',
    sahkoposti: '',
    palaute: 'Tiedotteet ovat hyvin kirjoitettuja ja selkeitä. Ymmärrän mitä on tapahtunut.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 251,
    aikaleima: '2026-02-23T16:00:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Vankilat',
    nimi: '',
    sahkoposti: '',
    palaute: 'Vankiloiden postiosoitteet pitäisi olla helpommin löydettävissä. Nyt ne ovat piilossa.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 252,
    aikaleima: '2026-03-08T09:00:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Ulosottohakemus',
    nimi: 'Anita Salmi',
    sahkoposti: 'anita.salmi@yritys.fi',
    palaute: 'Ulosottohakemuksen ohje-teksti on liian pitkä. Voisi tiivistää oleelliset kohdat alkuun.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 253,
    aikaleima: '2026-01-20T08:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusapu',
    nimi: 'Tellervo Laaksonen',
    sahkoposti: '',
    palaute: 'Oikeusapuhakemuksen voi lähettää sähköisesti, mutta vahvistusta joutuu odottamaan useita päiviä.',
    kategoria: 'lomakkeet',
    tunne: 'neutraali'
  },
  {
    id: 254,
    aikaleima: '2026-02-05T12:15:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Liiketoimintakieltorekisteri',
    nimi: '',
    sahkoposti: '',
    palaute: 'Liiketoimintakieltorekisterin tiedot eivät ole ajantasaisia. Löysin tietoja jotka oli kumottu kuukausia sitten.',
    kategoria: 'sisalto',
    tunne: 'negatiivinen'
  },
  {
    id: 255,
    aikaleima: '2026-03-11T16:20:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Yhdenvertaisuusvaltuutettu',
    nimi: 'Kerttu Numminen',
    sahkoposti: '',
    palaute: 'Yhdenvertaisuusvaltuutetun verkkosivut toimivat hyvin ruudunlukuohjelmalla. Hyvä saavutettavuus.',
    kategoria: 'saavutettavuus',
    tunne: 'positiivinen'
  },
  {
    id: 256,
    aikaleima: '2026-01-25T13:00:00',
    virpiId: 'oikeus_fi',
    sivu: 'Perheoikeus',
    nimi: 'Kalevi Lindström',
    sahkoposti: 'kalevi.lindstrom@email.fi',
    palaute: 'Avioeroa koskevat ohjeet ovat erittäin selkeät. Prosessi ei ollut niin pelottava kuin luulin.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 257,
    aikaleima: '2026-02-09T09:30:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Etusivu',
    nimi: 'Taimi Kortelainen',
    sahkoposti: '',
    palaute: 'Sivustolla voisi olla palaute-painike jokaisella sivulla. Nyt palautelomake on vain yhdessä paikassa.',
    kategoria: 'kaytettavyys',
    tunne: 'neutraali'
  },
  {
    id: 258,
    aikaleima: '2026-03-06T14:00:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Rikosasiat',
    nimi: '',
    sahkoposti: '',
    palaute: 'Rikosasioiden termistö on liian vaikeaa tavalliselle kansalaiselle. Tarvitaan selkokielinen versio.',
    kategoria: 'sisalto',
    tunne: 'negatiivinen'
  },
  {
    id: 259,
    aikaleima: '2026-01-22T14:40:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Yhdyskuntaseuraamukset',
    nimi: 'Paavo Rantala',
    sahkoposti: '',
    palaute: 'Yhdyskuntapalvelun suorituspaikkojen karttanäkymä olisi hyödyllinen.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 260,
    aikaleima: '2026-02-13T11:00:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Palkan ulosmittaus',
    nimi: 'Eeva Laakso',
    sahkoposti: 'eeva.laakso@email.fi',
    palaute: 'Palkan ulosmittausta koskevat ohjeet ovat erittäin selkeät. Taulukko on havainnollinen.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 261,
    aikaleima: '2026-03-15T07:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Toivoisin mahdollisuutta varata aika oikeusaputoimistoon suoraan verkossa kalenterinäkymästä.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 262,
    aikaleima: '2026-01-27T10:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Kaupparekisteri',
    nimi: 'Jorma Salonen',
    sahkoposti: '',
    palaute: 'Kaupparekisteritietojen hakutulosten vienti Exceliin olisi todella hyödyllinen ominaisuus.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 263,
    aikaleima: '2026-02-20T15:15:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Konkurssiasiamies',
    nimi: 'Arja Mäkinen',
    sahkoposti: 'arja.makinen@yritys.fi',
    palaute: 'Konkurssiasiamiehen sivusto on päivittynyt hyvin. Uusi ulkoasu on selkeä ja ammattimainen.',
    kategoria: 'ulkoasu',
    tunne: 'positiivinen'
  },
  {
    id: 264,
    aikaleima: '2026-03-04T16:00:00',
    virpiId: 'oikeus_fi',
    sivu: 'Tuomioistuimet',
    nimi: '',
    sahkoposti: '',
    palaute: 'Tuomioistuinten toimialuetiedot ovat vanhentuneita. Käräjäoikeuksien tuomiopiirit ovat muuttuneet.',
    kategoria: 'sisalto',
    tunne: 'negatiivinen'
  },
  {
    id: 265,
    aikaleima: '2026-01-15T11:30:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Yhteystiedot',
    nimi: 'Sirkka Pitkänen',
    sahkoposti: '',
    palaute: 'Tuomioistuinten puhelinpalvelun aukioloajat pitäisi olla selvemmin esillä.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 266,
    aikaleima: '2026-02-04T13:30:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Etusivu',
    nimi: 'Arvo Pesonen',
    sahkoposti: '',
    palaute: 'Sivuston mobiiliversio on toimiva ja nopea. Käytän sitä usein puhelimella.',
    kategoria: 'mobiili',
    tunne: 'positiivinen'
  },
  {
    id: 267,
    aikaleima: '2026-03-02T08:45:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston ponnahdusikkuna-ilmoitukset ovat häiritseviä. Tulevat liian usein ja peittävät sisällön.',
    kategoria: 'kaytettavyys',
    tunne: 'negatiivinen'
  },
  {
    id: 268,
    aikaleima: '2026-01-30T15:00:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Maksujärjestelyt',
    nimi: 'Tuomo Ahonen',
    sahkoposti: 'tuomo.ahonen@email.fi',
    palaute: 'Maksujärjestelyn hakeminen verkossa on helppoa ja nopeaa. Ei tarvinnut jonottaa puhelimessa.',
    kategoria: 'kaytettavyys',
    tunne: 'positiivinen'
  },
  {
    id: 269,
    aikaleima: '2026-02-18T09:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Yleinen edunvalvonta',
    nimi: 'Maija-Liisa Korhonen',
    sahkoposti: '',
    palaute: 'Edunvalvonnan hakemislomake on vaikeasti löydettävissä. Jouduin googlettamaan.',
    kategoria: 'navigointi',
    tunne: 'negatiivinen'
  },
  {
    id: 270,
    aikaleima: '2026-03-10T12:15:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Oikeushallinnon rekisterit',
    nimi: '',
    sahkoposti: '',
    palaute: 'Rekisterien käyttöoikeushakemuksen käsittelyaika on liian pitkä. Pitäisi automatisoida.',
    kategoria: 'toiminnallisuus',
    tunne: 'negatiivinen'
  },
  {
    id: 271,
    aikaleima: '2026-01-19T14:00:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Tietosuojavaltuutettu',
    nimi: 'Jaakko Virtanen',
    sahkoposti: '',
    palaute: 'Tietosuojavaltuutetun sivujen FAQ-osio on todella hyödyllinen. Löysin vastauksen nopeasti.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 272,
    aikaleima: '2026-02-06T16:30:00',
    virpiId: 'oikeus_fi',
    sivu: 'Asiointi',
    nimi: 'Marjatta Koskinen',
    sahkoposti: 'marjatta.koskinen@email.fi',
    palaute: 'Asiointipalvelussa pitäisi olla mahdollisuus tallentaa asioinnin keskeneräinen tila ja jatkaa myöhemmin.',
    kategoria: 'kaytettavyys',
    tunne: 'neutraali'
  },
  {
    id: 273,
    aikaleima: '2026-03-07T10:30:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Asiointi',
    nimi: 'Kyllikki Rantanen',
    sahkoposti: '',
    palaute: 'Sähköisen asioinnin PDF-lomakkeet ovat hyvin suunniteltuja. Ohjeet ovat selkeät.',
    kategoria: 'lomakkeet',
    tunne: 'positiivinen'
  },
  {
    id: 274,
    aikaleima: '2026-01-23T07:30:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Yhteystiedot',
    nimi: '',
    sahkoposti: '',
    palaute: 'Syyttäjänvirastojen yhteystietosivulla chat-ikkuna peittää osan sisällöstä eikä sitä voi sulkea.',
    kategoria: 'kaytettavyys',
    tunne: 'negatiivinen'
  },
  {
    id: 275,
    aikaleima: '2026-02-15T10:00:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Kuntoutus',
    nimi: 'Viljo Lahtinen',
    sahkoposti: 'viljo.lahtinen@email.fi',
    palaute: 'Päihdekuntoutusohjelman kuvaus on hyvä. Selkeä ja informatiivinen.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 276,
    aikaleima: '2026-03-13T08:45:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Etusivu',
    nimi: 'Ritva Mikkola',
    sahkoposti: '',
    palaute: 'Sivuston teksteissä on kirjoitusvirheitä. Esim. "ulosoottohakemus" Maksujärjestelyt-sivulla.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 277,
    aikaleima: '2026-01-26T11:00:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Oikeusapu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Oikeusavun tulorajat on esitetty hyvin taulukossa. Selkeä ja ymmärrettävä.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 278,
    aikaleima: '2026-02-28T09:15:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Etusivu',
    nimi: 'Taisto Mäkinen',
    sahkoposti: '',
    palaute: 'Sivuston asettelua on vaikea hahmottaa. Sisältö on liian levällään isolla näytöllä.',
    kategoria: 'ulkoasu',
    tunne: 'negatiivinen'
  },
  {
    id: 279,
    aikaleima: '2026-03-05T13:00:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Kuluttajariitalautakunta',
    nimi: 'Elvi Mäkelä',
    sahkoposti: 'elvi.makela@email.fi',
    palaute: 'Kuluttajariitalautakunnan käsittelyaika-arvio pitäisi näkyä sivustolla. En tiedä kuinka kauan joudun odottamaan.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 280,
    aikaleima: '2026-01-17T09:00:00',
    virpiId: 'oikeus_fi',
    sivu: 'Rikosasiat',
    nimi: 'Antti Mäkelä',
    sahkoposti: '',
    palaute: 'Rikosasioiden käsittelyprosessin kaavio on todella havainnollinen. Ymmärsin prosessin heti.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 281,
    aikaleima: '2026-02-01T11:30:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston hakukenttä on liian pieni. Ei mahdu kirjoittamaan pidempää hakulauseketta.',
    kategoria: 'hakutoiminto',
    tunne: 'negatiivinen'
  },
  {
    id: 282,
    aikaleima: '2026-03-09T14:30:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Asiointi',
    nimi: 'Aulis Korhonen',
    sahkoposti: '',
    palaute: 'Sähköisen asioinnin vahvistusviesti tulee, mutta siinä ei kerrota arvioitua käsittelyaikaa.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 283,
    aikaleima: '2026-01-28T08:15:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Tapaamiset',
    nimi: 'Tyyne Saarinen',
    sahkoposti: 'tyyne.saarinen@email.fi',
    palaute: 'Tapaamisten vahvistusviesti tulee sähköpostiin, mutta peruuttaminen onnistuu vain soittamalla.',
    kategoria: 'toiminnallisuus',
    tunne: 'neutraali'
  },
  {
    id: 284,
    aikaleima: '2026-02-21T10:00:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Velkajärjestely',
    nimi: '',
    sahkoposti: '',
    palaute: 'Velkajärjestelyn hakemislomakkeessa on epäselvä ohjeteksti. "Täytä tarvittavat tiedot" ei kerro mitä oikeasti tarvitaan.',
    kategoria: 'lomakkeet',
    tunne: 'negatiivinen'
  },
  {
    id: 285,
    aikaleima: '2026-03-12T09:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Talous- ja velkaneuvonta',
    nimi: 'Jouko Tuominen',
    sahkoposti: '',
    palaute: 'Velkaneuvonnan verkkomateriaalit ovat kattavia. Erityisesti velkajärjestelyopas on hyvä.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 286,
    aikaleima: '2026-01-22T15:30:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Sakkorekisteri',
    nimi: 'Vappu Laine',
    sahkoposti: '',
    palaute: 'Sakkorekisterin sivuilla on selkeä ohje miten oma sakkohistoria tarkistetaan.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 287,
    aikaleima: '2026-02-12T14:40:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Erityisviranomaisten sivusto ei ole yhtenäinen. Jokainen viranomainen näyttää erilaiselta.',
    kategoria: 'ulkoasu',
    tunne: 'negatiivinen'
  },
  {
    id: 288,
    aikaleima: '2026-03-01T11:00:00',
    virpiId: 'oikeus_fi',
    sivu: 'Lait ja asetukset',
    nimi: 'Heikki Mäkelä',
    sahkoposti: 'heikki.makela@email.fi',
    palaute: 'Lakien haku on nopea ja tarkka. Löysin oikean lain heti ensimmäisellä hakukerralla.',
    kategoria: 'hakutoiminto',
    tunne: 'positiivinen'
  },
  {
    id: 289,
    aikaleima: '2026-01-16T12:00:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Oikeustapaukset',
    nimi: 'Raija Koivula',
    sahkoposti: '',
    palaute: 'Oikeustapausten julkaisutahti on hyvä. Uudet päätökset tulevat nopeasti sivulle.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 290,
    aikaleima: '2026-02-04T08:00:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Syyttäjät',
    nimi: '',
    sahkoposti: '',
    palaute: 'Syyttäjien profiilisivuilla voisi olla tietoa erikoisosaamisesta. Nyt näkyy vain nimi ja toimisto.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 291,
    aikaleima: '2026-03-03T15:00:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Vankilat',
    nimi: 'Esa Lindholm',
    sahkoposti: '',
    palaute: 'Vankiloiden vierailutietojen löytäminen on helppoa. Selkeä sivurakenne.',
    kategoria: 'navigointi',
    tunne: 'positiivinen'
  },
  {
    id: 292,
    aikaleima: '2026-01-20T09:30:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Usein kysytyt kysymykset',
    nimi: 'Anna-Liisa Virtanen',
    sahkoposti: 'anna-liisa.virtanen@email.fi',
    palaute: 'UKK-osion kysymykset on ryhmitelty hyvin aiheittain. Löydän etsimäni nopeasti.',
    kategoria: 'navigointi',
    tunne: 'positiivinen'
  },
  {
    id: 293,
    aikaleima: '2026-02-11T15:30:00',
    virpiId: 'oikeuspalveluvirasto',
    sivu: 'Edunvalvonta',
    nimi: '',
    sahkoposti: '',
    palaute: 'Edunvalvonnan palvelukuvaus on liian yleinen. Haluaisin konkreettisia esimerkkejä mitä edunvalvoja tekee.',
    kategoria: 'sisalto',
    tunne: 'neutraali'
  },
  {
    id: 294,
    aikaleima: '2026-03-06T10:00:00',
    virpiId: 'oikeusrekisterikeskus',
    sivu: 'Rekisterit',
    nimi: 'Pentti Virtanen',
    sahkoposti: '',
    palaute: 'Rekisterien tietosuojaseloste on selkeä. Tiedän miten tietojani käsitellään.',
    kategoria: 'tietoturva',
    tunne: 'positiivinen'
  },
  {
    id: 295,
    aikaleima: '2026-01-25T08:00:00',
    virpiId: 'erityisviranomaiset',
    sivu: 'Tietosuojavaltuutettu',
    nimi: 'Hilkka Mäkinen',
    sahkoposti: 'hilkka.makinen@email.fi',
    palaute: 'Tietosuojavaltuutetun sivujen GDPR-opas yrityksille on erinomainen. Todella käytännöllinen.',
    kategoria: 'sisalto',
    tunne: 'positiivinen'
  },
  {
    id: 296,
    aikaleima: '2026-02-26T13:45:00',
    virpiId: 'oikeus_fi',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston hakutulokset latautuvat hitaasti. Joudun odottamaan useita sekunteja.',
    kategoria: 'latausnopeus',
    tunne: 'negatiivinen'
  },
  {
    id: 297,
    aikaleima: '2026-03-08T11:30:00',
    virpiId: 'tuomioistuinvirasto',
    sivu: 'Lomakkeet',
    nimi: 'Lauri Koivisto',
    sahkoposti: '',
    palaute: 'Toivoisin sähköistä allekirjoitusta kaikkiin lomakkeisiin. Nyt osa pitää vielä tulostaa ja postittaa.',
    kategoria: 'lomakkeet',
    tunne: 'neutraali'
  },
  {
    id: 298,
    aikaleima: '2026-02-08T14:00:00',
    virpiId: 'syyttajalaitos',
    sivu: 'Rikosasiat',
    nimi: 'Lea Heikkinen',
    sahkoposti: 'lea.heikkinen@email.fi',
    palaute: 'Rikosasioiden seuranta pitäisi olla mahdollista mobiilisovelluksella. Nettisivu ei riitä.',
    kategoria: 'mobiili',
    tunne: 'neutraali'
  },
  {
    id: 299,
    aikaleima: '2026-03-10T15:00:00',
    virpiId: 'rikosseuraamuslaitos',
    sivu: 'Etusivu',
    nimi: 'Kaarina Korhonen',
    sahkoposti: '',
    palaute: 'Sivuston yleisilme on parantunut huomattavasti. Uusi ulkoasu on selkeä ja moderni.',
    kategoria: 'ulkoasu',
    tunne: 'positiivinen'
  },
  {
    id: 300,
    aikaleima: '2026-01-31T16:30:00',
    virpiId: 'ulosottolaitos',
    sivu: 'Etusivu',
    nimi: '',
    sahkoposti: '',
    palaute: 'Sivuston saavutettavuus on puutteellinen. Näppäimistönavigaatio ei toimi kaikissa osioissa.',
    kategoria: 'saavutettavuus',
    tunne: 'negatiivinen'
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PALAUTTEET };
}
