// Auto-generated by scraper – 2026-04-15T07:46:54.707Z
// Do not edit manually
const MENUS = {
  "lastUpdated": "2026-04-15T07:46:54.707Z",
  "weekNumber": 16,
  "dateRange": "13.4.–17.4.2026",
  "menus": {
    "1": {
      "maanantai": [
        "PICK IT 14 € - Pannupihvejä kermaisessa pekoni-sipulikastikkeessa ja persiljaperunaa (L, G)",
        "CHOOSE IT 14 € - Punajuurifalafeleja ja fetajuustoa, pestocouscousia ja kermaista valkosipulikastiketta (L saatavilla G)",
        "LOVE IT 14,70 € - Reuben-sandwich: hapanjuurileipää, ylikypsää naudanrintaa ja sulatettua sveitsiläistä juustoa sekä ranskalaisia (L)",
        "SOUP IT 12,90 € - Kermaista maa-artisokkakeittoa ja yrttiöljyä (G, L)",
        "DESSERT IT - Sitruunarahkaa ja talon granolaa (L, G)"
      ],
      "tiistai": [
        "PICK IT 14 € - Chicken tikka masalaa, basmatiriisiä ja rapeaa sipulia sekä tuoretta korianteria (G, M)",
        "CHOOSE IT 14 € - Popcornilla friteerattua tofua teriyakikastikkeessa, jasmiiniriisiä ja inkivääripikkelöityjä kurkkuja (G, M, V)",
        "LOVE IT 14,70 € - Reuben-sandwich: hapanjuurileipää, ylikypsää naudanrintaa ja sulatettua sveitsiläistä juustoa sekä ranskalaisia (L)",
        "SOUP IT 12,90 € - Paahdettua palsternakkakeittoa ja chiliöljyä (G, L)",
        "DESSERT IT - Talon brownieita (L)"
      ],
      "keskiviikko": [
        "PICK IT 14 € - Lihapullia basilika-tomaattikastikkeessa, pastaa, chiliöljyä ja Grana Padano -juustoa (L)",
        "CHOOSE IT 14 € - Thaimaalaista punaista currya paistetulla tofulla, vihreitä papuja ja pinaattia sekä udonnuudeleita (M, V)",
        "LOVE IT 14,70 € - Misomarinoitua lohifileetä, sakekastiketta ja jasmiiniriisiä sekä inkiväärimarinoituja kurkkuja (G, M)",
        "SOUP IT 12,90 € - Kermaista metsäsienikeittoa (G, L)",
        "DESSERT IT - Mokkakakkua (L saattaa sis. pähkinää)"
      ],
      "torstai": [
        "PICK IT 14 € - Revittyä possua American-style BBQ -kastikkeella ja uuniperunoita sitruunavoilla (L, G)",
        "CHOOSE IT 14 € - Tofujauhista savuisessa meksikolaisessa salsassa, maissia ja korianteria sekä lime-riisiä (G, M, V)",
        "LOVE IT 14,70 € - Misomarinoitua lohifileetä, sakekastiketta ja jasmiiniriisiä sekä inkiväärimarinoituja kurkkuja (G, M)",
        "SOUP IT 12,90 € - Perinteistä hernekeittoa ja sinappia (G, M, Ve)",
        "DESSERT IT - Halon pannukakkua ja mansikkahilloa (L)"
      ],
      "perjantai": [
        "PICK IT / CHOOSE IT 14 € - Kebab Perjantai!",
        "LOVE IT 14,20 € - Misomarinoitua lohifileetä, sakekastiketta ja jasmiiniriisiä sekä inkiväärimarinoituja kurkkuja (G, M)",
        "SOUP IT 12,90 € - Paahdettua kukkakaalikeittoa ja paahdettuja juustokuminansiemeniä (L, G)",
        "DESSERT IT - Lajitelma keksejä"
      ]
    },
    "2": {
      "maanantai": [
        "1 MALAI KOFTA (G) 13.50€",
        "2 GOBI SAG (L,G,V) 13,50€",
        "3 BUTTER CHICKEN (L,G) 14,00€",
        "ACHARI LAMB (L,G) 13,90€",
        "5. CHILI FISH (L,G) 13,50€",
        "6. MIX THALI 14,90€",
        "7. ΜΑΑΝΑΝΤΑIN ERIKOISET- TANDOOR KING PRAWN (G) 19,90€",
        "8. MIX SIZZLER (L,G) 18,90€"
      ],
      "tiistai": [
        "1. SHAHI PANEER (G) 13.50€",
        "2. SAG CHANA (L,G,V) 13,50€",
        "3. CHICKEN TIKKA MASALA (L,G) 13,50€",
        "4.LAMB KOFTA (L,G) 13,90€",
        "5. SHRIMP CHILI (L,G) 13,50€",
        "6. MIX THALI 14,90€",
        "7. TIISTAIN ERIKOISET - BUTTER CHICKEN (L,G) 16,90€",
        "8. LAMB SIZZLER (L,G) 16,90€"
      ],
      "keskiviikko": [
        "1. PANEER BUTTER MASALA (G) 13.50€",
        "2. ALU GOBI (L,G,V) 13,50€",
        "3. CHICKEN SIRAZ (L,G) (L,G) 13,50€",
        "4. HANDI LAMB (L.G) 13,90€",
        "5. SHRIMP SAG (L,G) 13,50€",
        "6. MIX THALI 14,90€",
        "7. KESKIVIIKON ERIKOINEN - LAMB TIKKA MASALA (G) 19,90€",
        "8. BUTTER KING PRAWN (L,G) 19,90€"
      ],
      "torstai": [
        "1. SAG PANEER (G) 13.50€",
        "2. MUSHROOM TOFU MASALA (L,G,V) 13,50€",
        "3. CHICKEN TIKKA MASALA (L,G)) 13,50€",
        "4. ACHARI KABAB (L,G) 13,90€",
        "5. NARIWAL FISH (L,G) 13,50€",
        "6. MIX THALI 14,50€",
        "7. TORSTAIN ERIKOINEN - BUTTER CHICKEN (L,G) 16,90€",
        "8. LAMB SIZZLER (L,G) 16,90€"
      ],
      "perjantai": [
        "1. KARAHI PANEER (G) 13.50€",
        "2. TOFU CHANA MASALA (L,G,V) 13,50€",
        "3. BUTTER CHICKEN (L,G) 14,00€",
        "4. PUDINA LAMB (L.G) 13,90€",
        "5. SAG FISH (L.G) 13,50€",
        "6. MIX THALI 14,90€",
        "7. PERJANTAIN ERIKOISET - MANGO CHICKEN (L,G) 15,90€",
        "8. KING PRAWN SIZZLER (L,G) 19,90€"
      ]
    },
    "3": {
      "keskiviikko": [
        "Kukkakaalikeitto (L+G)",
        "Mureaa kookoskanaa tuoreella korianterilla (M+G+VS) basmatiriisi (VE+G)",
        "Fish & Chips – tempura-turskaa (M) parmesaani-yrttiranskalaiset (L+G) tryffelimajoneesi (VE+G)",
        "Täyteläinen herkkusienirisotto parmesaanilla (VL+G)",
        "Dal Makhani – linssi-papumuhennos tofulla (VE+G+VS)",
        "Omena-kaurapaistos (VE+gluteeniton kaura) vaniljakastike (L+G)"
      ],
      "torstai": [
        "Hernekeitto palvikinkulla (M+G) hienonnettua sipulia (VE+G)",
        "Factoryn juustolihapullat tex mex -cheddar-jalapenokastikkeessa (L+G+VS) valkosipuliperunat (VE+G+VS)",
        "Rapeaa paneroitua kanaa (M) riisi (VE+G) avocado-basilikakastike (L+G)",
        "Gruusialainen kaalilaatikko Gold & Green -suikaleilla (VE+G) puolukkahillo (VE+G)",
        "Factoryn letut (L) mansikkahillo (VE+G) vaniljavaahto (L+G) jäätelö (L+G)",
        "Vegaaniset gluteenittomat letut (VE+G)"
      ],
      "perjantai": [
        "Tom yam -jättirapukeitto (M+G+VS)",
        "Kebablastut mausteisessa tomaattikastikkeessa (M+G+VS) ranskalaiset (VE+G) valkosipulijogurtti (L+G+VS)",
        "Kana-pestopasta grillatulla halloumijuustolla ja herneenversoilla (VL+G)",
        "Salami-ananas-sipulipizza (VL+VS)",
        "Itse tehdyt porkkana-papupihvit (VE+G+VS) hummus (VE+G+VS)",
        "Factoryn jälkiruokalajitelma"
      ]
    },
    "4": {
      "maanantai": [
        "Jauheliha-caponatapasta & parmesaania (L) 13,00 €",
        "Tofu tikka masala ja basmatiriisiä (fodmap,Ve,G) & kasvissamosa (Ve) 13,00 €",
        "Bataatti-inkiväärisosekeitto (fodmap,Ve,G) 10,00 €",
        "Uuniperuna tonnikala-fetatäytteellä & vihersalaattia (fodmap,G,L) 12,20 €",
        "Uuniperuna chili sin carne täytteellä & vege fraiche & vihersalaattia (Ve,G) 12,20 €",
        "Kinkku-karamellisoitusipulisandwich & california slaw (L) 12,20 €",
        "Feta-falafeltoast & california slaw (L) 12,20 €",
        "Seesami-kanavarras salaatti (fodmap,G,M) 12,20 €"
      ],
      "tiistai": [
        "Kanaa tikkamasala, basmatiriisiä & kurkkuraita (fodmap,G,L) 13,00 €",
        "Portobelloraviolit & tomaattikastiketta (Ve) ja fetaa (L) 13,00 €",
        "Metsäsieni-jauhelihakeitto (G,L) 10,00 €",
        "Uuniperuna tonnikala-fetatäytteellä & vihersalaattia (fodmap,G,L) 12,20 €",
        "Uuniperuna chili sin carne täytteellä & vege fraiche & vihersalaattia (Ve,G) 12,20 €",
        "Kinkku-karamellisoitusipulisandwich & california slaw (L) 12,20 €",
        "Feta-falafeltoast & california slaw (L) 12,20 €",
        "Kreikkalainen tonnikalasalaatti (fodmap,G,L) 12,20 €"
      ],
      "keskiviikko": [
        "Cajun lohta & lime-ranch (G,L) 13,00 €",
        "Kreikkalainen feta-perunagratiini & hummusta (fodmap,G,L) 13,00 €",
        "Saariston siskonmakkarakeitto (G,L) 10,00 €",
        "Uuniperuna tonnikala-fetatäytteellä & vihersalaattia (fodmap,G,L) 12,20 €",
        "Uuniperuna chili sin carne täytteellä & vege fraiche & vihersalaattia (Ve,G) 12,20 €",
        "Kinkku-karamellisoitusipulisandwich & california slaw (L) 12,20 €",
        "Feta-falafeltoast & california slaw (L) 12,20 €",
        "Salaatti paahdetusta bataatista & vuohenjuustosta (fodmap,L,G) 12,20 €"
      ],
      "torstai": [
        "Kana-chorizopaella & aiolia (G,L) 13,00 €",
        "Punajuuripyörykät & paahdettua perunaa ja sienikastiketta (L,G) 13,00 €",
        "Hernekeitto (liha/vege) (G, M / Ve) & pannukakku (L) 10,00 €",
        "Uuniperuna tonnikala-fetatäytteellä & vihersalaattia (fodmap,G,L) 12,20 €",
        "Uuniperuna chili sin carne täytteellä & vege fraiche & vihersalaattia (Ve,G) 12,20 €",
        "Kinkku-karamellisoitusipulisandwich & california slaw (L) 12,20 €",
        "Feta-falafeltoast & california slaw (L) 12,20 €",
        "Katkarapu caesarsalaatti (G,L) 12,20 €"
      ],
      "perjantai": [
        "Paneroitua kanaa, ranskalaiset perunat & paprikamajoneesia (M) 13,00 €",
        "Meksikolainen papupata, nachoja & avocadosalsaa (Ve,G) ) 13,00 €",
        "Lohikeitto (fodmap,G,L) 10,00 €",
        "Uuniperuna tonnikala-fetatäytteellä & vihersalaattia (fodmap,G,L) 12,20 €",
        "Uuniperuna chili sin carne täytteellä & vege fraiche & vihersalaattia (Ve,G) 12,20 €",
        "Kinkku-karamellisoitusipulisandwich & california slaw (L) 12,20 €",
        "Feta-falafeltoast & california slaw (L) 12,20 €",
        "Lohipiirasta & coleslawsalaattia (L) 12,20 €"
      ]
    },
    "5": {
      "maanantai": [
        "Nordic buffet 13,80€: Punajuurisosekeittoa (A, G, ILM, L)",
        "Nordic buffet 13,80€: Tofua vihreässä currykastikkeessa - Luomutofu Green Curry (A, G, ILM, L, M, Veg, VS)",
        "Nordic buffet 13,80€: Riisiä ja kotimaista kauraa (A, G, L, M, Veg)",
        "Nordic buffet 13,80€: Italialaista jauhelihalasagnettea (A, L, VS)",
        "Nordic buffet 13,80€: Pastajuustoa (A, G, L)",
        "Nordic buffet 13,80€: Paahdettua kirjolohta (A, G, ILM, L, M)",
        "Nordic buffet 13,80€: Ruohosipuli-kermaviilikastiketta (A, G, ILM, L)",
        "Nordic buffet 13,80€: Perunamuusia (A, G, ILM, L)",
        "Nordic buffet 13,80€: Satokauden kasviksia (G, L, M, Veg)",
        "Nordic buffet 13,80€: Limerahkaa (A, G, L)",
        "Nordic buffet 13,80€: Päivän pizza",
        "Nordic buffet 13,80€: Päivän kasvispizza"
      ],
      "tiistai": [
        "Nordic buffet 13,80€: Savujuustokeittoa (A, G, ILM, L)",
        "Nordic buffet 13,80€: Fetajuustolla ja tomaatilla täytetty kikhernepihvi (A, G, VL, VS)",
        "Nordic buffet 13,80€: Broileri-katkarapupaellaa (A, G, L, M, VS)",
        "Nordic buffet 13,80€: Aiolia (A, G, L, M, VS)",
        "Nordic buffet 13,80€: Talon chilinen jauhelihapihvi (A, L, M, VS)",
        "Nordic buffet 13,80€: Tzatsikia (A, G, ILM, L, VS)",
        "Nordic buffet 13,80€: Timjamilla ja ruohosipulilla maustettuja perunoita (A, G, ILM, L, M, Veg)",
        "Nordic buffet 13,80€: Satokauden kasviksia (G, L, M, Veg)",
        "Nordic buffet 13,80€: Aprikoosipiirakkaa (A, L, M)",
        "Nordic buffet 13,80€: Vaniljakastiketta (A, G, L)",
        "Nordic buffet 13,80€: Päivän pizza",
        "Nordic buffet 13,80€: Päivän kasvispizza"
      ],
      "keskiviikko": [
        "Nordic buffet 13,80€: Linssi-kookoskeittoa (G, ILM, L, M, Veg, VS)",
        "Nordic buffet 13,80€: Kasvimakkara (G, ILM, L, M, Veg)",
        "Nordic buffet 13,80€: Artesaanimakkaraa ja bratvurstia (G, L, M)",
        "Nordic buffet 13,80€: Pekoni-hapankaalia (G, L, M)",
        "Nordic buffet 13,80€: Perunamuusia (A, G, ILM, L)",
        "Nordic buffet 13,80€: Sitruunaista rapeaa kalaa (A, L, M)",
        "Nordic buffet 13,80€: Tartarkastiketta (A, G, L, M)",
        "Nordic buffet 13,80€: Satokauden kasviksia (G, L, M, Veg)",
        "Nordic buffet 13,80€: Lakritsirahkaa (A, G, L)",
        "Nordic buffet 13,80€: Päivän pizza",
        "Nordic buffet 13,80€: Päivän kasvispizza"
      ],
      "torstai": [
        "Nordic buffet 13,80€: Sienestäjän sienikeittoa (A, ILM, L)",
        "Nordic buffet 13,80€: Vuohenjuusto-punajuurilasagnea (A, ILM, VL, VS)",
        "Nordic buffet 13,80€: Kylmäsavukirjolohipastaa (A, L, VS)",
        "Nordic buffet 13,80€: Pastajuustoa (A, G, L)",
        "Nordic buffet 13,80€: Briossi BRG Beef (A, L, M)",
        "Nordic buffet 13,80€: Maalaisranskalaisia (G, L, M, Veg)",
        "Nordic buffet 13,80€: Mansikkavispipuuroa (A, L, M, Veg)",
        "Nordic buffet 13,80€: Päivän pizza",
        "Nordic buffet 13,80€: Päivän kasvispizza"
      ],
      "perjantai": [
        "Nordic buffet 13,80€: Bataattikeittoa (A, G, L)",
        "Nordic buffet 13,80€: Paahdettua tofua, vegaanista Ndujaa ja rigatonipastaa (A, ILM, L, M, Veg, VS)",
        "Nordic buffet 13,80€: Lindströminpihvejä (A, L, M)",
        "Nordic buffet 13,80€: Perunamuusia (A, G, ILM, L)",
        "Nordic buffet 13,80€: Sipulikastiketta (A, ILM, L)",
        "Nordic buffet 13,80€: Broileria tomaatti-kermakastikkeessa - Murg Makhani (A, G, L, VS)",
        "Nordic buffet 13,80€: Basmatiriisiä (G, L, M, Veg)",
        "Nordic buffet 13,80€: Satokauden kasviksia (G, L, M, Veg)",
        "Nordic buffet 13,80€: Jogurttipannacottaa (A, G, L)",
        "Nordic buffet 13,80€: Mangokastiketta (G, L, M, Veg)",
        "Nordic buffet 13,80€: Päivän pizza",
        "Nordic buffet 13,80€: Päivän kasvispizza"
      ]
    },
    "6": {
      "tiistai": [
        "TänäänKe"
      ],
      "perjantai": [
        "Seuraava viikko>",
        "Ma 13.4.2026",
        "VIHREÄ KANACURRY & JASMIINIRIISI",
        "MAISSIPIHVIT, SAVUSTETTU PAPRIKAKERMAVIILI & PURJO-PERUNAMUUSI",
        "POSSU-NAUTAPATA & PAAHDETUT PERUNAT",
        "PERUNA-PURJOKEITTO",
        "PASSIONHEDELMÄ KAKKU",
        "Ti 14.4.2026",
        "ÄYRIÄISMARINARA RIGATONIPASTALLA & TUORETTA SITRUUNAA",
        "GOCHUJANG TOFUA & RIISI"
      ]
    },
    "8": {
      "maanantai": [
        "Päivän burgeri: Ridley",
        "Briossisämpylä, fetajuusto, pikkelöity raparperi, basilika-omenachutney, salaatti ja piparjuurimajoneesi. Ranut ja lipstikka-jogurttiaiolia. vähälaktoosinen",
        "Pihvivaihtoehdot: Mortonin porkkana-pellavapihvi Kanan rintafilee",
        "saatavana vegaanisena saatavana laktoosittomana saatavana gluteenittomana +1€",
        "Päivän salaatti: Elisabethin salaatti",
        "Peltolan Blue -sinihomejuusto, kirsikkatomaatti, salaattisekoitus, pikkelöity raparperi, basilika-omenahilloke ja piparjuurikastike. laktoositon gluteeniton"
      ],
      "tiistai": [
        "Päivän burgeri: Delaware",
        "Suosituin burgerimme! Briossisämpylä, cheddarjuusto, chili-sipulihilloke, pekoni, tomaatti, salaatti ja Kontin savupaprikamajoneesi. Ranut ja lipstikka-jogurttiaiolia. vähälaktoosinen",
        "Pihvivaihtoehdot:",
        "Naudanlihapihvi",
        "Kanan rintafilee",
        "saatavana laktoosittomana saatavana gluteenittomana +1€ saatavana vegaanisena",
        "Päivän salaatti: Saran salaatti"
      ],
      "keskiviikko": [
        "Päivän burgeri: Darby",
        "Kanan rintafilee",
        "Mortonin porkkana-pellavapihvi.",
        "Päivän salaatti: Elisabethin salaatti",
        "Peltolan Blue -sinihomejuusto, kirsikkatomaatti, salaattisekoitus, pikkelöity raparperi, basilika-omenahilloke ja piparjuurikastike. laktoositon gluteeniton",
        "Inkiväärimaustetulla kanan fileelläMortonin porkkana-pellavapullilla"
      ],
      "torstai": [
        "Päivän burgeri: Little John",
        "Mortonin klassikkoburgeri! Briossisämpylä, Peltolan Blue -sinihomejuusto, punasipulihilloke, Myrttisen maustekurkku, tomaatti, salaatti, chipotlemajoneesi. vähälaktoosinen",
        "Lisäksi ranut ja lipstikka-jogurttiaiolia.",
        "Pihvivaihtoehdot: Naudanlihapihvi Mortonin porkkana-pellavapihvi",
        "saatavana vegaanisena saatavana laktoosittomana saatavana gluteenittomana +1€",
        "Päivän salaatti: Saran salaatti"
      ]
    },
    "9": {
      "maanantai": [
        "Grillattua kanaa, paprikakastiketta, kauden kasviksia ja paahdettua perunaa L,G 15,50€",
        "Risotto Verde, bufala-mozzarellaa ja pestoa VL,G 15,50€",
        "Halloumisalaatti ja mangosalsaa L,G 15,50€",
        "Surf & Turf härän sisäfileellä ja sahramimarinoiduilla jättikatkaravunpyrstöillä, punaviinikastike, marinoitua punakaalia, chimichurri-perunaa ja aioli L,G 23€",
        "Beef burger, ranskalaiset ja dippi L,(G) 18,50€",
        "Fish’n’ chips, tartarkastike ja muhennettua hernettä L 19,50€"
      ],
      "tiistai": [
        "Grillattu lohta, avokadopyree, aurajuustokastike, mangosalsaa ja paahdettua perunaa L,G 15,50€",
        "Risotto Verde, bufala-mozzarellaa ja pestoa VL,G 15,50€",
        "Halloumisalaatti ja mangosalsaa L,G 15,50€",
        "Surf & Turf härän sisäfileellä ja sahramimarinoiduilla jättikatkaravunpyrstöillä, punaviinikastike, marinoitua punakaalia, chimichurri-perunaa ja aioli L,G 23€",
        "Beef burger, ranskalaiset ja dippi L,(G) 18,50€",
        "Fish’n’ chips, tartarkastike ja muhennettua hernettä L 19,50€"
      ],
      "keskiviikko": [
        "Gochujang-härkäpasta ja parmesania L15,50€",
        "Paahdettua kukkakaalia, yrtti-voipapupyree, kvinoaa, chimichurria, kasviksia ja seesamijogurtti V,(G) 15,50€",
        "Halloumisalaatti ja mangosalsaa L,G 15,50€",
        "Surf & Turf härän sisäfileellä ja sahramimarinoiduilla jättikatkaravunpyrstöillä, punaviinikastike, marinoitua punakaalia, chimichurri-perunaa ja aioli L,G 23€",
        "Beef burger, ranskalaiset ja dippi L,(G) 18,50€",
        "Fish’n’ chips, tartarkastike ja muhennettua hernettä L 19,50€"
      ],
      "torstai": [
        "Riistapullia, dijonkastike, perunapyree, pikkelöityä kurkkua ja punaherukkaa L,G 15,50€,G",
        "Paahdettua kukkakaalia, yrtti-voipapupyree, kvinoaa, chimichurria, kasviksia ja seesamijogurtti V,(G) 15,50€",
        "Halloumisalaatti ja mangosalsaa L,G 15,50€",
        "Surf & Turf härän sisäfileellä ja sahramimarinoiduilla jättikatkaravunpyrstöillä, punaviinikastike, marinoitua punakaalia, chimichurri-perunaa ja aioli L,G 23€",
        "Beef burger, ranskalaiset ja dippi L,(G) 18,50€",
        "Fish’n’ chips, tartarkastike ja muhennettua hernettä L 19,50€"
      ],
      "perjantai": [
        "Härän sisäfilee, punaviinikastike, marinoitua punakaalia, vihreitä papuja, lohkoperunaa ja aioli L,G 15,50€,G",
        "Paahdettua kukkakaalia, yrtti-voipapupyree, kvinoaa, chimichurria, kasviksia ja seesamijogurtti V,(G) 15,50€",
        "Halloumisalaatti ja mangosalsaa L,G 15,50€",
        "Surf & Turf härän sisäfileellä ja sahramimarinoiduilla jättikatkaravunpyrstöillä, punaviinikastike, marinoitua punakaalia, chimichurri-perunaa ja aioli L,G 23€",
        "Beef burger, ranskalaiset ja dippi L,(G) 18,50€",
        "Fish’n’ chips, tartarkastike ja muhennettua hernettä L 19,50€",
        "”Ehdottomasti tulen uudelleen. Upea ”kanavaravintola”, erinomainen ruoka, ystävällinen palvelu.”",
        "”Kerran kesässä käytävä luottokohde ja aina yhtä toimiva! Ruoka on maukasta ja tulee nopeasti, palvelu on todella mukavaa ja kiireettömän tuntuista! Vahva suositus 👌”",
        "”Kiitos hyvästä ja ystävällisestä palvelusta. Ruoka oli maistuvaa ja annoskoot sopivat (teinikin sai vatsansa täyteen). Meille jäi vierailustamme hyvä mieli!”",
        "”Ravintolassa oli kiva tunnelma ja tarjoilijat olivat todella miellyttäviä ja palvelualttiita. Erinomainen hinta-laatusuhde. Tulen varmasti uudelleen tähän ravintolaan.”"
      ]
    },
    "10": {
      "maanantai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Tofua vihreässä currykastikkeessa - Luomutofu Green Curry (A, G, ILM, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Basmatia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Vuohenjuustolla täytettyä broileria ja paprikahilloa (A, G, VL)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettuja chorizopyöryköitä sekä fenkoli-tomaattikastikeessa (G, L, M, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettua rosmariini-valkosipuliperunaa (G, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Maitosuklaa -Rocky Road (A)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Kikherne-purjososekeittoa (A, G, ILM, L, M, Veg, VS)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Paahdettuja kurpitsansiemeniä (G, L, M, Veg)"
      ],
      "tiistai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Mexican kasvispihvejä (G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Lime-aiolia (A, G, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Porotäytettä (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettua perunaa (G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettua kirjolohta (A, G, ILM, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Ruohosipuli-kermaviilikastiketta (A, G, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Keitettyjä perunoita (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Omenapiirakkaa (A, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Vaniljakastiketta (A, G, L)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Punajuurisosekeittoa (A, G, ILM, L, M, Veg)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Rucolaöljyä (G, L, M, Veg, VS)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Paahdettuja pinjansiemeniä (G, L, M, Veg)"
      ],
      "keskiviikko": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Seitan-kookoscurrya ja korianteria (A, ILM, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Kotimaista kauraa (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettua broileria (G, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Minttugremolataa (A, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pehmeäksi haudutettua naudanrintaa (G, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Bearnaisea (A, G)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pinaatti-perunasosetta (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Food & Co Jäätelöbuffet (A, G, L)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Kikhernekeittoa (A, G, ILM, L, M, Veg, VS)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Raejuustoa (A, G, L)"
      ],
      "torstai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Meidän keittiön porkkana-lehtikaalipihvejä (A, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Sitruuna-kauragurttia (A, G, ILM, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Butter Chicken ja kasviksia (A, G, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Jasminriisiä (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Mureaa possua (G, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pico De Gallo -salsaa (G, ILM, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettuja perunoita (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Vohveleita (A)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Kermavaahtoa (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Mansikkahilloa (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Karamellisoitua sipulia (G, L, M, Veg)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Perinteistä hernekeittoa (A, G, ILM, L, M)"
      ],
      "perjantai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Vege-vuustohampurilainen (A, L, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Beef Burger (A, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Ranskalaisia perunoita (G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Seifileetä ja sitruunapestoa (A, G, ILM, L, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Tilliperunoita (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Limepannacottaa (A, G, L)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Palsternakkasosekeittoa (A, ILM, L, M, Veg)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Paahdettuja kurpitsansiemeniä (G, L, M, Veg)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Persiljaöljyä (G, L, M, Veg)"
      ]
    },
    "11": {
      "maanantai": [
        "Lounasbuffet 13,20 €:",
        "Kanakormaa",
        "Rapeita chilikalafileitä",
        "Panang curry – thaimaalaista currya luomutofulla",
        "Marokkolaista kurpitsakeittoa",
        "Basmatiriisiä",
        "Yrttiperunaa",
        "Timjamilla maustettua porkkanaa",
        "Chili-limejugurttia",
        "Sitruunarahkaa",
        "Kahvi"
      ],
      "tiistai": [
        "Lounasbuffet 13,20 €:",
        "Misokastikkeella glaseerattua possunniskaa",
        "Lyonin kanaa",
        "Itte tehtyjä juustoisia kesäkurpitsamurekepihvejä",
        "Punajuuri-vuohenjuustokeittoa",
        "Maalaislohkoperunoita",
        "Riisiä",
        "Kukkakaalia",
        "Ruohosipuli-kermaviilikastiketta",
        "Mustikkakukkoa",
        "Kahvi"
      ],
      "keskiviikko": [
        "Lounasbuffet 13,20 €:",
        "Lindströminpihvejä",
        "Tikka masala -maustettua kalkkunaa",
        "Tofu ratatouille – kasvispaistosta",
        "Paahdettua juuressosekeittoa",
        "Valkosipulikermaperunoita",
        "Currymaustettua riisiä",
        "Sinappisia uuniporkkanoita",
        "Kapris-ranskankermakastiketta",
        "Passionpannacotta #",
        "Kahvi"
      ],
      "torstai": [
        "Lounasbuffet 13,20 €:",
        "Kukkoa viinissä",
        "Katkarapuskagentäytettä",
        "Peshawarin tofucurry – currypataa pakistanilaisittain",
        "Kasvishernekeittoa",
        "Uuniperunoita",
        "Mausteista riisiä",
        "Rosmariinipunajuuria",
        "Antellin pannukakkua",
        "Kermavaahtoa",
        "Marjahilloa",
        "Kahvi"
      ],
      "perjantai": [
        "Lounasbuffet 13,20 €:",
        "Porsaan grillipihvejä",
        "Bulgogi chicken – kanaa korealaisittain",
        "Napolilaista lasagnea",
        "Metsäsienikeittoa",
        "Maustepaahdettuja perunoita",
        "Yrttistä kvinoaa ja riisiä",
        "Paahdettua palsternakkaa",
        "Itte tehtyä maustevoita",
        "Jäätelöbaari",
        "Kahvi"
      ]
    },
    "12": {
      "maanantai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Purjo-perunasosekeittoa (A, G, ILM, L, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Punajuuri falafelpihvejä (G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Porkkana-kikhernehummusta (A, G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pasta carbonaraa (A, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pastajuustoa (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Rapeaa broileria (A, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): BBQ -majoneesia (A, G, L, M, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettua perunaa (G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pähkinäinen omenapiirakka (A, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Vaniljakermavaahtoa (A, G, L)"
      ],
      "tiistai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Linssisosekeittoa (A, G, ILM, L, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Mö chavre -kasvispyöryköitä ja paprika-oliivipaistosta (A, ILM, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Chilipaahdettua kirjolohta (A, G, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Chilisalsakermaviiliä (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paprikalla maustettuja lammasmurekepihvejä (A, L, M, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Mintulla maustettua tzatsikia (A, G, ILM, L, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettua perunaa (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Suklaaunelma piiras (A, G, VL)"
      ],
      "keskiviikko": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Myskikurpitsasosekeittoa (A, G, ILM, L, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Meidän keittiön pähkinäisiä kukkakaali-tofupihvejä Sis.Pähkinää, Veg (A, ILM, L, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Vege-Aiolia (A, G, L, M, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Kotimaista kauraa (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Tonnikala-lehtipinaattilasagnettea (A, L, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Rapeaa kanaa Gochujang (A, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Parmesanmajoneesia (A, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettuja mausteperunoita (G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Suklaamoussea, kinuskia ja pähkinää (A, G, L)"
      ],
      "torstai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Kasvishernekeittoa (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Hienonnettua sipulia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Maccheronipastaa ja fetaa (A, VL, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pastajuustoa (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettua broileria (G, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Tomaatti-vuohenjuustokastiketta (A, G, ILM, L, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Yrttipaahdettua perunaa (G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pappilan hätävaraa (A, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Ruskeaa kastiketta (A, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Lindströminpihvejä (A, L, M)"
      ],
      "perjantai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Kukkakaalisosekeittoa (A, G, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Tofua, kasviksia ja pähkinää (A, G, ILM, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Riisiä (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Porsaan grillipihvi (G, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pippurista tuorejuustokastiketta (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Kermaperunoita (A, G, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Food & Co Jäätelöbuffet (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Broileria inkivääri-chilikastikkeessa (A, G, L, M)"
      ]
    },
    "13": {
      "maanantai": [
        "1.Veg kofta chilli (G,L)* Vegaani / Vegan",
        "Kasvispyöryköita mausteisessa soija-chillikastikkeessa.",
        "2.Shahi Paneer (G)",
        "Leipäjuustopaloja tomaatti-voi-kermakastikkeessa.",
        "3.Chicken Tikka Masala (G)**",
        "Tandoori-uunissa grillattua kanaa mausteisessa masalakastikkeessa.",
        "4.lamb Vindalo(G,L)*"
      ],
      "tiistai": [
        "1.Paneer Masala (G)*",
        "Paneer-juustoa tomaatti-sipuli-valkosipuli-masalakastikeessa.",
        "2.Saag Tofu (G)*",
        "3.Butter Chicken (G)",
        "Tandoori-uunissa grillattua kanaa tomaatti-voi-kermakastikkeessa.",
        "4.Lamb Kofta (G,L)*",
        "Lampaan jauhelihapyöryköitä hieman mausteisessa tomaatti-valkosipuli-inkivääri-sipuli-currykastikkeessa."
      ],
      "keskiviikko": [
        "1.Tofu Chili (G,L)** Vegaani / Vegan",
        "Tofua, paprikaa ja sipulia chili-soijakastikkeessa.",
        "2.Malai Kofta (G)",
        "Paneerjuusto-kasvispyöryköitä tomaatti-voi-kermakastikkeessa.",
        "3.Kadai Chicken (G,L)*",
        "4.Lamb Saag (G,L)*",
        "Haudutettua lammasta pinaatti-tomaatti-inkivääri-valkosipuli-currykastikkeessa."
      ],
      "torstai": [
        "1.Tofu Masala (G,L)* Vegaani / Vegan",
        "Tofua masala-kastikkeessa..",
        "2.Paneer Makhani (G)",
        "Paneer-juustoa tomaatti-voi-kermakastikkeessa.",
        "3.Garlic chicken(G,L)*",
        "4.Chicken Lamb Masala (G)*",
        "Yrtti-jogurttimarinoitua ja tandoori-uunissa grillattua kanaa ja lampaanjauhelihaa mausteisessa tomaatti-sipuli-inkiväärikastikkeessa."
      ],
      "perjantai": [
        "1.Aloo Gobi Tofu (G,L)* Vegaani / Vegan",
        "Kukkakaalia,tofu ja perunaa tomaatti-masalakastikkeesa",
        "2.Saag Paneer (G)",
        "Paneer-juustoa pinaatti-curry-kermakastikkeessa.",
        "3.Butter Chicken (G)",
        "Tandoori-uunissa grillattua kanaa tomaatti-voi-kermakastikkeessa",
        "4.Lamb Curry (G,L)*"
      ]
    },
    "14": {
      "keskiviikko": [
        "na 10. joulukuuta klo 11:00–14:00. Hinta: 19,90 €Seuraavissa ravintoloissa:Ravintola Huudi",
        "Ravintola Fågeli",
        "Ravintola Oikeus",
        "Ravintola Verkstad",
        "Cafeteria Vuokki",
        "Ravintola Käpis",
        "Ravintola Bron",
        "Sekä Ravintola Oasis (opening soon)Mechelininkatu 1a, 00180 Helsinki+358 0400510970 | oasis@nordrest.fi",
        "Special Foods Division",
        "Nordrest Special Foods Division (SFD) delivers long-shelf-life food solutions for defence, emergency preparedness, humanitarian operations, and institutional customers."
      ]
    },
    "15": {
      "maanantai": [
        "Lounasbuffet 13,90 €:",
        "Lihapullia kermaisessa pippurikastikkeessa",
        "Melanzane – munakoiso-tomaattivuokaa",
        "Perunamuusia",
        "Puolukkasurvosta",
        "Luomukahvi"
      ],
      "tiistai": [
        "Lounasbuffet 13,90 €:",
        "Seesamipaahdettua kanaa",
        "Itte tehtyjä juurespihvejä",
        "Jasmiiniriisiä",
        "Limeaiolia",
        "Luomukahvi"
      ],
      "keskiviikko": [
        "Lounasbuffet 13,90 €:",
        "Kevyesti savustettua kirjolohta",
        "Pinaattiohukaisia",
        "Tilliperunoita",
        "Tartarkastiketta",
        "Polukkahilloa",
        "Luomukahvi"
      ],
      "torstai": [
        "Lounasbuffet 13,90 €:",
        "Metsästäjänleike",
        "Kesäkurpitsa-halloumipihvejä",
        "Kermaperunoita",
        "Metsäsienikastiketta",
        "Tzazikia",
        "Luomukahvi"
      ],
      "perjantai": [
        "Lounasbuffet 13,90 €:",
        "Kermaista kirjolohikeittoa",
        "Tomaatti-Mozzarellapiirakka #",
        "Omena-kanelipiirakkaa",
        "Vaniljakastiketta",
        "Luomukahvi"
      ]
    },
    "16": {
      "maanantai": [
        "Lemongrass Stir-Fried ChickenL",
        "Mandarin Chicken L,G",
        "Crispy Fried Pangasius in Sweet and Sour Sauce (wheat and egg contained) L",
        "Vietnamese Vegan Curry L,G,V",
        "Non-fried Tofu with Sweet and Sour sauce Singapore Style. L,V,G"
      ],
      "tiistai": [
        "Stir-fried veggies & Tofu in Teriyaki sauce. L",
        "Meatballs in tamarind sauce. L,G",
        "Roasted Eggplant (V). L,G,V",
        "Crispy-fried chicken balls. L",
        "Stir-fried lemongrass chicken. L,G",
        "Vegan mixed noodle salad with soy sauce dressing (Contains Peanuts). L,V"
      ],
      "keskiviikko": [
        "Orange Chicken L",
        "Lemongrass Stir-fried Pork L,G",
        "Fried Pangasius in Homemade Sweet and Sour Sauce L",
        "Oven-roasted Eggplants with Tofu, and Salty Radish in Homemade Sweet Soy Sauce L,V",
        "Stir-fried Rice Noodles with Vietnamese Vegan Ham L,V",
        "Non-fried Tofu with Sweet and Sour sauce L,G,V"
      ],
      "torstai": [
        "Braised Chicken with Ginger L,G",
        "Fried Pangasius in sweet Tomato sauce L",
        "Fried Chicken with Red Pepper in Sweet and Sour Sauce L",
        "Wok-fried Tofu and Vegetables in homemade Teriyaki Sauce L,V",
        "Vietnamese Vegan Curry L,V,G",
        "Stir-fried Veggies and Tofu in Tomyum sauce L,G,V"
      ],
      "perjantai": [
        "Ragu Chicken L",
        "Crispy Fried Pangasius in Sweet and Sour Sauce (wheat and egg contained) L",
        "Kung Pao Chicken L",
        "Stir-fried Veggies with Slices Vegan Beef in Teriyaki Sauce L,V",
        "Stir Fried Egg noodles, Vegan ( contained Egg and wheat). L,V",
        "Fried Rice with Veggies, (contained Egg) L,V",
        "function showTab(day) {",
        "// Hide all tabs"
      ]
    },
    "17": {
      "keskiviikko": [
        "Tom yam -rapukeitto (M+G+VS)",
        "Nepalilainen Butter Chicken paahdetuilla cashewpähkinöillä (L+G+VS+sis. pähkinää) basmatiriisi (VE+G)",
        "Voissa paistetut ruispaneroidut muikut (L) tilli-kermaviili (L+G) perunamuusi (L+G)",
        "Siirappi-paahdetut maalaisporkkanalohkot, rapeaa tofua ja seesaminsiemeniä (VE+G)",
        "Snickers-mousse suolapähkinä-kauragranolalla (VE+G+sis.pähkinä)"
      ],
      "torstai": [
        "Hernekeitto (M+G) pilkottua sipulia (VE+G)",
        "Mureita porsaan ulkofilenoisetteja konjakki-pippurikastikkeessa (L+G) timjamiperunat (VE+G)",
        "Chicken 65 – meillä tehdyt mausteiset friteeratut kanan paistileikkeet (M+G+VS) basmatiriisi (VE+G)",
        "MUU vege -nakkipaloja kasviksilla ja sataykastikkeella (VE+G+VS+sis.pähkinää)",
        "Factoryn letut (L) mansikkahillo (VE+G) kermavaahto (L+G) jäätelö (L+G)"
      ],
      "perjantai": [
        "Kermainen lohikeitto (L+G)",
        "Naudan kebablastuja makean tulisessa paprika-tomaatti-basilikakastikkeessa (M+G+VS)",
        "turkkilaista jogurttia (L+G) basmatiriisi (VE+G)",
        "Fish & Chips – tempura-paneroitua turskaa (L) avocado-ranch -dippi (L) rapeat ranskalaiset (VE+G)",
        "Kana-halloumipasta sitruuna–valkosipuli-kermakastikkeessa ja parmesaanimurua (L+VS)",
        "Tonnikalapizza chili-limemajoneesi -raitakastikkeella (L)",
        "Seesami-tofua ja kasviksia sweet & sour -kastikkeessa (VE+G+VS)",
        "Kakkulajitelma (L)"
      ]
    },
    "18": {
      "maanantai": [
        "A) Naudan pannupihvi, tummaa sinapinsiemenkastiketta ja Skånen perunoita (L, saatavilla G) 14.00€",
        "B) Punajuuriravioleja, vuohenjuustomoussea ja lehtikaalisalaattia (saatavilla G, saatavilla VE, sis. pähk.) 14.00€",
        "C) Mantelikala – Kevyesti hiillostettua kuhaa, valkoviinikastiketta ja hiillostettuja perunoita sekä paahdettuja mantelilastuja (L, G) 14.70€",
        "Jälki-istunto ja kahvi – Hunajakakkua (L) 2€"
      ],
      "tiistai": [
        "A) Butter chicken – Pariloitua kananpoikaa tomaattivoikastikkeessa, basmatiriisiä ja kurkkuraitaa (L, G) 14.00€",
        "B) Grillattua savutofua, ratatouillea ja paahdettuja pinjansiemeniä sekä rucolaa (M, VE, G) 14.00€",
        "C) Mantelikala – Kevyesti hiillostettua kuhaa, valkoviinikastiketta ja hiillostettuja perunoita sekä paahdettuja mantelilastuja (L, G) 14.70€",
        "Jälki-istunto ja kahvi – Hunajakakkua (L) 2€"
      ],
      "keskiviikko": [
        "A) Paahdettua kirjolohta, piparjuurismetanaa ja lohkoperunoita (L, G) 14.00€",
        "Kikherneitä ja myskikurpitsaa ’Green curry’, kookosriisiä ja pikkelöityä chiliä (M, VE, G) 14.00€",
        "C) Tilliliha – Pitkään haudutettua härkää, porkkanapyreetä ja paistettuja kevätkasviksia sekä tillipestoa (L, G) 14.70€",
        "Jälki-istunto ja kahvi – Mangorahkaa ja pistaasimurua (L, G) 2€"
      ],
      "torstai": [
        "A) Chorizopastaa tuoretomaattikastikkeessa ja sitruunalla sekä basilikalla marinoitua mozzarellasalaattia (L, saatavilla G) 14.00€",
        "B) Pariloitua halloumia, bataattipyttipannua ja sitruunamajoneesia (G, saatavilla VE) 14.00€",
        "C) Tilliliha – Pitkään haudutettua härkää, porkkanapyreetä ja paistettuja kevätkasviksia sekä tillipestoa (L, G) 14.70€",
        "Jälki-istunto ja kahvi – Mangorahkaa ja pistaasimurua (L, G) 2€"
      ],
      "perjantai": [
        "A) Spicy chicken – Rapeaa kanaa tulisessa siipikastikkeessa, yuzujogurttia ja riisiä sekä chili crunchia (L, G) 14.00€",
        "B) Falafel Bowl – Falafelpyöryköitä, yuzujogurttia, riisiä ja pikkelöityä punakaalia sekä chili crunchia (L, VE, G) 14.00€",
        "C) Tilliliha – Pitkään haudutettua härkää, porkkanapyreetä ja paistettuja kevätkasviksia sekä tillipestoa (L, G) 14.70€",
        "Jälki-istunto ja kahvi – Mangorahkaa ja pistaasimurua (L, G) 2€",
        "SisältöLounas",
        "Lunch Kamppi",
        "Olemme esteetön ravintola!",
        ".kb-row-layout-idblock-38_b24816-ee > .kt-row-column-wrap{align-content"
      ]
    },
    "19": {
      "maanantai": [
        "Härkäpapu tagine (V, G)",
        "Mausteinen riisi (V, G)"
      ],
      "tiistai": [
        "Nautaa punaviinikastikkeessa (M, G)",
        "Kikherne tagine (V, G)",
        "Couscous (V)"
      ],
      "keskiviikko": [
        "Kampela sitruuna-yrttikastikkeessa (M)",
        "Kurpitsa tagine (V, G)",
        "Paahdetut perunat (V, G)"
      ],
      "torstai": [
        "Kanaa sahramikastikkeessa (M, G)",
        "Mausteinen munakoisotagine (V, G)",
        "Mausteinen riisi (V, G)"
      ],
      "perjantai": [
        "Porsasta tomaattikastikkeessa (M, G)",
        "Härkäpapu tagine (V, G)",
        "Lohkoperunat (V, G)",
        "(M = Maidoton, G = Gluteeniton, V = Vegaaninen)",
        "Sandro Kortteli",
        "Kauppakeskus Kamppi 5 kerros",
        "Urho Kekkosen katu 1",
        "Evästeet ja tietosuoja",
        "Oivaraportti",
        "Meille töihin"
      ]
    },
    "20": {
      "maanantai": [
        "Insalata di Pollo 13.50 €",
        "Spaghetti Chitarra 13.50 €",
        "Penne Rosa 14.20 €",
        "Cannelloni Pistachio 14.80 €"
      ],
      "tiistai": [
        "Insalata di Pollo 13.50 €",
        "Spaghetti Chitarra 13.50 €",
        "Penne Rosa 14.20 €",
        "Cannelloni Pistachio 14.80 €"
      ],
      "keskiviikko": [
        "Insalata di Pollo 13.50 €",
        "Spaghetti Chitarra 13.50 €",
        "Penne Rosa 14.20 €",
        "Cannelloni Pistachio 14.80 €"
      ],
      "torstai": [
        "Insalata di Pollo 13.50 €",
        "Spaghetti Chitarra 13.50 €",
        "Penne Rosa 14.20 €",
        "Cannelloni Pistachio 14.80 €"
      ],
      "perjantai": [
        "Insalata di Pollo 13.50 €",
        "Spaghetti Chitarra 13.50 €",
        "Penne Rosa 14.20 €",
        "Cannelloni Pistachio 14.80 €"
      ]
    },
    "21": {
      "maanantai": [
        "Punainen siikacurry ja limeriisiä M, GPunainen kasviscurry ja limeriisiä V, GRed whitefish curry with lime rice V, GRed vegetable curry and lime rice V, G"
      ],
      "tiistai": [
        "Paahdettua N’duja kananpaistia sekä ratatouille kasviksia L, GTofukasvis paistosta V, GRoasted chicken with N’duja and ratatouille vegetables L, GTofu vegetables stir-fry V, G"
      ],
      "torstai": [
        "Nakkikastike ja yrttiperunaa L, GPalak paneer sekä yrttiperunaa V, GSausage stew with herd potatoes L, GPalak paneer with herb potatoes V, G"
      ],
      "perjantai": [
        "Tervetuloa lounaalle Tislaamolle!Welcome to lunch at Tislaamo!",
        "What’s Happening at Henry’s Distillery:",
        "-Our upcoming events are published here.More upcoming events and campaigns you can find in our Music Bar’s side!",
        "@henryskasarmi | @kulttuurikasarmievents",
        "!function(){\"use strict\";if(\"query",
        "Selector\"in document&&\"add",
        "Listener\"in window){var e=document.body;e.add",
        "Listener(\"pointerdown\",(function(){e.class"
      ]
    },
    "22": {
      "maanantai": [
        "Manun lounasbuffet",
        "Kirjolohipyörykät L ja tartarkastike L,G",
        "Papu-kasviscurry VE,G",
        "Pinaattimuusia L,G",
        "Paahdettua kukka -ja parsakaalia VE,G",
        "Mausteinen myskikurpitsakeitto VE,G",
        "Manun Lounasbuffet",
        "Kermaista viherpippuripossua L,G",
        "Kasvispihvejä, aiolia VE,G",
        "Paahdettuja juureksia ja perunoita VE,G",
        "Tomaattikeitto VE,G",
        "Manun Lounasbuffet",
        "Pannupihvi \\u0026 tummaa timjamikastiketta L,G",
        "Falafelpyörykkä, tartarkastike VE,G",
        "Keitettujä perunoita VE,G",
        "Kauden kasviksia VE, G",
        "Paahdettu kukkakaalisosekeitto L,G",
        "Manun Lounasbuffet",
        "Paahdettua broileria \\u0026 kookos-savupaprikakastiketta M,G",
        "Nyhtökasviswokkia VE,G",
        "Basmatiriisiä VE,G",
        "Hernekeittoa M,G",
        "Pannukakkua L, mansikkahilloa VE,G ja kermavaahtoa L,G",
        "(pyydettäessä glut.ohukainen G,L)"
      ],
      "tiistai": [
        "Manun Lounasbuffet",
        "Kermaista viherpippuripossua L,G",
        "Kasvispihvejä, aiolia VE,G",
        "Paahdettuja juureksia ja perunoita VE,G",
        "Tomaattikeitto VE,G",
        "Manun Lounasbuffet",
        "Pannupihvi \\u0026 tummaa timjamikastiketta L,G",
        "Falafelpyörykkä, tartarkastike VE,G",
        "Keitettujä perunoita VE,G",
        "Kauden kasviksia VE, G",
        "Paahdettu kukkakaalisosekeitto L,G",
        "Manun Lounasbuffet",
        "Paahdettua broileria \\u0026 kookos-savupaprikakastiketta M,G",
        "Nyhtökasviswokkia VE,G",
        "Basmatiriisiä VE,G",
        "Hernekeittoa M,G",
        "Pannukakkua L, mansikkahilloa VE,G ja kermavaahtoa L,G",
        "(pyydettäessä glut.ohukainen G,L)",
        "Manun Lounasbuffet",
        "Uunilohi L,G ja tillikermaviili VE,G",
        "Perunamuussi L,G",
        "Paahdetut juurekset VE,G",
        "Maa-artisokkakeittoa ja nyhtökauraa VE,G"
      ],
      "keskiviikko": [
        "Manun Lounasbuffet",
        "Pannupihvi \\u0026 tummaa timjamikastiketta L,G",
        "Falafelpyörykkä, tartarkastike VE,G",
        "Keitettujä perunoita VE,G",
        "Kauden kasviksia VE, G",
        "Paahdettu kukkakaalisosekeitto L,G",
        "Manun Lounasbuffet",
        "Paahdettua broileria \\u0026 kookos-savupaprikakastiketta M,G",
        "Nyhtökasviswokkia VE,G",
        "Basmatiriisiä VE,G",
        "Hernekeittoa M,G",
        "Pannukakkua L, mansikkahilloa VE,G ja kermavaahtoa L,G",
        "(pyydettäessä glut.ohukainen G,L)",
        "Manun Lounasbuffet",
        "Uunilohi L,G ja tillikermaviili VE,G",
        "Perunamuussi L,G",
        "Paahdetut juurekset VE,G",
        "Maa-artisokkakeittoa ja nyhtökauraa VE,G",
        "Manun Lounasbuffet",
        "Porsaankassleria, tummaa BBQ-kastiketta M,G",
        "Kasvis-kvinoapihvit ja tartarkastiketta VE,G",
        "Paahdettu peruna VE,G",
        "Paahdettua kukka -ja parsakaalia VE,G",
        "Kermaista sellerikeittoa L,G"
      ],
      "torstai": [
        "Manun Lounasbuffet",
        "Paahdettua broileria \\u0026 kookos-savupaprikakastiketta M,G",
        "Nyhtökasviswokkia VE,G",
        "Basmatiriisiä VE,G",
        "Hernekeittoa M,G",
        "Pannukakkua L, mansikkahilloa VE,G ja kermavaahtoa L,G",
        "(pyydettäessä glut.ohukainen G,L)",
        "Manun Lounasbuffet",
        "Uunilohi L,G ja tillikermaviili VE,G",
        "Perunamuussi L,G",
        "Paahdetut juurekset VE,G",
        "Maa-artisokkakeittoa ja nyhtökauraa VE,G",
        "Manun Lounasbuffet",
        "Porsaankassleria, tummaa BBQ-kastiketta M,G",
        "Kasvis-kvinoapihvit ja tartarkastiketta VE,G",
        "Paahdettu peruna VE,G",
        "Paahdettua kukka -ja parsakaalia VE,G",
        "Kermaista sellerikeittoa L,G",
        "Manun lounasbuffet",
        "Broilerinleikettä",
        "punaisesssa currykastikeessa M,G",
        "Vönerwokkia VE",
        "Vihannesriisiä VE,G",
        "Kermainen kalakeitto L,G"
      ],
      "perjantai": [
        "Manun Lounasbuffet",
        "Uunilohi L,G ja tillikermaviili VE,G",
        "Perunamuussi L,G",
        "Paahdetut juurekset VE,G",
        "Maa-artisokkakeittoa ja nyhtökauraa VE,G",
        "Manun Lounasbuffet",
        "Porsaankassleria, tummaa BBQ-kastiketta M,G",
        "Kasvis-kvinoapihvit ja tartarkastiketta VE,G",
        "Paahdettu peruna VE,G",
        "Paahdettua kukka -ja parsakaalia VE,G",
        "Kermaista sellerikeittoa L,G",
        "Manun lounasbuffet",
        "Broilerinleikettä",
        "punaisesssa currykastikeessa M,G",
        "Vönerwokkia VE",
        "Vihannesriisiä VE,G",
        "Kermainen kalakeitto L,G",
        "Manun lounasbuffet",
        "Chorizopyörykkä, savupaprikakastiketta L,G",
        "Vönerwokkia VE",
        "Basmatiriisi VE,G",
        "Bataattikeitto VE,G",
        "Manun lounasbuffet",
        "Lindströminpihvit ja sipulikastike L,G",
        "Metsäsienikääryle ja puolukkasurvos VE,G",
        "Palsternakkamuusi L,G",
        "Pinaattikeitto ja kananmunaa L,G"
      ]
    },
    "23": {
      "maanantai": [
        "LOUNASBUFFET",
        "Kasvislasagne VE, g",
        "Lasagne l"
      ],
      "tiistai": [
        "LOUNASBUFFET",
        "Chipotle–falafelit ja paahdetut juurekset VE, g",
        "Uuni–lohi ja paahdetut juurekset l g"
      ],
      "keskiviikko": [
        "LOUNASBUFFET",
        "Metsäsieni–kääryleet, perunamuusi ja puolukkasurvos VE, g",
        "Kaalikääryleet, perunamuusi ja puolukkasurvos l g"
      ],
      "torstai": [
        "LOUNASBUFFET",
        "Marry me –no chicken ja riisi VE, g",
        "Marry me –chicken ja riisi l g"
      ],
      "perjantai": [
        "LOUNASBUFFET",
        "Tortilla–perjantai:",
        "• Chipotle no–chicken VE, g",
        "• Chipotle chicken l g"
      ]
    },
    "24": {
      "maanantai": [
        "Päivän keitto: Kermainen lohikeitto (L, G)",
        "Karjalanpaisti (M, G)",
        "Kanapyörykät currykastikkeessa (L, G) Puolukkahillo (M, G)",
        "Chili sin Carne (Ve, G)",
        "Perunamuusi (L, G)",
        "Riisi (Ve, G)"
      ],
      "tiistai": [
        "Päivän keitto: Mausteinen tomaattikeitto (Ve, G)",
        "Lasagne (L)",
        "Seitiä voikastikkeessa (L, G)",
        "Uunijuurekset (M, G)",
        "Yrttiriisi (Ve, G)"
      ],
      "keskiviikko": [
        "Päivän keitto: Pinaattikeitto (L, G)",
        "Kermainen pyttipannu (L, G)",
        "Silakkapihvit (L), tilli-kermaviilikastike (L, G)",
        "Vegaaninen leike, vegaaninen majoneesi (Ve)",
        "Perunamuusi (L, G)",
        "Riisi (Ve, G)"
      ],
      "torstai": [
        "Päivän keitto: Hernekeitto (M, G), pannukakkua (L)",
        "Chili con Carne (M, G)",
        "Lohipyörykät hollandaisekastikkeessa (L, G)",
        "Härkäpapupata (Ve, G)",
        "Kermaperunat (L, G)",
        "Riisi (Ve, G)"
      ],
      "perjantai": [
        "Päivän keitto: Kermainen riistakeitto (L, G)",
        "Ylikypsää kassleria punaviinikastikkeessa (L, G)",
        "Paneroitu kampelafilee (L), sitruuna-aioli (L, G)",
        "Tofu kookoscurry (Ve, G)",
        "Lohkoperunat (L, G)",
        "Riisi (Ve, G)",
        "Viikon leike 14,90 €:",
        "JOHN SCOTT’S BURGER 13,90 €",
        "120 g naudanlihapihvi, cheddarjuusto, 3 dippiä",
        "Fish & Chips 14,90 (L) €"
      ]
    },
    "25": {
      "maanantai": [
        "Lounasbuffet 13,70 €:",
        "Kebabstroganoffia",
        "Tom yam -keittoa katkaravuilla",
        "Yrttistä kvinoaa ja riisiä",
        "Valkosipulipapuja",
        "Mustaherukka-banaanismoothieta",
        "Kahviannos , maito ja sokeri"
      ],
      "tiistai": [
        "Lounasbuffet 13,70 €:",
        "Butter chicken – intialaista kanakastiketta",
        "Salvialla maustettua juustokeittoa",
        "Pinaattiriisiä",
        "Hunajaisia rakuunaporkkanoita",
        "Marjapiirakkaa",
        "Kahviannos , maito ja sokeri"
      ],
      "keskiviikko": [
        "Lounasbuffet 13,70 €:",
        "Antellin kanalasagnea",
        "Katkarapu-kalakeittoa",
        "Kookos-jogurtti mansikalla",
        "Kahviannos , maito ja sokeri"
      ],
      "torstai": [
        "Lounasbuffet 13,70 €:",
        "Meksikon pikajunaa",
        "Punaista curry-kalkkunakeittoa",
        "Perunamuusia",
        "Paahdettua uuniporkkanaa ja lanttua",
        "Uuniomenarahkaa",
        "Kahviannos, maito ja sokeri"
      ],
      "perjantai": [
        "Lounasbuffet 13,70 €:",
        "Lohi-katkarapucurrya",
        "Herkkusienikeittoa",
        "Basmatiriisiä",
        "Marjahilloa",
        "Kermavaahtoa",
        "Vohveleita",
        "Kahviannos maito ja sokeri"
      ]
    },
    "26": {
      "maanantai": [
        "Kana Cobb -salaatti (L, G)",
        "Kermainen naudanliharagù ja perunagnoccheja (L)",
        "Kurpitsarisottoa ja paahdettua vuohenjuustoa (L, G)",
        "No-chicken taco (Ve)",
        "Ceviche-lohi taco (L)"
      ],
      "tiistai": [
        "Kana Cobb -salaatti (L, G)",
        "Kermainen naudanliharagù ja perunagnoccheja (L)",
        "Kurpitsarisottoa ja paahdettua vuohenjuustoa (L, G)",
        "No-chicken taco (Ve)",
        "Ceviche-lohi taco (L)"
      ],
      "keskiviikko": [
        "Kana Cobb -salaatti (L, G)",
        "Kermainen naudanliharagù ja perunagnoccheja (L)",
        "Kurpitsarisottoa ja paahdettua vuohenjuustoa (L, G)",
        "No-chicken taco (Ve)",
        "Ceviche-lohi taco (L)"
      ],
      "torstai": [
        "Kana Cobb -salaatti (L, G)",
        "Kermainen naudanliharagù ja perunagnoccheja (L)",
        "Kurpitsarisottoa ja paahdettua vuohenjuustoa (L, G)",
        "No-chicken taco (Ve)",
        "Ceviche-lohi taco (L)"
      ],
      "perjantai": [
        "Kana Cobb -salaatti (L, G)",
        "Kermainen naudanliharagù ja perunagnoccheja (L)",
        "Kurpitsarisottoa ja paahdettua vuohenjuustoa (L, G)",
        "No-chicken taco (Ve)",
        "Ceviche-lohi taco (L)"
      ]
    },
    "27": {
      "maanantai": [
        "Buffetlounas",
        "Lihapullapasta L",
        "Uunifeta-tomaattipasta L",
        "Mausteinen porkkanakeitto VE, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Paistettua kampelaa, perunamuusia ja tilli-kermaviilikastike L",
        "Kasviskääryleitä ja puolukkaa VE, G",
        "Sipulikeitto G, VE",
        "Kahvi tai tee",
        "Buffetlounas",
        "Lindströminpihvit ja kapriskermakastiketta L",
        "Juures-voipapupyörykät ja yrttikastike VE, M",
        "Paahdettuja perunoita G, VE",
        "Kana-currykeitto L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Parmesaanikanaa tomaattikastikeessa L",
        "Kasvis-kikhernecurrya VE, M",
        "Vihannesriisiä G, VE",
        "Peruna-purjososekeittoa G, L",
        "Kahvi tai tee"
      ],
      "tiistai": [
        "Buffetlounas",
        "Paistettua kampelaa, perunamuusia ja tilli-kermaviilikastike L",
        "Kasviskääryleitä ja puolukkaa VE, G",
        "Sipulikeitto G, VE",
        "Kahvi tai tee",
        "Buffetlounas",
        "Lindströminpihvit ja kapriskermakastiketta L",
        "Juures-voipapupyörykät ja yrttikastike VE, M",
        "Paahdettuja perunoita G, VE",
        "Kana-currykeitto L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Parmesaanikanaa tomaattikastikeessa L",
        "Kasvis-kikhernecurrya VE, M",
        "Vihannesriisiä G, VE",
        "Peruna-purjososekeittoa G, L",
        "Kahvi tai tee",
        "Buffetlounas",
        "Uunimakkaraa ja perunamuusia G, L",
        "Vegechorizopannu G, VE",
        "Etikkapunajuurta ja suolakurkkua VE, G",
        "Kermaista lohikeittoa L, G",
        "Kahvi tai tee"
      ],
      "keskiviikko": [
        "Buffetlounas",
        "Lindströminpihvit ja kapriskermakastiketta L",
        "Juures-voipapupyörykät ja yrttikastike VE, M",
        "Paahdettuja perunoita G, VE",
        "Kana-currykeitto L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Parmesaanikanaa tomaattikastikeessa L",
        "Kasvis-kikhernecurrya VE, M",
        "Vihannesriisiä G, VE",
        "Peruna-purjososekeittoa G, L",
        "Kahvi tai tee",
        "Buffetlounas",
        "Uunimakkaraa ja perunamuusia G, L",
        "Vegechorizopannu G, VE",
        "Etikkapunajuurta ja suolakurkkua VE, G",
        "Kermaista lohikeittoa L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Lihapyöryköitä, pippurikastiketta ja perunamuusia L, G",
        "Kasvispyöryköitä ja paprikamajoneesia G, VE",
        "Tomaatti-vuohenjuustokeitto L, G",
        "Kahvi tai tee"
      ],
      "torstai": [
        "Buffetlounas",
        "Parmesaanikanaa tomaattikastikeessa L",
        "Kasvis-kikhernecurrya VE, M",
        "Vihannesriisiä G, VE",
        "Peruna-purjososekeittoa G, L",
        "Kahvi tai tee",
        "Buffetlounas",
        "Uunimakkaraa ja perunamuusia G, L",
        "Vegechorizopannu G, VE",
        "Etikkapunajuurta ja suolakurkkua VE, G",
        "Kermaista lohikeittoa L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Lihapyöryköitä, pippurikastiketta ja perunamuusia L, G",
        "Kasvispyöryköitä ja paprikamajoneesia G, VE",
        "Tomaatti-vuohenjuustokeitto L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Kalamurekepihvit, tartarkastiketta L",
        "Linssi-kasvismuhennosta G, VE",
        "Keitettyjä perunoita G, VE",
        "Siskonmakkarakeitto M",
        "Kahvi tai tee"
      ],
      "perjantai": [
        "Buffetlounas",
        "Uunimakkaraa ja perunamuusia G, L",
        "Vegechorizopannu G, VE",
        "Etikkapunajuurta ja suolakurkkua VE, G",
        "Kermaista lohikeittoa L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Lihapyöryköitä, pippurikastiketta ja perunamuusia L, G",
        "Kasvispyöryköitä ja paprikamajoneesia G, VE",
        "Tomaatti-vuohenjuustokeitto L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Kalamurekepihvit, tartarkastiketta L",
        "Linssi-kasvismuhennosta G, VE",
        "Keitettyjä perunoita G, VE",
        "Siskonmakkarakeitto M",
        "Kahvi tai tee",
        "Buffetlounas",
        "Pannupihvit ja paistettua sipulia L",
        "Kasvispihvejä ja paistettua sipulia G, VE",
        "Paahdettuja perunoita G, VE",
        "Samettinen purjo-perunasosekeitto L, G",
        "Kahvi tai tee"
      ]
    },
    "28": {
      "keskiviikko": [
        "Kebabkastike ❤️ M G",
        "Vebabkastike ❤️ V",
        "MYÖS TAKE AWAY"
      ],
      "torstai": [
        "Kievinkana",
        "Falafelpyörykät ❤️ V G",
        "MYÖS TAKE AWAY"
      ],
      "perjantai": [
        "Kalanugetti ❤️ M G",
        "Marokko-kasvispihvi ❤️ V G",
        "MYÖS TAKE AWAY"
      ],
      "maanantai": [
        "Paneroitu kalapihvi ❤️ L G",
        "Kvinoa-kasvispihvi ❤️ V G",
        "MYÖS TAKE AWAY"
      ],
      "tiistai": [
        "Pesto-broilerilasagne L",
        "Härkislasagnette ❤️ L",
        "MYÖS TAKE AWAY"
      ]
    },
    "29": {
      "maanantai": [
        "Salaattipöytä (L)",
        "Paistettuja muikkuja,tartar-kastiketta ja tilliperunaa (L)",
        "Vebabia tomaattikastikeessa ja pilahviriisiä (M)",
        "Herkkusienikeitto (G, L)",
        "Marjasmoothie (G, M)",
        "Kahvi ja tee (G, M)"
      ],
      "tiistai": [
        "Kreikka-teema, Salaattipöytä (G, L)",
        "Kreikka-teema, pastitsio ja parmesaani (L)",
        "Kreikka-teema, Halloumi-punajuuripihvejä, riisiä ja tsatsikikastiketta (G, L)",
        "Kreikka-teema, linssikeitto (G, M)",
        "Kreikka-teema, Halvavaahto (G, L)",
        "Kahvi ja tee (G, M)"
      ],
      "keskiviikko": [
        "Kreikka-teema, Salaattipöytä (G)",
        "Kreikka-teema, Kreikkalainen naudanliha-stifado ja riisi (G, M)",
        "Kreikka-teema, Kasvismoussaka (G, M)",
        "Kreikka-teema, kanakeitto (G, M)",
        "Kreikka-teema, Ekmek kadayıfı (L)",
        "Kahvi ja tee (G, M)"
      ],
      "torstai": [
        "Salaattipöytä (G, L)",
        "Lindströminpihvit, juuresperunamuusi ja siitakesienikastike (G, L)",
        "Soijatäytteiset paprikat ja musta riisi (G, M)",
        "Kasvis-tom-yam-keitto (G, M)",
        "Kardemumma-marjapaistos ja vaniljakastike (M)",
        "Kahvi ja tee (G, M)"
      ],
      "perjantai": [
        "Salaattipöytä (G, L)",
        "Harissakebabia, riisiä ja valkosipulijogurttia (G, L)",
        "Lämmintä siitakesieni-halloumi-kasvissalaattia (G)",
        "Kookos-bataattikeitto (G, M)",
        "Banoffee (L)",
        "Kahvi ja tee (G, M)"
      ]
    },
    "30": {
      "maanantai": [
        "Pohjois-Afrikkalaista kanaa tomaattisella yrttikastikkeella (M, G)",
        "⁠Sitruuna-inkivääri Jalotofupaistos (VE, G)",
        "⁠Kermainen herkkusieni-pennepasta (VE, G)"
      ],
      "tiistai": [
        "Pasta bolognese naudanjauhelihalla (M, G)",
        "Seitan kebab kasvis-kookos-currypata (VE, G)",
        "Juustoinen Portobello-ravioli (VE, G)"
      ],
      "keskiviikko": [
        "Teriyakimausteista kanaa (M, G)",
        "Paahdettua Jalotofuwokkia (VE, G)",
        "⁠Chipotle-bataattipyöryköitä & chilimajoneesia (VE, G)"
      ],
      "torstai": [
        "Kanapyörykät lohkoperunoilla & currymajoneesilla (M, G)",
        "Pinaattinen soijarouhelaatikko (VE, G)",
        "⁠Jalotofu-kukkakaaligratiini (VE, G)"
      ],
      "perjantai": [
        "Uunilohta valkosipulivoikastikkeella & kermaperunat (G, L⁠Marokkolainen Jalotofu-couscousvuoka (VE)",
        "Punaista Jalotofupastaa (VE, G)"
      ]
    },
    "32": {
      "keskiviikko": [
        "Lohimurekepihvi, kermaviilikastike, perunamuussi (L)",
        "Italian salaatti (L)",
        "Puutarhan vihersalaatti Vegaani, G",
        "Pullavanukas & pappilan hätävara (L)"
      ],
      "torstai": [
        "Lihapullat pippurikastikketta ja paahdetut perunat (L)",
        "Marinoidut Välimeren vihannekset (L)",
        "Puutarhan víhersalaatti Vegaani, G",
        "Pullavanukas & pappilan hätävara (L) & (L, G)"
      ],
      "perjantai": [
        "Kana enchilada, creme fraiche ja paahdetut maissintähkät (L)",
        "Tomaatti jalopeno salaatti (G), Vegaani",
        "Puutarhan vihersalaatti Vegaani, G",
        "Pullavanukas & pappilan hätävara (L)"
      ]
    },
    "33": {
      "maanantai": [
        "POROPASTA: Savupororouhetta täyteläisessä kermakastikkeessa, viimeistelty parmesaanilla. Laktoositon",
        "SITRUUNA-PINAATTIKANA: Raikkaassa sitruunaliemessä haudutettua kananrintaa ja pinaattia. Riisin kanssa. Laktoositon, gluteeniton",
        "KASVISLASAGNE: Kasvissose, tomaatti- ja béchamelkastike, pastakerrokset ja mozzarella. Laktoositon, kasvis"
      ],
      "tiistai": [
        "MOUSSAKA: Kreikkalainen munakoiso-jauheliha vuoka béchamel-kastikkeella. Uunissa paistettu. Laktoositon",
        "KANA CURRYKASTIKKEESSA: Maustetussa curry-kermakastikkeessa haudutettua kananrintaa. Tarjoillaan riisin kanssa. Laktoositon, gluteeniton",
        "SIENIRISOTTO: Kermainen risotto jossa herkkusienet, Arborio-riisi ja Parmesan-juusto. Laktoositon, gluteeniton, kasvis"
      ],
      "keskiviikko": [
        "NAUDANLIHA-KASVISKEITTO: Jauhelihaa, kuutioitua perunaa, porkkanaa ja purjoa tomaattipohjaisessa liemessä. Laktoositon, gluteeniton",
        "KATKARAPUPASTA: Kermainen tomaattipasta katkaravuilla, viimeistelty Parmesan-juustolla. Laktoositon",
        "AURINKOKUIVATTUTOMAATTIPASTA: Kermainen pasta aurinkokuivatuilla tomaateilla ja sinihomejuustolla, päällä parmesaania. Laktoositon, kasvis"
      ]
    }
  }
};
