// Auto-generated by scraper – 2026-04-11T10:33:08.068Z
// Do not edit manually
const MENUS = {
  "lastUpdated": "2026-04-11T10:33:08.068Z",
  "weekNumber": 15,
  "dateRange": "6.4.–10.4.2026",
  "menus": {
    "1": {
      "maanantai": [
        "PICK IT 14 € -",
        "CHOOSE IT 14 € -",
        "LOVE IT 14,70 € - SOUP IT 12,90 € -",
        "DESSERT IT -"
      ],
      "tiistai": [
        "PICK IT 14 € - Pannulla paistettuja lihapullia kermaisessa sipulikastikkeessa ja valkosipuliperunoita (G, L)",
        "CHOOSE IT 14 € - Tuorejuustotäytteisiä pinaatti-kasvispihvejä, caponataa ja jogurttikastiketta (G, L)",
        "LOVE IT 14,70 € - Paahdettua possunkylkeä ja juureksia pippurikastikkeessa sekä perunamuusia (G, L)",
        "SOUP IT 12,90 € - Kasvis-orzokeittoa (M, Ve)",
        "DESSERT IT - Biscoff- keksimurua ja kermavaahtoa (L)"
      ],
      "keskiviikko": [
        "PICK IT 14 € - Intialaista Butter Chickenia, purjoa ja kikherneitä sekä jamiiniriisiä (G, L)",
        "CHOOSE IT 14 € - Paahdettua halloumia ja bataattia, sekä sitruuna-yrtticouscousia ja tzatzikia (L saatavilla G)",
        "LOVE IT 14,70 € - Voissa kypsennettyä kirjolohta, tillikermaa ja parsapyreetä sekä murskattuja perunoita (G, L)",
        "SOUP IT 12,90 € - Kermaista kurpitsakeittoa (G, L)",
        "DESSERT IT - Tuoremarjasmoothieta (G, L)"
      ],
      "torstai": [
        "PICK IT 14 € - Possun tonkatsua, aasialaista BBQ-kastiketta ja coleslaw’ta sekä jasmiiniriisiä (M)",
        "CHOOSE IT 14 € - Pinaatti-ricottalasagnea ja rucolasalaattia (L saatavilla G)",
        "LOVE IT 14,70 € - Voissa kypsennettyä kirjolohta, tillikermaa ja parsapyreetä sekä murskattuja perunoita (G, L)",
        "SOUP IT 12,90 € - Perinteistä hernekeittoa ja sinappia (G, M, Ve)",
        "DESSERT IT - Halon pannukakkua ja mansikkahilloa (L)"
      ],
      "perjantai": [
        "PICK IT / CHOOSE IT 14 € - Taco Perjantai!",
        "LOVE IT 14,20 € - Voissa kypsennettyä kirjolohta, tillikermaa ja parsapyreetä sekä murskattuja perunoita (G, L)",
        "SOUP IT 12,90 € - Mustapapukeittoa (G, L)",
        "DESSERT IT - Churroja, kanelisokeria ja suklaakastiketta (L)"
      ]
    },
    "2": {
      "maanantai": [
        "1 MALAI KOFTA (G) 13.50€",
        "2 GOBI SAG (L,G,V) 13,50€",
        "3 BUTTER CHICKEN (L,G) 14,00€",
        "ACHARI LAMB (L,G) 13,90€",
        "5. CHILI FISH (L,G) 13,50€",
        "6. MIX THALI 14,90€",
        "7. ΜΑΑΝΑΝΤΑIN ERIKOISET- TANDOOR KING PRAWN (G) 19,90€",
        "8. MIX SIZZLER (L,G) 18,90€"
      ],
      "tiistai": [
        "1. SHAHI PANEER (G) 13.50€",
        "2. SAG CHANA (L,G,V) 13,50€",
        "3. CHICKEN TIKKA MASALA (L,G) 13,50€",
        "4.LAMB KOFTA (L,G) 13,90€",
        "5. SHRIMP CHILI (L,G) 13,50€",
        "6. MIX THALI 14,90€",
        "7. TIISTAIN ERIKOISET - BUTTER CHICKEN (L,G) 16,90€",
        "8. LAMB SIZZLER (L,G) 16,90€"
      ],
      "keskiviikko": [
        "1. PANEER BUTTER MASALA (G) 13.50€",
        "2. ALU GOBI (L,G,V) 13,50€",
        "3. CHICKEN SIRAZ (L,G) (L,G) 13,50€",
        "4. HANDI LAMB (L.G) 13,90€",
        "5. SHRIMP SAG (L,G) 13,50€",
        "6. MIX THALI 14,90€",
        "7. KESKIVIIKON ERIKOINEN - LAMB TIKKA MASALA (G) 19,90€",
        "8. BUTTER KING PRAWN (L,G) 19,90€"
      ],
      "torstai": [
        "1. SAG PANEER (G) 13.50€",
        "2. MUSHROOM TOFU MASALA (L,G,V) 13,50€",
        "3. CHICKEN TIKKA MASALA (L,G)) 13,50€",
        "4. ACHARI KABAB (L,G) 13,90€",
        "5. NARIWAL FISH (L,G) 13,50€",
        "6. MIX THALI 14,50€",
        "7. TORSTAIN ERIKOINEN - BUTTER CHICKEN (L,G) 16,90€",
        "8. LAMB SIZZLER (L,G) 16,90€"
      ],
      "perjantai": [
        "1. KARAHI PANEER (G) 13.50€",
        "2. TOFU CHANA MASALA (L,G,V) 13,50€",
        "3. BUTTER CHICKEN (L,G) 14,00€",
        "4. PUDINA LAMB (L.G) 13,90€",
        "5. SAG FISH (L.G) 13,50€",
        "6. MIX THALI 14,90€",
        "7. PERJANTAIN ERIKOISET - MANGO CHICKEN (L,G) 15,90€",
        "8. KING PRAWN SIZZLER (L,G) 19,90€"
      ]
    },
    "3": {
      "keskiviikko": [
        "Kukkakaalikeitto (L+G)",
        "Mureaa kookoskanaa tuoreella korianterilla (M+G+VS) basmatiriisi (VE+G)",
        "Fish & Chips – tempura-turskaa (M) parmesaani-yrttiranskalaiset (L+G) tryffelimajoneesi (VE+G)",
        "Täyteläinen herkkusienirisotto parmesaanilla (VL+G)",
        "Dal Makhani – linssi-papumuhennos tofulla (VE+G+VS)",
        "Omena-kaurapaistos (VE+gluteeniton kaura) vaniljakastike (L+G)"
      ],
      "torstai": [
        "Hernekeitto palvikinkulla (M+G) hienonnettua sipulia (VE+G)",
        "Factoryn juustolihapullat tex mex -cheddar-jalapenokastikkeessa (L+G+VS) valkosipuliperunat (VE+G+VS)",
        "Rapeaa paneroitua kanaa (M) riisi (VE+G) avocado-basilikakastike (L+G)",
        "Gruusialainen kaalilaatikko Gold & Green -suikaleilla (VE+G) puolukkahillo (VE+G)",
        "Factoryn letut (L) mansikkahillo (VE+G) vaniljavaahto (L+G) jäätelö (L+G)",
        "Vegaaniset gluteenittomat letut (VE+G)"
      ],
      "perjantai": [
        "Tom yam -jättirapukeitto (M+G+VS)",
        "Kebablastut mausteisessa tomaattikastikkeessa (M+G+VS) ranskalaiset (VE+G) valkosipulijogurtti (L+G+VS)",
        "Kana-pestopasta grillatulla halloumijuustolla ja herneenversoilla (VL+G)",
        "Salami-ananas-sipulipizza (VL+VS)",
        "Itse tehdyt porkkana-papupihvit (VE+G+VS) hummus (VE+G+VS)",
        "Factoryn jälkiruokalajitelma"
      ]
    },
    "5": {
      "tiistai": [
        "Nordic buffet 13,80€: Linssisosekeittoa (A, G, ILM, L, VS)",
        "Nordic buffet 13,80€: Porkkanaohukaisia (A, ILM, L)",
        "Nordic buffet 13,80€: Raejuustoa ja yrttejä (A, G, L)",
        "Nordic buffet 13,80€: Puolukkahilloa (A, G, L, M, Veg)",
        "Nordic buffet 13,80€: Täyteläisen maustettua broileria - Broileria Tikka Masala (A, G, L, VS)",
        "Nordic buffet 13,80€: Riisiä ja kotimaista kauraa (A, G, L, M, Veg)",
        "Nordic buffet 13,80€: Lihapullia \"Lamminpään lumous\" - tummassa sinappikastikkeessa (A, G, L)",
        "Nordic buffet 13,80€: Persiljaperunoita (A, G, ILM, L, M, Veg)",
        "Nordic buffet 13,80€: Satokauden kasviksia (G, L, M, Veg)",
        "Nordic buffet 13,80€: Marjarahkaa (A, G, L)",
        "Nordic buffet 13,80€: Päivän pizza",
        "Nordic buffet 13,80€: Päivän kasvispizza"
      ],
      "keskiviikko": [
        "Nordic buffet 13,80€: Myskikurpitsasosekeittoa (A, G, ILM, L, VS)",
        "Nordic buffet 13,80€: Meidän keittiön pähkinäisiä kukkakaali-emmentalpihvejä (A, ILM, L, VS)",
        "Nordic buffet 13,80€: Tonnikala-lehtipinaattilasagnettea (A, L, VS)",
        "Nordic buffet 13,80€: Rapeaa kanaa Gochujang (A, L, M)",
        "Nordic buffet 13,80€: Parmesanmajoneesia (A, L)",
        "Nordic buffet 13,80€: Paahdettuja lohkoperunoita (G, ILM, L, M, Veg)",
        "Nordic buffet 13,80€: Satokauden kasviksia (G, L, M, Veg)",
        "Nordic buffet 13,80€: Suklaamoussea, kinuskia ja pähkinää (A, G, L)",
        "Nordic buffet 13,80€: Päivän pizza",
        "Nordic buffet 13,80€: Päivän kasvispizza"
      ],
      "torstai": [
        "Nordic buffet 13,80€: Ahvenkeittoa (A, G, ILM, L)",
        "Nordic buffet 13,80€: Korean fried tofu HotDog (A, L, M, Veg, VS)",
        "Nordic buffet 13,80€: Paahdettua broileria (G, L, M)",
        "Nordic buffet 13,80€: Yrttipaahdettua perunaa (G, ILM, L, M, Veg)",
        "Nordic buffet 13,80€: Rapeaa seitifilettä (A, ILM, L, M)",
        "Nordic buffet 13,80€: Ruohosipulijogurttia (A, G, ILM, L)",
        "Nordic buffet 13,80€: Perunamuusia (A, G, ILM, L)",
        "Nordic buffet 13,80€: Satokauden kasviksia (G, L, M, Veg)",
        "Nordic buffet 13,80€: Ohukaisia (A)",
        "Nordic buffet 13,80€: Mansikkahilloa (G, L, M, Veg)",
        "Nordic buffet 13,80€: Kermavaahtoa (A, G, L)",
        "Nordic buffet 13,80€: Päivän pizza",
        "Nordic buffet 13,80€: Päivän kasvispizza"
      ],
      "perjantai": [
        "Nordic buffet 13,80€: Kukkakaalisosekeittoa (A, G, ILM, L)",
        "Nordic buffet 13,80€: Tofua, kasviksia ja pähkinää (A, G, ILM, L, M, Veg, VS)",
        "Nordic buffet 13,80€: Teriyakimaustettua broileria (A, G, L, M, VS)",
        "Nordic buffet 13,80€: Riisiä (G, L, M, Veg)",
        "Nordic buffet 13,80€: Porsaan grillipihvi (G, L, M)",
        "Nordic buffet 13,80€: Pippurista tuorejuustokastiketta (A, G, L)",
        "Nordic buffet 13,80€: Kermaperunoita (A, G, ILM, L)",
        "Nordic buffet 13,80€: Satokauden kasviksia (G, L, M, Veg)",
        "Nordic buffet 13,80€: Food & Co Jäätelöbuffet (A, G, L)",
        "Nordic buffet 13,80€: Päivän pizza",
        "Nordic buffet 13,80€: Päivän kasvispizza"
      ]
    },
    "6": {
      "perjantai": [
        "Seuraava viikko>",
        "Ma 6.4.2026",
        "HYVÄÄ PÄÄSIÄISTÄ : )",
        "Ti 7.4.2026",
        "KOREALAISTA BULDAK KANAA MUNANUUDELEILLA",
        "TOFUA HARISSAKASTIKKEESSA SEKÄ CONFIT MINIPORKKANOITA",
        "PÄIVÄN BUFFET",
        "KERMAINEN LATVA-ARTISOKKAKEITTO",
        "PORKKANAKAKKUA",
        "Ke 8.4.2026"
      ]
    },
    "8": {
      "maanantai": [
        "Päivän burgeri: Ridley",
        "Briossisämpylä, fetajuusto, pikkelöity raparperi, basilika-omenachutney, salaatti ja piparjuurimajoneesi. Ranut ja lipstikka-jogurttiaiolia. vähälaktoosinen",
        "Pihvivaihtoehdot: Mortonin porkkana-pellavapihvi Kanan rintafilee",
        "saatavana vegaanisena saatavana laktoosittomana saatavana gluteenittomana +1€",
        "Päivän salaatti: Lydian salaatti",
        "Uusi resepti! Brie-valkohomejuusto, salaattisekoitus, pikkuperuna, yrttimarinoitu edamame-papu, retiisi, pikkelöity kaalisalaatti ja lipstikka-jogurttiaioli. laktoositon gluteeniton"
      ],
      "tiistai": [
        "Päivän burgeri: Delaware",
        "Suosituin burgerimme! Briossisämpylä, cheddarjuusto, chili-sipulihilloke, pekoni, tomaatti, salaatti ja Kontin savupaprikamajoneesi. Ranut ja lipstikka-jogurttiaiolia. vähälaktoosinen",
        "Pihvivaihtoehdot:",
        "Naudanlihapihvi",
        "Kanan rintafilee",
        "saatavana laktoosittomana saatavana gluteenittomana +1€ saatavana vegaanisena",
        "Päivän salaatti: Elisabethin salaatti"
      ],
      "keskiviikko": [
        "Päivän burgeri: Darby",
        "Kanan rintafilee",
        "Mortonin porkkana-pellavapihvi.",
        "Päivän salaatti: Lydian salaatti",
        "Uusi resepti! Brie-valkohomejuusto, salaattisekoitus, pikkuperuna, yrttimarinoitu edamame-papu, retiisi, pikkelöity kaalisalaatti ja lipstikka-jogurttiaioli. laktoositon gluteeniton",
        "saatavana vegaanisena"
      ],
      "torstai": [
        "Päivän burgeri: Little John",
        "Mortonin klassikkoburgeri! Briossisämpylä, Peltolan Blue -sinihomejuusto, punasipulihilloke, Myrttisen maustekurkku, tomaatti, salaatti, chipotlemajoneesi. vähälaktoosinen",
        "Lisäksi ranut ja lipstikka-jogurttiaiolia.",
        "Pihvivaihtoehdot: Naudanlihapihvi Mortonin porkkana-pellavapihvi",
        "saatavana vegaanisena saatavana laktoosittomana saatavana gluteenittomana +1€",
        "Päivän salaatti: Saran salaatti"
      ]
    },
    "9": {
      "maanantai": [
        "Surf & Turf grillatulla kanalla ja sahramimarinoiduilla jättikatkaravunpyrstöillä, punaviinikastike, teriyakilla marinoitua punakaalia, paahdettua perunaa ja aioli L,G 15,50€",
        "Pinaattirisotto, bufala-mozzarellaa, yrttiöljyä ja paahdettua pähkinää VL,G 15,50€",
        "Kana-caesarsalaatti L,(G) 15,50€",
        "Grillattu härän lehtipihvi, chipotlevoita, punaviinikastiketta, kauden kasviksia, lohkoperunaa ja aioli L,G 23€",
        "Beef burger, ranskalaiset ja dippi L,(G) 18,50€",
        "Fish’n’ chips, tartarkastike ja muhennettua hernettä L 19,50€"
      ],
      "tiistai": [
        "Grillattu jauhelihapihvi, sienikastike ja paahdettua perunaa L,G 15,50€",
        "Linguinepasta tomaattikastikkerlla, Burratalla ja pestolla 15,50€",
        "Jokirapusalaatti L,G 15,50€",
        "Grillattu härän entrcôte, punaviinikastiketta, kauden kasviksia, lohkoperunaa ja aioli L,G 23€",
        "Beef burger, ranskalaiset ja dippi L,(G) 18,50€",
        "Fish’n’ chips, tartarkastike ja muhennettua hernettä L 19,50€"
      ],
      "keskiviikko": [
        "Piimällä marinoitua kanaa, tzatziki, riisiä ja tillillä maustettua kurkku-sipulisalaattia L,G 15,50€",
        "Linguinepasta tomaattikastikkerlla, Burratalla ja pestolla 15,50€",
        "Jokirapusalaatti L,G 15,50€",
        "Grillattu härän entrcôte, punaviinikastiketta, kauden kasviksia, lohkoperunaa ja aioli L,G 23€",
        "Beef burger, ranskalaiset ja dippi L,(G) 18,50€",
        "Fish’n’ chips, tartarkastike ja muhennettua hernettä L 19,50€"
      ],
      "torstai": [
        "Sweet & Chili seitifileetä, perunapyree ja broccolia L,G 15,50€,G",
        "Veriappelsiinirisotto, paistettua vuohenjuustoa ja paahdettua pistaasia G 15,50€",
        "Jokirapusalaatti L,G 15,50€",
        "Grillattu härän entrcôte, punaviinikastiketta, kauden kasviksia, lohkoperunaa ja aioli L,G 23€",
        "Beef burger, ranskalaiset ja dippi L,(G) 18,50€",
        "Fish’n’ chips, tartarkastike ja muhennettua hernettä L 19,50€"
      ],
      "perjantai": [
        "Sous vide naudan brisket, timjamikastiketta, marinoitua punakaalia, lohkoperunaa ja dijonkreemi L,G 15,50€,G",
        "Veriappelsiinirisotto, paistettua vuohenjuustoa ja paahdettua pistaasia G 15,50€",
        "Jokirapusalaatti L,G 15,50€",
        "Grillattu härän entrcôte, punaviinikastiketta, kauden kasviksia, lohkoperunaa ja aioli L,G 23€",
        "Beef burger, ranskalaiset ja dippi L,(G) 18,50€",
        "Fish’n’ chips, tartarkastike ja muhennettua hernettä L 19,50€",
        "”Ehdottomasti tulen uudelleen. Upea ”kanavaravintola”, erinomainen ruoka, ystävällinen palvelu.”",
        "”Kerran kesässä käytävä luottokohde ja aina yhtä toimiva! Ruoka on maukasta ja tulee nopeasti, palvelu on todella mukavaa ja kiireettömän tuntuista! Vahva suositus 👌”",
        "”Kiitos hyvästä ja ystävällisestä palvelusta. Ruoka oli maistuvaa ja annoskoot sopivat (teinikin sai vatsansa täyteen). Meille jäi vierailustamme hyvä mieli!”",
        "”Ravintolassa oli kiva tunnelma ja tarjoilijat olivat todella miellyttäviä ja palvelualttiita. Erinomainen hinta-laatusuhde. Tulen varmasti uudelleen tähän ravintolaan.”"
      ]
    },
    "10": {
      "tiistai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Luomutofu-kasviscurrya (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Välimeren halloumipiirakkaa (A, ILM, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Smetana-sinappi porsaspataa (A, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Riisiä ja kotimaista kauraa (A, G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Sitruunaista turskaa ja kesäkurpitsa-parsakaalipaistosta (A, G, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Keitettyjä perunoita (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Vanilja kruunuviineri (A)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Linssisosekeittoa (A, G, ILM, L, M, Veg)"
      ],
      "keskiviikko": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Seitanlastuja (A, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Rapeaa kanaa Gochujang (A, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Riisiä (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paprikalla maustettuja lammasmurekepihvejä (A, L, M, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Limellä maustettua jogurttia (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettuja yrttiperunoita (G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Mokkapala (A, L, M)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Myskikurpitsasosekeittoa (A, G, ILM, L, M, Veg, VS)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Raejuustoa (A, G, L)"
      ],
      "torstai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Puttanescakastiketta (A, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Bolognesekastiketta (A, G, L, M, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Spagettia (A, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettua kirjolohta (A, G, ILM, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Ruohosipuli-kermaviilikastiketta (A, G, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Bataatti-perunasosetta (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Ohukaisia (A)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Mansikkahilloa (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Kermavaahtoa (A, G, L)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Pinaattikeittoa (A, G, ILM, L, M, Veg)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Keitetty kananmuna (A, G, ILM, L, M)"
      ],
      "perjantai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Maustettua nyhtökauraa ja kevätsipulia (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Broileri-kasvistäytettä (A, G, L, M, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Tortillaa (A, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Tuoretomaattisalsaa (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Guacamolea (G, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Jogurttia (A, G, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Riisiä (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Porsaan grillipihvi (G, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pippurista tuorejuustokastiketta (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Churro (A, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Suklaakastiketta (A, G)",
        "Keittolounas (sis. salaattipöytä, keitto, jälkiruoka, kahvi/tee): Lanttusosekeittoa (A, G, ILM, L)"
      ]
    },
    "11": {
      "maanantai": [
        "Lounasbuffet 13,20 €:",
        "Kanakormaa",
        "Rapeita chilikalafileitä",
        "Panang curry – thaimaalaista currya luomutofulla",
        "Marokkolaista kurpitsakeittoa",
        "Basmatiriisiä",
        "Yrttiperunaa",
        "Timjamilla maustettua porkkanaa",
        "Chili-limejugurttia",
        "Sitruunarahkaa",
        "Kahvi"
      ],
      "tiistai": [
        "Lounasbuffet 13,20 €:",
        "Misokastikkeella glaseerattua possunniskaa",
        "Lyonin kanaa",
        "Itte tehtyjä juustoisia kesäkurpitsamurekepihvejä",
        "Punajuuri-vuohenjuustokeittoa",
        "Maalaislohkoperunoita",
        "Riisiä",
        "Kukkakaalia",
        "Ruohosipuli-kermaviilikastiketta",
        "Mustikkakukkoa",
        "Kahvi"
      ],
      "keskiviikko": [
        "Lounasbuffet 13,20 €:",
        "Lindströminpihvejä",
        "Tikka masala -maustettua kalkkunaa",
        "Tofu ratatouille – kasvispaistosta",
        "Paahdettua juuressosekeittoa",
        "Valkosipulikermaperunoita",
        "Currymaustettua riisiä",
        "Sinappisia uuniporkkanoita",
        "Kapris-ranskankermakastiketta",
        "Passionpannacotta #",
        "Kahvi"
      ],
      "torstai": [
        "Lounasbuffet 13,20 €:",
        "Kukkoa viinissä",
        "Katkarapuskagentäytettä",
        "Peshawarin tofucurry – currypataa pakistanilaisittain",
        "Kasvishernekeittoa",
        "Uuniperunoita",
        "Mausteista riisiä",
        "Rosmariinipunajuuria",
        "Antellin pannukakkua",
        "Kermavaahtoa",
        "Marjahilloa",
        "Kahvi"
      ],
      "perjantai": [
        "Lounasbuffet 13,20 €:",
        "Porsaan grillipihvejä",
        "Bulgogi chicken – kanaa korealaisittain",
        "Napolilaista lasagnea",
        "Metsäsienikeittoa",
        "Maustepaahdettuja perunoita",
        "Yrttistä kvinoaa ja riisiä",
        "Paahdettua palsternakkaa",
        "Itte tehtyä maustevoita",
        "Jäätelöbaari",
        "Kahvi"
      ]
    },
    "12": {
      "tiistai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Parsakaalisosekeittoa (A, G, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Kasvis-Chavrepyörykkä (A, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Wasabi-herne-kauragurttikastiketta (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Rapeaa broileria (A, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Avokadokermaviiliä (A, G, L, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Lihapullia tomaattikastikkeessa (A, L, M, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettua perunaa, chilimajoneesia ja korianteria (A, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Amerikkalaista porkkanakakkua (A, L)"
      ],
      "keskiviikko": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Tomaattikeittoa (L, G, VS) (A, G, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Chili con vege (A, ILM, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Riisiä ja kotimaista kauraa (A, G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Jerk Chicken -broileria Jamaican tapaan (A, G, L, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Chili-mangochutneyta (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Meidän keittiön kirjolohimureketta (A, G, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Piparjuurihollandaisekastiketta (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettua perunaa (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Karpalo-juustokakkumousse (A, L)"
      ],
      "torstai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Palsternakkasosekeittoa (A, G, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pinaattiohukaisia (A, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Puolukkahilloa (A, G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Persiljaperunoita (A, G, ILM, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Meidän keittiön lasagnea (A, L, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Korean Chicken (A, L, M, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Paahdettua myskikurpitsaa, chili-majoneesia ja pikkelöityä chiliä (A, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Riisiä ja kotimaista kauraa (A, G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Meidän keittiön pannukakkua (A, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Mansikkahilloa (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Kermavaahtoa (A, G, L)"
      ],
      "perjantai": [
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Puutarhurin juuressosekeittoa (A, G, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Mö chavre - vegaanisia vuustokasvispyöryköitä (A, ILM, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Salsa verde (A, G, L, M, Veg, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Riisiä (A, G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pastaa, katkarapuja ja tilliä (A, L, VS)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Pastajuustoa (A, G, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Wieninleike (A, L, M)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Perunamuusia (A, G, ILM, L)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Satokauden kasviksia (G, L, M, Veg)",
        "Lounasbuffet (sis. salaattipöytä, lämmin lounas, jälkiruoka, kahvi/tee): Food & Co Jäätelöbuffet (A, G, L)"
      ]
    },
    "13": {
      "maanantai": [
        "1.Veg kofta chilli (G,L)* Vegaani / Vegan",
        "Kasvispyöryköita mausteisessa soija-chillikastikkeessa.",
        "2.Shahi Paneer (G)",
        "Leipäjuustopaloja tomaatti-voi-kermakastikkeessa.",
        "3.Chicken Tikka Masala (G)**",
        "Tandoori-uunissa grillattua kanaa mausteisessa masalakastikkeessa.",
        "4.lamb Vindalo(G,L)*"
      ],
      "tiistai": [
        "1.Paneer Masala (G)*",
        "Paneer-juustoa tomaatti-sipuli-valkosipuli-masalakastikeessa.",
        "2.Saag Tofu (G)*",
        "3.Butter Chicken (G)",
        "Tandoori-uunissa grillattua kanaa tomaatti-voi-kermakastikkeessa.",
        "4.Lamb Kofta (G,L)*",
        "Lampaan jauhelihapyöryköitä hieman mausteisessa tomaatti-valkosipuli-inkivääri-sipuli-currykastikkeessa."
      ],
      "keskiviikko": [
        "1.Tofu Chili (G,L)** Vegaani / Vegan",
        "Tofua, paprikaa ja sipulia chili-soijakastikkeessa.",
        "2.Malai Kofta (G)",
        "Paneerjuusto-kasvispyöryköitä tomaatti-voi-kermakastikkeessa.",
        "3.Kadai Chicken (G,L)*",
        "4.Lamb Saag (G,L)*",
        "Haudutettua lammasta pinaatti-tomaatti-inkivääri-valkosipuli-currykastikkeessa."
      ],
      "torstai": [
        "1.Tofu Masala (G,L)* Vegaani / Vegan",
        "Tofua masala-kastikkeessa..",
        "2.Paneer Makhani (G)",
        "Paneer-juustoa tomaatti-voi-kermakastikkeessa.",
        "3.Garlic chicken(G,L)*",
        "4.Chicken Lamb Masala (G)*",
        "Yrtti-jogurttimarinoitua ja tandoori-uunissa grillattua kanaa ja lampaanjauhelihaa mausteisessa tomaatti-sipuli-inkiväärikastikkeessa."
      ],
      "perjantai": [
        "1.Aloo Gobi Tofu (G,L)* Vegaani / Vegan",
        "Kukkakaalia,tofu ja perunaa tomaatti-masalakastikkeesa",
        "2.Saag Paneer (G)",
        "Paneer-juustoa pinaatti-curry-kermakastikkeessa.",
        "3.Butter Chicken (G)",
        "Tandoori-uunissa grillattua kanaa tomaatti-voi-kermakastikkeessa",
        "4.Lamb Curry (G,L)*"
      ]
    },
    "14": {
      "keskiviikko": [
        "na 10. joulukuuta klo 11:00–14:00. Hinta: 19,90 €Seuraavissa ravintoloissa:Ravintola Huudi",
        "Ravintola Fågeli",
        "Ravintola Oikeus",
        "Ravintola Verkstad",
        "Cafeteria Vuokki",
        "Ravintola Käpis",
        "Ravintola Bron",
        "Sekä Ravintola Oasis (opening soon)Mechelininkatu 1a, 00180 Helsinki+358 0400510970 | oasis@nordrest.fi",
        "Special Foods Division",
        "Nordrest Special Foods Division (SFD) delivers long-shelf-life food solutions for defence, emergency preparedness, humanitarian operations, and institutional customers."
      ]
    },
    "15": {
      "maanantai": [
        "Lounasbuffet 13,90 €:",
        "Lihapullia kermaisessa pippurikastikkeessa",
        "Melanzane – munakoiso-tomaattivuokaa",
        "Perunamuusia",
        "Puolukkasurvosta",
        "Luomukahvi"
      ],
      "tiistai": [
        "Lounasbuffet 13,90 €:",
        "Seesamipaahdettua kanaa",
        "Itte tehtyjä juurespihvejä",
        "Jasmiiniriisiä",
        "Limeaiolia",
        "Luomukahvi"
      ],
      "keskiviikko": [
        "Lounasbuffet 13,90 €:",
        "Kevyesti savustettua kirjolohta",
        "Pinaattiohukaisia",
        "Tilliperunoita",
        "Tartarkastiketta",
        "Polukkahilloa",
        "Luomukahvi"
      ],
      "torstai": [
        "Lounasbuffet 13,90 €:",
        "Metsästäjänleike",
        "Kesäkurpitsa-halloumipihvejä",
        "Kermaperunoita",
        "Metsäsienikastiketta",
        "Tzazikia",
        "Luomukahvi"
      ],
      "perjantai": [
        "Lounasbuffet 13,90 €:",
        "Kermaista kirjolohikeittoa",
        "Tomaatti-Mozzarellapiirakka #",
        "Omena-kanelipiirakkaa",
        "Vaniljakastiketta",
        "Luomukahvi"
      ]
    },
    "16": {
      "maanantai": [
        "Lemongrass Stir-Fried ChickenL",
        "Mandarin Chicken L,G",
        "Crispy Fried Pangasius in Sweet and Sour Sauce (wheat and egg contained) L",
        "Vietnamese Vegan Curry L,G,V",
        "Non-fried Tofu with Sweet and Sour sauce Singapore Style. L,V,G"
      ],
      "tiistai": [
        "Stir-fried veggies & Tofu in Teriyaki sauce. L",
        "Meatballs in tamarind sauce. L,G",
        "Roasted Eggplant (V). L,G,V",
        "Crispy-fried chicken balls. L",
        "Stir-fried lemongrass chicken. L,G",
        "Vegan mixed noodle salad with soy sauce dressing (Contains Peanuts). L,V"
      ],
      "keskiviikko": [
        "Orange Chicken L",
        "Lemongrass Stir-fried Pork L,G",
        "Fried Pangasius in Homemade Sweet and Sour Sauce L",
        "Oven-roasted Eggplants with Tofu, and Salty Radish in Homemade Sweet Soy Sauce L,V",
        "Stir-fried Rice Noodles with Vietnamese Vegan Ham L,V",
        "Non-fried Tofu with Sweet and Sour sauce L,G,V"
      ],
      "torstai": [
        "Braised Chicken with Ginger L,G",
        "Fried Pangasius in sweet Tomato sauce L",
        "Fried Chicken with Red Pepper in Sweet and Sour Sauce L",
        "Wok-fried Tofu and Vegetables in homemade Teriyaki Sauce L,V",
        "Vietnamese Vegan Curry L,V,G",
        "Stir-fried Veggies and Tofu in Tomyum sauce L,G,V"
      ],
      "perjantai": [
        "Ragu Chicken L",
        "Crispy Fried Pangasius in Sweet and Sour Sauce (wheat and egg contained) L",
        "Kung Pao Chicken L",
        "Stir-fried Veggies with Slices Vegan Beef in Teriyaki Sauce L,V",
        "Stir Fried Egg noodles, Vegan ( contained Egg and wheat). L,V",
        "Fried Rice with Veggies, (contained Egg) L,V",
        "function showTab(day) {",
        "// Hide all tabs"
      ]
    },
    "17": {
      "keskiviikko": [
        "Tom yam -rapukeitto (M+G+VS)",
        "Nepalilainen Butter Chicken paahdetuilla cashewpähkinöillä (L+G+VS+sis. pähkinää) basmatiriisi (VE+G)",
        "Voissa paistetut ruispaneroidut muikut (L) tilli-kermaviili (L+G) perunamuusi (L+G)",
        "Siirappi-paahdetut maalaisporkkanalohkot, rapeaa tofua ja seesaminsiemeniä (VE+G)",
        "Snickers-mousse suolapähkinä-kauragranolalla (VE+G+sis.pähkinä)"
      ],
      "torstai": [
        "Hernekeitto (M+G) pilkottua sipulia (VE+G)",
        "Mureita porsaan ulkofilenoisetteja konjakki-pippurikastikkeessa (L+G) timjamiperunat (VE+G)",
        "Chicken 65 – meillä tehdyt mausteiset friteeratut kanan paistileikkeet (M+G+VS) basmatiriisi (VE+G)",
        "MUU vege -nakkipaloja kasviksilla ja sataykastikkeella (VE+G+VS+sis.pähkinää)",
        "Factoryn letut (L) mansikkahillo (VE+G) kermavaahto (L+G) jäätelö (L+G)"
      ],
      "perjantai": [
        "Kermainen lohikeitto (L+G)",
        "Naudan kebablastuja makean tulisessa paprika-tomaatti-basilikakastikkeessa (M+G+VS)",
        "turkkilaista jogurttia (L+G) basmatiriisi (VE+G)",
        "Fish & Chips – tempura-paneroitua turskaa (L) avocado-ranch -dippi (L) rapeat ranskalaiset (VE+G)",
        "Kana-halloumipasta sitruuna–valkosipuli-kermakastikkeessa ja parmesaanimurua (L+VS)",
        "Tonnikalapizza chili-limemajoneesi -raitakastikkeella (L)",
        "Seesami-tofua ja kasviksia sweet & sour -kastikkeessa (VE+G+VS)",
        "Kakkulajitelma (L)"
      ]
    },
    "18": {
      "maanantai": [
        "Ravintola suljettu – Hyvää pääsiäistä!"
      ],
      "tiistai": [
        "A) Provencen yrteillä marinoitua kananpoikaa, couscousia ja tzatzikia (L, saatavilla G) 14.00€",
        "B) Tuorejuustotäytteisiä pinaattipihvejä, munakoiso-kvinoaa ja tomaattichutneyta (L, G, saatavilla VE) 14.00€",
        "C) Kaalikääryleet – Ylikypsää härän rintaa, puolukkakastiketta ja höyrytettyä varhaiskaalia sekä yrttiohraa (L) 14.70€",
        "Jälki-istunto ja kahvi – Porkkanakakkua (L) 2€"
      ],
      "keskiviikko": [
        "A) Grillattu possun lehtipihvi, bearnaisekastiketta ja paahdettua peruna-parsasalaattia (L, G) 14.00€",
        "B) Butter curry – Jalotofua mausteisessa tomaatti-voikastikkeessa, mintturaitaa ja basmatiriisiä (L, G, saatavilla VE) 14.00€",
        "C) Mantelikala – Kevyesti hiillostettua kuhaa, valkoviinikastiketta ja hiillostettuja perunoita sekä paahdettuja mantelilastuja (L, G) 14.70€",
        "Jälki-istunto ja kahvi – Porkkanakakkua (L)2€"
      ],
      "torstai": [
        "A) Oluessa haudutettua riistakäristystä saksanhirvestä, ruskealla voilla maustettua juurespyreetä ja hillottuja karpaloita (L, G) 14.00€",
        "B) Gnoccheja sitruunakastikkeessa, ricottamoussea ja puolikuivattuja luumutomaatteja (VL, saatavilla G, VE) 14.00€",
        "C) Mantelikala – Kevyesti hiillostettua kuhaa, valkoviinikastiketta ja hiillostettuja perunoita sekä paahdettuja mantelilastuja (L, G) 14.70€",
        "Jälki-istunto ja kahvi – Suklaa-appelsiinimoussea (L, G)"
      ],
      "perjantai": [
        "A) Cheddar Jalapeño burger – briossia, 100% naudanlihaburgerpihvi, kypsytettyä cheddarjuustoa, jalapeño-limemajoneesia ja ranskalaisia (saatavilla G)14.00€",
        "B) Chili sin carne, avokadomoussea ja riisiä sekä maissisalsaa (VE, G) 14.00€",
        "C) Mantelikala – Kevyesti hiillostettua kuhaa, valkoviinikastiketta ja hiillostettuja perunoita sekä paahdettuja mantelilastuja (L, G) 14.70€",
        "Jälki-istunto ja kahvi – Suklaa-appelsiinimoussea (L, G)",
        "SisältöLounas",
        "Lunch Kamppi",
        "Olemme esteetön ravintola!",
        ".kb-row-layout-idblock-38_b24816-ee > .kt-row-column-wrap{ali"
      ]
    },
    "19": {
      "maanantai": [
        "Härkäpapu tagine (V, G)",
        "Mausteinen riisi (V, G)"
      ],
      "tiistai": [
        "Nautaa punaviinikastikkeessa (M, G)",
        "Kikherne tagine (V, G)",
        "Couscous (V)"
      ],
      "keskiviikko": [
        "Kampela sitruuna-yrttikastikkeessa (M)",
        "Kurpitsa tagine (V, G)",
        "Paahdetut perunat (V, G)"
      ],
      "torstai": [
        "Kanaa sahramikastikkeessa (M, G)",
        "Mausteinen munakoisotagine (V, G)",
        "Mausteinen riisi (V, G)"
      ],
      "perjantai": [
        "Porsasta tomaattikastikkeessa (M, G)",
        "Härkäpapu tagine (V, G)",
        "Lohkoperunat (V, G)",
        "(M = Maidoton, G = Gluteeniton, V = Vegaaninen)",
        "Sandro Kortteli",
        "Kauppakeskus Kamppi 5 kerros",
        "Urho Kekkosen katu 1",
        "Evästeet ja tietosuoja",
        "Oivaraportti",
        "Meille töihin"
      ]
    },
    "20": {
      "maanantai": [
        "Insalata di Pollo 13.50 €",
        "Spaghetti porta susa 13.50 €",
        "Penne alla Coppola 14.20 €",
        "Ravioli Tricolore 14.80 €"
      ],
      "tiistai": [
        "Insalata di Pollo 13.50 €",
        "Spaghetti porta susa 13.50 €",
        "Penne alla Coppola 14.20 €",
        "Ravioli Tricolore 14.80 €"
      ],
      "keskiviikko": [
        "Insalata di Pollo 13.50 €",
        "Spaghetti porta susa 13.50 €",
        "Penne alla Coppola 14.20 €",
        "Ravioli Tricolore 14.80 €"
      ],
      "torstai": [
        "Insalata di Pollo 13.50 €",
        "Spaghetti porta susa 13.50 €",
        "Penne alla Coppola 14.20 €",
        "Ravioli Tricolore 14.80 €"
      ],
      "perjantai": [
        "Insalata di Pollo 13.50 €",
        "Spaghetti porta susa 13.50 €",
        "Penne alla Coppola 14.20 €",
        "Ravioli Tricolore 14.80 €"
      ]
    },
    "21": {
      "maanantai": [
        "Punainencurry siiasta ja limeriisiä",
        "Punainen kasviscurry ja limeriisiä"
      ],
      "tiistai": [
        "Tofu-kasvispaistosta"
      ],
      "keskiviikko": [
        "Sipulipihvejä, perunamuusia ja pippurinen kermakastike",
        "Paahdettuja falafeleja, perunamuusia ja pippurinen kermakastike",
        "Roasted falafel, mashed potatoes and creamy pepper sauce"
      ],
      "perjantai": [
        "Lihapulla-pyttipannu, paistettuja kananmunia ja kurkkusalaattia",
        "Vegaaninen pyttipannu",
        "Vegan hash",
        "Tervetuloa lounaalle Tislaamolle!Welcome to lunch at Tislaamo!",
        "What’s Happening at Henry’s Distillery:",
        "-Our upcoming events are published here.More upcoming events and campaigns you can find in our Music Bar’s side!",
        "@henryskasarmi | @kulttuurikasarmievents",
        "!function(){\"use strict\";if(\"query"
      ]
    },
    "22": {
      "tiistai": [
        "Manun lounasbuffet",
        "Paahdettua broileria,",
        "kermaista harissakastiketta L,G",
        "Pinaattiohukaiset, puolukkasurvosta VE,G",
        "Kvinoaa ja kasviksia VE,G",
        "Kermainen kalakeitto L,G",
        "Manun lounasbuffet",
        "Inkivääri-hunaja possua kastikkeessa M,G",
        "Kikherne-kasviscurry VE,G",
        "Riisiä VE,G",
        "Höyrytettyä kukka- ja parsakaalia VE,G",
        "Maa-artisokkakeitto L,G",
        "Manun lounasbuffet",
        "Paistettuja muikkuja L, tillikermaviiliä L,G",
        "Punajuuripihvit, tillicremeä VE,G",
        "Muusia L,G",
        "Paahdetut juurekset VE,G",
        "Hernekeittoa M,G",
        "Pannukakkua L,",
        "mansikkahilloa VE,G ja kermavaahtoa L,G",
        "(pyydettäessä glut.ohukainen G,L)",
        "Manun lounasbuffet",
        "Uunilohi, kermainen sienikastike L,G",
        "Paahdettuja perunoita ja kauden kasviksia VE, G",
        "Porkkana inkiväärikeittoa ja paahdettua tofua VE,G"
      ],
      "keskiviikko": [
        "Manun lounasbuffet",
        "Inkivääri-hunaja possua kastikkeessa M,G",
        "Kikherne-kasviscurry VE,G",
        "Riisiä VE,G",
        "Höyrytettyä kukka- ja parsakaalia VE,G",
        "Maa-artisokkakeitto L,G",
        "Manun lounasbuffet",
        "Paistettuja muikkuja L, tillikermaviiliä L,G",
        "Punajuuripihvit, tillicremeä VE,G",
        "Muusia L,G",
        "Paahdetut juurekset VE,G",
        "Hernekeittoa M,G",
        "Pannukakkua L,",
        "mansikkahilloa VE,G ja kermavaahtoa L,G",
        "(pyydettäessä glut.ohukainen G,L)",
        "Manun lounasbuffet",
        "Uunilohi, kermainen sienikastike L,G",
        "Paahdettuja perunoita ja kauden kasviksia VE, G",
        "Porkkana inkiväärikeittoa ja paahdettua tofua VE,G",
        "Manun lounasbuffet",
        "Kirjolohipyörykät L ja tartarkastike L,G",
        "Papu-kasviscurry VE,G",
        "Pinaattimuusia L,G",
        "Paahdettua kukka -ja parsakaalia VE,G",
        "Mausteinen myskikurpitsakeitto VE,G"
      ],
      "torstai": [
        "Manun lounasbuffet",
        "Paistettuja muikkuja L, tillikermaviiliä L,G",
        "Punajuuripihvit, tillicremeä VE,G",
        "Muusia L,G",
        "Paahdetut juurekset VE,G",
        "Hernekeittoa M,G",
        "Pannukakkua L,",
        "mansikkahilloa VE,G ja kermavaahtoa L,G",
        "(pyydettäessä glut.ohukainen G,L)",
        "Manun lounasbuffet",
        "Uunilohi, kermainen sienikastike L,G",
        "Paahdettuja perunoita ja kauden kasviksia VE, G",
        "Porkkana inkiväärikeittoa ja paahdettua tofua VE,G",
        "Manun lounasbuffet",
        "Kirjolohipyörykät L ja tartarkastike L,G",
        "Papu-kasviscurry VE,G",
        "Pinaattimuusia L,G",
        "Paahdettua kukka -ja parsakaalia VE,G",
        "Mausteinen myskikurpitsakeitto VE,G",
        "Manun Lounasbuffet",
        "Kermaista viherpippuripossua L,G",
        "Kasvispihvejä, aiolia VE,G",
        "Paahdettuja juureksia ja perunoita VE,G",
        "Tomaattikeitto VE,G"
      ],
      "perjantai": [
        "Manun lounasbuffet",
        "Uunilohi, kermainen sienikastike L,G",
        "Paahdettuja perunoita ja kauden kasviksia VE, G",
        "Porkkana inkiväärikeittoa ja paahdettua tofua VE,G",
        "Manun lounasbuffet",
        "Kirjolohipyörykät L ja tartarkastike L,G",
        "Papu-kasviscurry VE,G",
        "Pinaattimuusia L,G",
        "Paahdettua kukka -ja parsakaalia VE,G",
        "Mausteinen myskikurpitsakeitto VE,G",
        "Manun Lounasbuffet",
        "Kermaista viherpippuripossua L,G",
        "Kasvispihvejä, aiolia VE,G",
        "Paahdettuja juureksia ja perunoita VE,G",
        "Tomaattikeitto VE,G",
        "Manun Lounasbuffet",
        "Pannupihvi \\u0026 tummaa timjamikastiketta L,G",
        "Falafelpyörykkä, tartarkastike VE,G",
        "Keitettujä perunoita VE,G",
        "Kauden kasviksia VE, G",
        "Paahdettu kukkakaalisosekeitto L,G"
      ]
    },
    "24": {
      "maanantai": [
        "2. Pääsiäispäivä, ei lounasta"
      ],
      "tiistai": [
        "Päivän keitto: Borssikeitto (L, G)",
        "Lihapullat kermakastikkeella (L, G), Puolukkahillo (M, G)",
        "Sataykana (M, sis. pähkinää)",
        "Tofu-kasvispata (Ve, G)",
        "Perunamuusi (L, G)",
        "Riisi (Ve, G)"
      ],
      "keskiviikko": [
        "Päivän keitto: Kermainen maa-artisokkakeitto (L, G)",
        "Jauhelihapihvit pippurikastikkeella (L, G) Puolukkahillo (M, G)",
        "Broileria vihreällä currykastikkeella (M, G)",
        "Kikhernepata (Ve, G)",
        "Lohkoperunat (M, G)",
        "Riisi (Ve, G)"
      ],
      "torstai": [
        "Päivän keitto: Hernekeitto (M, G), pannukakkua (L)",
        "Seitiä voikastikkeessa (L, G)",
        "Valkosipuliperunat (L, G)",
        "Riisi (Ve, G)"
      ],
      "perjantai": [
        "Päivän keitto: Minestronekeitto (L, G)",
        "Kanapihvit kermakastikkeessa (L, G)",
        "Tofu korma (Ve, G)",
        "Perunamuusi (L, G)",
        "Riisi (Ve, G)",
        "Viikon leike 14,90 €:",
        "JOHN SCOTT’S BURGER 13,90 €",
        "120 g naudanlihapihvi, cheddarjuusto, 3 dippiä",
        "Fish & Chips 14,90 (L) €",
        "JOHN SCOTT´S BURGER 13,90 €"
      ]
    },
    "25": {
      "maanantai": [
        "Lounasbuffet 13,70 €:",
        "Kebabstroganoffia",
        "Tom yam -keittoa katkaravuilla",
        "Yrttistä kvinoaa ja riisiä",
        "Valkosipulipapuja",
        "Mustaherukka-banaanismoothieta",
        "Kahviannos , maito ja sokeri"
      ],
      "tiistai": [
        "Lounasbuffet 13,70 €:",
        "Butter chicken – intialaista kanakastiketta",
        "Salvialla maustettua juustokeittoa",
        "Pinaattiriisiä",
        "Hunajaisia rakuunaporkkanoita",
        "Marjapiirakkaa",
        "Kahviannos , maito ja sokeri"
      ],
      "keskiviikko": [
        "Lounasbuffet 13,70 €:",
        "Antellin kanalasagnea",
        "Katkarapu-kalakeittoa",
        "Kookos-jogurtti mansikalla",
        "Kahviannos , maito ja sokeri"
      ],
      "torstai": [
        "Lounasbuffet 13,70 €:",
        "Meksikon pikajunaa",
        "Punaista curry-kalkkunakeittoa",
        "Perunamuusia",
        "Paahdettua uuniporkkanaa ja lanttua",
        "Uuniomenarahkaa",
        "Kahviannos, maito ja sokeri"
      ],
      "perjantai": [
        "Lounasbuffet 13,70 €:",
        "Lohi-katkarapucurrya",
        "Herkkusienikeittoa",
        "Basmatiriisiä",
        "Marjahilloa",
        "Kermavaahtoa",
        "Vohveleita",
        "Kahviannos maito ja sokeri"
      ]
    },
    "26": {
      "maanantai": [
        "Kana Cobb -salaatti (L, G)",
        "Kermaista rosmariinipastaa ja ylikypsää porsaanposkea (L)",
        "Punajuuririsotto ja paahdettua vuohenjuustoa (L, G)",
        "No-chicken taco (Ve)",
        "Ceviche-lohi taco (L)"
      ],
      "tiistai": [
        "Kana Cobb -salaatti (L, G)",
        "Kermaista rosmariinipastaa ja ylikypsää porsaanposkea (L)",
        "Punajuuririsotto ja paahdettua vuohenjuustoa (L, G)",
        "No-chicken taco (Ve)",
        "Ceviche-lohi taco (L)"
      ],
      "keskiviikko": [
        "Kana Cobb -salaatti (L, G)",
        "Kermaista rosmariinipastaa ja ylikypsää porsaanposkea (L)",
        "Punajuuririsotto ja paahdettua vuohenjuustoa (L, G)",
        "No-chicken taco (Ve)",
        "Ceviche-lohi taco (L)"
      ],
      "torstai": [
        "Kana Cobb -salaatti (L, G)",
        "Kermaista rosmariinipastaa ja ylikypsää porsaanposkea (L)",
        "Punajuuririsotto ja paahdettua vuohenjuustoa (L, G)",
        "No-chicken taco (Ve)",
        "Ceviche-lohi taco (L)"
      ],
      "perjantai": [
        "Kana Cobb -salaatti (L, G)",
        "Kermaista rosmariinipastaa ja ylikypsää porsaanposkea (L)",
        "Punajuuririsotto ja paahdettua vuohenjuustoa (L, G)",
        "No-chicken taco (Ve)",
        "Ceviche-lohi taco (L)"
      ]
    },
    "27": {
      "maanantai": [
        "Buffetlounas",
        "Paistettuja muikkuja, perunamuusia ja tilli-kermaviilikastiketta L",
        "Härkis-kaalilaatikkoa ja puolukkaa G, VE",
        "Tomaatti- linssikeitto G, VE",
        "Kahvi tai tee",
        "Buffetlounas",
        "Riistakäristystä, perunamuusia ja puolukkaa L, G",
        "Kasvis-uunipasta L",
        "Kukkakaali-currykeitto G, VE",
        "Kahvi tai tee",
        "Buffetlounas",
        "Lyonin kanaa ja basilikariisiä L, G",
        "Punajuurifalafelit ja tartarkastiketta G, VE",
        "Savuporo-juustokeitto L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Jauhelihakastiketta ja perunamuusia L, G",
        "Vege Pasta Bolognese VE",
        "Kermainen lohikeitto L, G",
        "Kahvi tai tee"
      ],
      "tiistai": [
        "Buffetlounas",
        "Paistettuja muikkuja, perunamuusia ja tilli-kermaviilikastiketta L",
        "Härkis-kaalilaatikkoa ja puolukkaa G, VE",
        "Tomaatti- linssikeitto G, VE",
        "Kahvi tai tee",
        "Buffetlounas",
        "Riistakäristystä, perunamuusia ja puolukkaa L, G",
        "Kasvis-uunipasta L",
        "Kukkakaali-currykeitto G, VE",
        "Kahvi tai tee",
        "Buffetlounas",
        "Lyonin kanaa ja basilikariisiä L, G",
        "Punajuurifalafelit ja tartarkastiketta G, VE",
        "Savuporo-juustokeitto L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Jauhelihakastiketta ja perunamuusia L, G",
        "Vege Pasta Bolognese VE",
        "Kermainen lohikeitto L, G",
        "Kahvi tai tee"
      ],
      "keskiviikko": [
        "Buffetlounas",
        "Riistakäristystä, perunamuusia ja puolukkaa L, G",
        "Kasvis-uunipasta L",
        "Kukkakaali-currykeitto G, VE",
        "Kahvi tai tee",
        "Buffetlounas",
        "Lyonin kanaa ja basilikariisiä L, G",
        "Punajuurifalafelit ja tartarkastiketta G, VE",
        "Savuporo-juustokeitto L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Jauhelihakastiketta ja perunamuusia L, G",
        "Vege Pasta Bolognese VE",
        "Kermainen lohikeitto L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Lihapullapasta L",
        "Uunifeta-tomaattipasta L",
        "Mausteinen porkkanakeitto VE, G",
        "Kahvi tai tee"
      ],
      "torstai": [
        "Buffetlounas",
        "Lyonin kanaa ja basilikariisiä L, G",
        "Punajuurifalafelit ja tartarkastiketta G, VE",
        "Savuporo-juustokeitto L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Jauhelihakastiketta ja perunamuusia L, G",
        "Vege Pasta Bolognese VE",
        "Kermainen lohikeitto L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Lihapullapasta L",
        "Uunifeta-tomaattipasta L",
        "Mausteinen porkkanakeitto VE, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Paistettua kampelaa, perunamuusia ja tilli-kermaviilikastike L",
        "Kasviskääryleitä ja puolukkaa VE, G",
        "Sipulikeitto G, VE",
        "Kahvi tai tee"
      ],
      "perjantai": [
        "Buffetlounas",
        "Jauhelihakastiketta ja perunamuusia L, G",
        "Vege Pasta Bolognese VE",
        "Kermainen lohikeitto L, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Lihapullapasta L",
        "Uunifeta-tomaattipasta L",
        "Mausteinen porkkanakeitto VE, G",
        "Kahvi tai tee",
        "Buffetlounas",
        "Paistettua kampelaa, perunamuusia ja tilli-kermaviilikastike L",
        "Kasviskääryleitä ja puolukkaa VE, G",
        "Sipulikeitto G, VE",
        "Kahvi tai tee",
        "Buffetlounas",
        "Lindströminpihvit ja kapriskermakastiketta L",
        "Juures-voipapupyörykät ja yrttikastike VE, M",
        "Paahdettuja perunoita G, VE",
        "Kana-currykeitto L, G",
        "Kahvi tai tee"
      ]
    },
    "28": {
      "maanantai": [
        "Broileri-sinihomejuustokastike L G",
        "Kikherne-bataatticurry ❤️ V G",
        "MYÖS TAKE AWAY"
      ],
      "tiistai": [
        "Tonnikalalasagnette ❤️ L",
        "Linssimoussaka ❤️ V G",
        "MYÖS TAKE AWAY"
      ],
      "keskiviikko": [
        "Kebabkastike ❤️ M G",
        "Vebabkastike ❤️ V",
        "MYÖS TAKE AWAY"
      ],
      "torstai": [
        "Kievinkana",
        "Falafelpyörykät ❤️ V G",
        "MYÖS TAKE AWAY"
      ],
      "perjantai": [
        "Kalanugetti ❤️ M G",
        "Marokko-kasvispihvi ❤️ V G",
        "MYÖS TAKE AWAY",
        "Joka päivä on tarjolla gluteeniton, maidoton ja vegaani ruoka.",
        "HUOM! Saatavuusongelmien vuoksi voi ruokalistaan tulla muutoksia.",
        "Ravintolatilaan ei ole esteetöntä pääsyä.",
        "Osakuntabaarin lounas",
        "Ei lounasta tänään",
        "Viikon lista",
        "Säätiön toimisto"
      ]
    },
    "29": {
      "maanantai": [
        "Hyvää pääsiäistä"
      ],
      "tiistai": [
        "Salaattipöytä (L)",
        "Chili con carne, riisiä, nachoja ja jalapenoja (G, M)",
        "Kantarellirisottoa ja parmesanjuustoa (G, L)",
        "Mausteinen nakkikeitto (G, M)",
        "Mansikka-melonismoothieta (G, M)",
        "Kahvi ja tee (G, M)"
      ],
      "keskiviikko": [
        "Salaattipöytä (L)",
        "Chorizo Arrabiata pastaa ja parmesaani juustoa (L)",
        "Feta-pinaattipiirakka (L)",
        "Kukkakaali-parsakaalikeitto (G, M)",
        "Marjahyve (G, L)",
        "Kahvi ja tee (G, M)"
      ],
      "torstai": [
        "Salaattipöytä (G, L)",
        "Seiti tikka masala ja keitettyjä perunoita (G, L)",
        "Linssi-soijatäytteisiä paprikoita ja riisiä (G, M)",
        "Bataattisosekeitto (G, M)",
        "Mustikka-talkkunarahka (L)",
        "Kahvi ja tee (G, M)"
      ],
      "perjantai": [
        "Salaattipöytä (L)",
        "Broileria yrtti-tomaattikastikeessa ja sahramiriisiä (G, M)",
        "Mie goreng -soijasuikale (G, M)",
        "Paprikatuorejuustokeitto (G, L)",
        "Trilece-kakku (L)",
        "Kahvi ja tee (G, M)"
      ]
    },
    "30": {
      "tiistai": [
        "Italialaiset kanafileet pestolla ja kirsikkatomaatilla (G, M)",
        "Kermainen jalotofu-pennepasta (VE, G)",
        "Pinaattinen kasvispata (VE, G)"
      ],
      "keskiviikko": [
        "Chili con carne (G, M)",
        "Kikherne-perunalaatikko (VE, G)",
        "Aasialainen vihreä curry jalotofulla (VE, G)"
      ],
      "torstai": [
        "Espanjalaiset kanafajitat (G, M)",
        "Kvinoa kasvispihvi suolakurkkumajoneesilla (VE, G)",
        "Härkäpapu-makaronilaatikko (VE, G)"
      ],
      "perjantai": [
        "Uunilohta tillimajoneesilla (G, M)",
        "Fettuccine Alfredo -pasta herkkusienillä (VE)",
        "Kvinoalla täytetyt kesäkurpitsat (VE, G)"
      ]
    },
    "32": {
      "maanantai": [
        "Moussakka (L)",
        "Kurkku feta salaatti (L, G)",
        "Vihersalaatti Vegaani, G",
        "Pullavanukas ja pappilan hätävara (L)"
      ],
      "tiistai": [
        "Sitruuna kanaa, villiriisi ja kurkkuraita (L, G)",
        "Vihreä kuningatar salaatti (L, G)",
        "Puutarhan vihersalaatti Vegaani, G",
        "Pullavanukas & pappilan hätävara (L)"
      ],
      "keskiviikko": [
        "Lohimurekepihvi, kermaviilikastike, perunamuussi (L)",
        "Italian salaatti (L)",
        "Puutarhan vihersalaatti Vegaani, G",
        "Pullavanukas & pappilan hätävara (L)"
      ],
      "torstai": [
        "Lihapullat pippurikastikketta ja paahdetut perunat (L)",
        "Marinoidut Välimeren vihannekset (L)",
        "Puutarhan víhersalaatti Vegaani, G",
        "Pullavanukas & pappilan hätävara (L) & (L, G)"
      ],
      "perjantai": [
        "Kana enchilada, creme fraiche ja paahdetut maissintähkät (L)",
        "Tomaatti jalopeno salaatti (G), Vegaani",
        "Puutarhan vihersalaatti Vegaani, G",
        "Pullavanukas & pappilan hätävara (L)"
      ]
    }
  }
};
