/* ── Siili Jyväskylä – Tapahtumat & Kalenteri ── data.js ── */

const OFFICE = { name: 'Siili Solutions Jyväskylä', address: 'Lutakonaukio 1, 40100 Jyväskylä', lat: 62.2391, lng: 25.7535 };

const VENUES = {
  siili:        { name: 'Siili Solutions',           address: 'Lutakonaukio 1',      lat: 62.2391, lng: 25.7535 },
  paviljonki:   { name: 'Paviljonki',                address: 'Messukatu 2',         lat: 62.2403, lng: 25.7565 },
  lutakonaukio:  { name: 'Lutakonaukio',              address: 'Lutakonaukio',         lat: 62.2387, lng: 25.7525 },
  kauppatori:   { name: 'Kauppatori',                address: 'Kauppatori',           lat: 62.2426, lng: 25.7473 },
  killeri:      { name: 'Killerin alue',             address: 'Killeri',              lat: 62.3120, lng: 25.7300 },
  hippos:       { name: 'Hippoksen stadion',         address: 'Hippoksenkatu',        lat: 62.2312, lng: 25.7397 },
  toivola:      { name: 'Toivolan Vanha Piha',       address: 'Cygnaeuksenkatu 2',    lat: 62.2445, lng: 25.7435 },
  teatteri:     { name: 'Jyväskylän kaupunginteatteri', address: 'Vapaudenkatu 36',   lat: 62.2425, lng: 25.7395 },
  lounaispuisto: { name: 'Lounaispuisto',             address: 'Lounaispuisto',        lat: 62.2395, lng: 25.7410 },
  various:      { name: 'Useita paikkoja',           address: 'Jyväskylä',            lat: 62.2430, lng: 25.7480 },
};

const CATEGORIES = {
  /* ── Site-tapahtumat ── */
  'site-monthly': { emoji: '🏢', fi: 'Site Monthly',        en: 'Site Monthly',        color: '#0891b2', type: 'site' },
  'ai-club':      { emoji: '🤖', fi: 'AI Club',             en: 'AI Club',             color: '#7c3aed', type: 'site' },
  'social':       { emoji: '🍻', fi: 'Perjantai-social',    en: 'Friday Social',       color: '#f59e0b', type: 'site' },
  'tech-talk':    { emoji: '🔧', fi: 'Tech Talk',           en: 'Tech Talk',           color: '#059669', type: 'site' },
  'lunch-learn':  { emoji: '🥗', fi: 'Lunch & Learn',       en: 'Lunch & Learn',       color: '#10b981', type: 'site' },
  'board-games':  { emoji: '🎲', fi: 'Lautapelit',          en: 'Board Games',         color: '#8b5cf6', type: 'site' },
  'coding-dojo':  { emoji: '💻', fi: 'Coding Dojo',         en: 'Coding Dojo',         color: '#3b82f6', type: 'site' },
  'wellbeing':    { emoji: '🧘', fi: 'Hyvinvointi',         en: 'Wellbeing',           color: '#ec4899', type: 'site' },
  'strategy':     { emoji: '📊', fi: 'Strategia',           en: 'Strategy',            color: '#6366f1', type: 'site' },
  'onboarding':   { emoji: '👋', fi: 'Perehdytys',          en: 'Onboarding',          color: '#14b8a6', type: 'site' },
  'special':      { emoji: '⭐', fi: 'Erikoistapahtuma',    en: 'Special Event',       color: '#f97316', type: 'site' },
  /* ── Kaupunkitapahtumat ── */
  'festival':     { emoji: '🎪', fi: 'Festivaali',          en: 'Festival',            color: '#e11d48', type: 'city' },
  'market':       { emoji: '🛍️', fi: 'Markkinat',           en: 'Market',              color: '#ca8a04', type: 'city' },
  'sports':       { emoji: '🏅', fi: 'Urheilu',             en: 'Sports',              color: '#16a34a', type: 'city' },
  'concert':      { emoji: '🎵', fi: 'Konsertti',           en: 'Concert',             color: '#9333ea', type: 'city' },
  'cultural':     { emoji: '🎭', fi: 'Kulttuuri',           en: 'Cultural',            color: '#0ea5e9', type: 'city' },
  'rally':        { emoji: '🏎️', fi: 'Ralli',               en: 'Rally / Motorsport',  color: '#dc2626', type: 'city' },
  'conference':   { emoji: '📋', fi: 'Konferenssi / Messut', en: 'Conference / Fair',   color: '#64748b', type: 'city' },
};

const TRAFFIC_LEVELS = {
  none:   { emoji: '⚪', fi: 'Ei vaikutusta',   en: 'No impact',   color: '#94a3b8' },
  low:    { emoji: '🟢', fi: 'Vähäinen',        en: 'Low',         color: '#22c55e' },
  medium: { emoji: '🟡', fi: 'Kohtalainen',     en: 'Medium',      color: '#eab308' },
  high:   { emoji: '🔴', fi: 'Merkittävä',      en: 'Significant', color: '#ef4444' },
};

/* ── Tapahtumagenerointi ── */
function generateEvents() {
  let id = 0;
  function ev(type, cat, tFi, tEn, date, end, time, dur, dFi, dEn, venue, traffic, url) {
    return { id: ++id, type, category: cat, title: { fi: tFi, en: tEn }, date, endDate: end, time, duration: dur,
      description: { fi: dFi, en: dEn }, venue, trafficImpact: traffic || 'none', url: url || null };
  }

  return [
    /* ═══════════════════════════════════════════
       SITE-TAPAHTUMAT (huhtikuu – kesäkuu 2026)
       ═══════════════════════════════════════════ */

    // ── Tänään: Tapio ja Tomi AI Tulevaisuus ──
    ev('site','special',
      'Tapio ja Tomi AI Tulevaisuus – keskustelusessio',
      'Tapio & Tomi AI Future – Discussion Session',
      '2026-04-16', null, '14:00', 120,
      'Tapion ja Tomin vapaamuotoinen keskustelusessio tekoälyn tulevaisuudesta. Miten generatiivinen AI muuttaa konsultointityötä? Tule kuuntelemaan ja keskustelemaan!',
      'An open discussion session on the future of AI with Tapio and Tomi. How will generative AI transform consulting? Join the conversation!',
      'siili', 'none'),

    // ── Site Monthly ──
    ev('site','site-monthly',
      'Site Monthly – Q2 Kick-off',
      'Site Monthly – Q2 Kick-off',
      '2026-04-30', null, '16:00', 120,
      'Q2-kauden avaus. Katsaus meneillään oleviin projekteihin ja tuleviin mahdollisuuksiin. Tarjolla pientä purtavaa.',
      'Q2 kick-off. Overview of ongoing projects and upcoming opportunities. Snacks provided.',
      'siili', 'none'),
    ev('site','site-monthly',
      'Site Monthly',
      'Site Monthly',
      '2026-05-28', null, '16:00', 90,
      'Kuukauden kuulumiset ja ajankohtaiset asiat. Projekti-spotlight: meneillään olevat AI-hankkeet.',
      'Monthly updates and current topics. Project spotlight: ongoing AI initiatives.',
      'siili', 'none'),
    ev('site','site-monthly',
      'Site Monthly – Kesäkauden päätös',
      'Site Monthly – Summer Season Wrap-up',
      '2026-06-25', null, '16:00', 120,
      'Kesäkauden päätöstilaisuus. H1-katsaus, kesälomajärjestelyt ja syksyn suunnitelmat. Grillaus terassilla!',
      'Summer season closing. H1 review, summer holiday arrangements, and autumn plans. BBQ on the terrace!',
      'siili', 'none'),

    // ── AI Club (joka toinen keskiviikko) ──
    ev('site','ai-club',
      'AI Club: LLM Agents & Tool Use',
      'AI Club: LLM Agents & Tool Use',
      '2026-04-22', null, '15:00', 90,
      'Syvennytään LLM-agenttien maailmaan: miten agentit käyttävät työkaluja ja tekevät päätöksiä. Demoja ja keskustelua.',
      'Deep dive into LLM agents: how agents use tools and make decisions. Demos and discussion.',
      'siili', 'none'),
    ev('site','ai-club',
      'AI Club: RAG-arkkitehtuurit',
      'AI Club: RAG Architectures',
      '2026-05-06', null, '15:00', 90,
      'Retrieval-Augmented Generation käytännössä. Vertailussa eri RAG-patternt ja vektoritietokannat.',
      'Retrieval-Augmented Generation in practice. Comparing RAG patterns and vector databases.',
      'siili', 'none'),
    ev('site','ai-club',
      'AI Club: Multimodaaliset mallit',
      'AI Club: Multimodal Models',
      '2026-05-20', null, '15:00', 90,
      'Kuva, ääni ja teksti yhdessä mallissa. Mitä mahdollisuuksia multimodaalisuus avaa asiakasprojekteissa?',
      'Image, audio, and text in one model. What opportunities does multimodality open for client projects?',
      'siili', 'none'),
    ev('site','ai-club',
      'AI Club: AI-testaus ja laadunvarmistus',
      'AI Club: AI Testing & Quality Assurance',
      '2026-06-03', null, '15:00', 90,
      'Miten testataan AI-sovelluksia? Evaluaatioframeworkit, benchmark-setit ja jatkuva monitorointi.',
      'How to test AI applications? Evaluation frameworks, benchmark sets, and continuous monitoring.',
      'siili', 'none'),
    ev('site','ai-club',
      'AI Club: Edge AI ja on-device mallit',
      'AI Club: Edge AI & On-device Models',
      '2026-06-17', null, '15:00', 90,
      'AI reunalaskennassa: mobiilimallit, optimointi ja käytännön haasteet. Esittelyssä ONNX ja TensorFlow Lite.',
      'AI at the edge: mobile models, optimization, and practical challenges. Featuring ONNX and TensorFlow Lite.',
      'siili', 'none'),

    // ── Friday Social ──
    ev('site','social',
      'Friday Social: Kevätkauden avaus',
      'Friday Social: Spring Season Opening',
      '2026-04-24', null, '16:00', 180,
      'Kevään ensimmäinen Friday Social! Rentoa yhdessäoloa, naposteltavaa ja juotavaa. Aiheena kevään projektikuulumiset.',
      'First Friday Social of spring! Casual hangout with snacks and drinks. Discussing spring project updates.',
      'siili', 'none'),
    ev('site','social',
      'Friday Social',
      'Friday Social',
      '2026-05-29', null, '16:00', 180,
      'Kuukauden päätös rentoa seuraa ja keskustelua. Lautapelien ystävät mukaan – tuodaan pelit esiin!',
      'End-of-month casual social and conversation. Board game fans welcome – bringing out the games!',
      'siili', 'none'),
    ev('site','social',
      'Friday Social: Kesäjuhlat',
      'Friday Social: Summer Party',
      '2026-06-26', null, '16:00', 240,
      'Kesän suurin Friday Social! Grillaus terassilla järvenrannassa. Koko porukka paikalle!',
      'Biggest Friday Social of summer! BBQ on the terrace by the lake. Everyone welcome!',
      'siili', 'none'),

    // ── Tech Talk ──
    ev('site','tech-talk',
      'Tech Talk: Kubernetes tuotannossa',
      'Tech Talk: Kubernetes in Production',
      '2026-04-14', null, '14:00', 60,
      'Kokemuksia K8s-klusterien operoinnista tuotannossa. Skaalaus, monitorointi ja vianhaku.',
      'Experiences operating K8s clusters in production. Scaling, monitoring, and troubleshooting.',
      'siili', 'none'),
    ev('site','tech-talk',
      'Tech Talk: Rust web-kehityksessä',
      'Tech Talk: Rust in Web Development',
      '2026-05-12', null, '14:00', 60,
      'Axum, Actix ja Rocket vertailussa. Miksi Rust web-backendinä ja miten pääsee alkuun?',
      'Comparing Axum, Actix, and Rocket. Why Rust for web backends and how to get started?',
      'siili', 'none'),
    ev('site','tech-talk',
      'Tech Talk: Platform Engineering',
      'Tech Talk: Platform Engineering',
      '2026-06-09', null, '14:00', 60,
      'Mitä platform engineering tarkoittaa käytännössä? Internal Developer Platformit ja Developer Experience.',
      'What does platform engineering mean in practice? Internal Developer Platforms and Developer Experience.',
      'siili', 'none'),

    // ── Lunch & Learn ──
    ev('site','lunch-learn',
      'Lunch & Learn: Design Systems',
      'Lunch & Learn: Design Systems',
      '2026-04-23', null, '11:30', 60,
      'Design systemien rakentaminen ja ylläpito. Miten yhtenäistää UI/UX eri projektien välillä?',
      'Building and maintaining design systems. How to unify UI/UX across projects?',
      'siili', 'none'),
    ev('site','lunch-learn',
      'Lunch & Learn: Saavutettavuus',
      'Lunch & Learn: Accessibility',
      '2026-05-14', null, '11:30', 60,
      'EU:n saavutettavuusdirektiivi ja WCAG 2.2 käytännössä. Mitä jokaisen kehittäjän tulee tietää?',
      'EU Accessibility Directive and WCAG 2.2 in practice. What every developer needs to know?',
      'siili', 'none'),
    ev('site','lunch-learn',
      'Lunch & Learn: Green Coding',
      'Lunch & Learn: Green Coding',
      '2026-06-04', null, '11:30', 60,
      'Kestävä ohjelmistokehitys: energiatehokas koodi, vihreä hosting ja hiilijalanjäljen mittaaminen.',
      'Sustainable software development: energy-efficient code, green hosting, and carbon footprint measurement.',
      'siili', 'none'),

    // ── Board Games ──
    ev('site','board-games',
      'Lautapeli-ilta',
      'Board Game Night',
      '2026-04-06', null, '17:00', 180,
      'Kuukauden ensimmäisen maanantain lautapeli-ilta. Tällä kertaa uudet strategiapelit testissä!',
      'First Monday board game night. This time testing new strategy games!',
      'siili', 'none'),
    ev('site','board-games',
      'Lautapeli-ilta',
      'Board Game Night',
      '2026-05-04', null, '17:00', 180,
      'Toukokuun lautapeli-ilta. Tuokaa omia pelejä tai pelatkaa toimiston kokoelmalla!',
      'May board game night. Bring your own games or play from the office collection!',
      'siili', 'none'),
    ev('site','board-games',
      'Lautapeli-ilta',
      'Board Game Night',
      '2026-06-01', null, '17:00', 180,
      'Kesäkuun lautapeli-ilta. Kevytpelejä terassilla säiden salliessa!',
      'June board game night. Light games on the terrace if weather permits!',
      'siili', 'none'),

    // ── Coding Dojo ──
    ev('site','coding-dojo',
      'Coding Dojo: TDD-patternit',
      'Coding Dojo: TDD Patterns',
      '2026-04-21', null, '15:00', 120,
      'Pair programming -session: TDD-patternit ja testivetoinen kehitys käytännössä.',
      'Pair programming session: TDD patterns and test-driven development in practice.',
      'siili', 'none'),
    ev('site','coding-dojo',
      'Coding Dojo: Funktionaalinen ohjelmointi',
      'Coding Dojo: Functional Programming',
      '2026-05-19', null, '15:00', 120,
      'FP-konseptit Scalan ja TypeScriptin kautta. Map, filter, reduce ja monadi demystifioituna.',
      'FP concepts through Scala and TypeScript. Map, filter, reduce, and monads demystified.',
      'siili', 'none'),
    ev('site','coding-dojo',
      'Coding Dojo: System Design',
      'Coding Dojo: System Design',
      '2026-06-16', null, '15:00', 120,
      'Suunnitellaan yhdessä skaalautuva järjestelmä whiteboard-harjoituksena. Haastattelutekniikka ja arkkitehtuurivalinnat.',
      'Collaborative scalable system design as a whiteboard exercise. Interview technique and architecture decisions.',
      'siili', 'none'),

    // ── Wellbeing ──
    ev('site','wellbeing',
      'Hyvinvointipäivä: Ergonomia & taukoliikunta',
      'Wellbeing Day: Ergonomics & Breaks',
      '2026-05-07', null, '10:00', 180,
      'Ergonomiakonsultti paikalla klo 10–13. Työpisteen säätö, taukoliikuntavinkit ja niska-hartia-jumppa.',
      'Ergonomics consultant on-site 10-13. Workstation adjustment, exercise break tips, and neck-shoulder exercises.',
      'siili', 'none'),
    ev('site','wellbeing',
      'Hyvinvointipäivä: Kesäkuntoon',
      'Wellbeing Day: Summer Shape',
      '2026-06-11', null, '10:00', 180,
      'Kevyt aamujumppa, smoothie-baari ja mindfulness-hetki. Hyvä startti kesäkuntokauteen!',
      'Light morning exercise, smoothie bar, and mindfulness moment. Great start to summer fitness!',
      'siili', 'none'),

    // ── Strategy ──
    ev('site','strategy',
      'Q2 Strategy Update',
      'Q2 Strategy Update',
      '2026-04-17', null, '14:00', 90,
      'Johdon Q2-katsaus: kasvustrategia, uudet asiakkuudet ja AI-palveluiden roadmap.',
      'Management Q2 review: growth strategy, new accounts, and AI services roadmap.',
      'siili', 'none'),
    ev('site','strategy',
      'Mid-year Review',
      'Mid-year Review',
      '2026-06-18', null, '14:00', 90,
      'H1-tulosten läpikäynti ja H2-suunnitelmat. Mitä opimme ja mihin panostamme jatkossa?',
      'H1 results review and H2 plans. What did we learn and where to invest next?',
      'siili', 'none'),

    // ── Onboarding ──
    ev('site','onboarding',
      'Perehdytyspäivä',
      'Onboarding Day',
      '2026-04-20', null, '09:00', 480,
      'Uusien siiläisten perehdytyspäivä. Toimiston esittely, työkalut, prosessit ja lounas yhdessä.',
      'Onboarding day for new Siili members. Office tour, tools, processes, and lunch together.',
      'siili', 'none'),
    ev('site','onboarding',
      'Perehdytyspäivä',
      'Onboarding Day',
      '2026-05-18', null, '09:00', 480,
      'Toukokuun uudet tulijat! Tervetuloa Siilin Jyväskylän toimistolle.',
      'May newcomers! Welcome to Siili Jyväskylä office.',
      'siili', 'none'),
    ev('site','onboarding',
      'Perehdytyspäivä',
      'Onboarding Day',
      '2026-06-15', null, '09:00', 480,
      'Kesäkuun perehdytys. Kesätyöntekijät ja harjoittelijat mukaan!',
      'June onboarding. Summer workers and interns welcome!',
      'siili', 'none'),

    // ── Special ──
    ev('site','special',
      'Kevätjuhlat',
      'Spring Celebration',
      '2026-05-15', null, '17:00', 240,
      'Siilin Jyväskylän toimiston kevätjuhlat! Illallinen, puheita ja karaokea. Ohjelmaa klo 17 alkaen.',
      'Siili Jyväskylä office spring celebration! Dinner, speeches, and karaoke. Program from 17:00.',
      'siili', 'none'),
    ev('site','special',
      'Kesän avajaiset – grillaus',
      'Summer Opening – BBQ',
      '2026-06-12', null, '16:00', 240,
      'Kesäkauden avajaisgrillaus terassilla! Perinteinen makkaranpaisto ja kesäjuomat järvenrannassa.',
      'Summer opening BBQ on the terrace! Traditional grilling and summer drinks by the lake.',
      'siili', 'none'),

    /* ═══════════════════════════════════════════
       KAUPUNKITAPAHTUMAT (huhtikuu – kesäkuu 2026)
       ═══════════════════════════════════════════ */

    // ── HUHTIKUU ──
    ev('city','conference',
      'Jyväskylän Hyvinvointimessut & Crafts Fair',
      'Jyväskylä Wellness Fair & Crafts Fair',
      '2026-04-11', '2026-04-12', '10:00', 480,
      'Hyvinvointi- ja käsityömessut Paviljongissa. Satoja näytteilleasettajia. Lisää liikennettä Lutakon alueella.',
      'Wellness and crafts trade fair at Paviljonki. Hundreds of exhibitors. Increased traffic in Lutakko area.',
      'paviljonki', 'medium',
      'https://www.paviljonki.fi/tapahtuma/jyvaskylan-hyvinvointimessut/'),

    ev('city','conference',
      'Digiturvallisuusmessut',
      'Digital Security Expo',
      '2026-04-16', null, '09:00', 480,
      'Tietoturva- ja kyberturvallisuusmessut Paviljongissa koko päivän. Näytteilleasettajia kalustoineen ja satoja kävijöitä. Paviljongin parkkipaikat täyttyvät aamusta – vaikuttaa suoraan Lutakonaukion pysäköintiin ja liikenteeseen Siili-toimiston edessä. Illalla samassa paikassa teatteriproduktioita → parkkipaikat varattu koko päivän.',
      'Full-day cybersecurity and digital security expo at Paviljonki. Exhibitors with equipment and hundreds of visitors. Paviljonki parking fills up from morning – directly affects parking and traffic at Lutakonaukio in front of Siili office. Theatre productions at the same venue in the evening → parking occupied all day.',
      'paviljonki', 'medium',
      'https://www.paviljonki.fi/en/messut/digital-security/'),

    ev('city','cultural',
      'Teatteriproduktiot Paviljongissa',
      'Theatre Productions at Paviljonki',
      '2026-04-16', '2026-04-18', '19:00', 150,
      'Jyväskylän kaupunginteatterin produktioita Paviljongissa: Lou Salome, Viettelyksen vaunu, Seitsemän veljestä. Ke 16.4. samanaikaisesti Digiturvallisuusmessujen kanssa – lisää liikennettä ja parkkipaikkapulaa Lutakon alueella iltapäivällä.',
      'City theatre productions at Paviljonki: Lou Salome, Viettelyksen vaunu, Seven Brothers. Wed Apr 16 concurrent with Digital Security Expo – additional traffic and parking pressure in Lutakko area in the afternoon.',
      'paviljonki', 'medium',
      'https://www.lippu.fi/artist/jyvaeskylaen-kaupunginteatteri/'),

    ev('city','concert',
      'TubeTrio-kiertue',
      'TubeTrio Tour',
      '2026-04-18', null, '18:00', 150,
      'Juhoflow, Satuseta & Tiia Weckström viihdeshown Paviljongissa. Koko perheen tapahtuma.',
      'Juhoflow, Satuseta & Tiia Weckström entertainment show at Paviljonki. Family event.',
      'paviljonki', 'low',
      'https://www.paviljonki.fi/tapahtuma/juhoflow-satuseta-tiia-weckstrom-tubetrio-kiertue/'),

    ev('city','concert',
      'Rajaton sings Bee Gees – Jyväskylä Sinfonia',
      'Rajaton Sings Bee Gees – Jyväskylä Sinfonia',
      '2026-04-22', '2026-04-23', '19:00', 120,
      'Rajaton ja Jyväskylä Sinfonia esittävät Bee Gees -klassikoita Paviljongissa. Kaksi esitystä.',
      'Rajaton and Jyväskylä Sinfonia perform Bee Gees classics at Paviljonki. Two performances.',
      'paviljonki', 'medium',
      'https://www.jyvaskylasinfonia.fi/konsertit/rajaton-sings-bee-gees'),

    ev('city','concert',
      'Ilmavoimien Big Band: Cannonball Lives!!',
      'Air Force Big Band: Cannonball Lives!!',
      '2026-04-24', null, '19:00', 120,
      'Ilmavoimien Big Bandin jazz-konsertti Paviljongissa.',
      'Finnish Air Force Big Band jazz concert at Paviljonki.',
      'paviljonki', 'low',
      'https://www.lippu.fi/artist/ilmavoimien-big-band/'),

    ev('city','cultural',
      'Tanssin päivän näytös',
      'Dance Day Performance',
      '2026-04-25', null, '14:00', 120,
      'Kansainvälisen tanssin päivän juhlanäytös Paviljongissa. Eri tanssityylejä ja esityksiä.',
      'International Dance Day celebration at Paviljonki. Various dance styles and performances.',
      'paviljonki', 'low',
      'https://www.paviljonki.fi/tapahtuma/tanssin-paivan-naytos/'),

    ev('city','festival',
      'Suomen Tivoli',
      'Finnish Funfair',
      '2026-04-30', '2026-05-24', '12:00', 600,
      'Suomen Tivoli Killerin alueella. Huvipuistolaitteet ja karkkikojut. Sijainti kaukana keskustasta – vähäinen liikennevaikutus.',
      'Finnish Funfair at Killeri. Rides and candy stalls. Located far from center – minimal traffic impact.',
      'killeri', 'low',
      'https://www.suomentivoli.fi/'),

    // ── TOUKOKUU ──
    ev('city','sports',
      'Talent Cup 2026',
      'Talent Cup 2026',
      '2026-05-02', '2026-05-03', '09:00', 600,
      'Nuorten urheilukilpailu useilla lajeilla eri puolilla Jyväskylää.',
      'Youth sports competition across multiple disciplines at various Jyväskylä venues.',
      'various', 'low',
      'https://talentcup.torneopal.fi/'),

    ev('city','conference',
      'KuljetusAreena',
      'Transport Arena',
      '2026-05-05', null, '09:00', 480,
      'Kuljetusalan ammattimessut Paviljongissa. Raskas kalusto esillä – lisää liikennettä Messukadun alueella.',
      'Transport industry trade fair at Paviljonki. Heavy vehicles on display – increased traffic around Messukatu.',
      'paviljonki', 'medium',
      'https://www.paviljonki.fi/en/messut/kuljetusareena-2/'),

    ev('city','concert',
      'Jyväskylä Sinfonia: Myrskyluodolta Napapiirille',
      'Jyväskylä Sinfonia: From Storm Islet to Arctic Circle',
      '2026-05-06', null, '19:00', 120,
      'Jyväskylä Sinfoniaorkesterin konsertti Paviljongissa.',
      'Jyväskylä Symphony Orchestra concert at Paviljonki.',
      'paviljonki', 'low',
      'https://www.jyvaskylasinfonia.fi/konsertit/myrskyluodolta-napapiirille'),

    ev('city','sports',
      'Lauri Markkanen Tournament',
      'Lauri Markkanen Tournament',
      '2026-05-08', '2026-05-10', '09:00', 600,
      'Koripallon huipputurnaus useissa halleissa. NBA-tähti Lauri Markkasen nimikkoturnaus tuo satoja pelaajia ja perheitä. Kohtalainen liikennevaikutus.',
      'Top basketball tournament at multiple halls. NBA star Lauri Markkanen\'s namesake tournament brings hundreds of players and families. Moderate traffic impact.',
      'various', 'medium',
      'https://lmtlogin.torneopal.fi/'),

    ev('city','concert',
      'Jyväskylä Sinfonia: Atte & Elina',
      'Jyväskylä Sinfonia: Atte & Elina',
      '2026-05-13', null, '19:00', 120,
      'Atte Kilpinen ja Elina Nechayeva esiintyvät Jyväskylä Sinfoniaorkesterin kanssa.',
      'Atte Kilpinen and Elina Nechayeva perform with Jyväskylä Symphony Orchestra.',
      'paviljonki', 'low',
      'https://www.jyvaskylasinfonia.fi/konsertit/atte-elina'),

    ev('city','market',
      'Hela-markkinat (kauppatorimarkkinat)',
      'Hela Market (Town Square Market)',
      '2026-05-14', null, '08:00', 600,
      'Perinteiset Hela-markkinat Kauppatorilla. Kymmeniä kojuja ja myyjiä. Lähialueen parkkipaikat täynnä aamusta alkaen.',
      'Traditional Hela market at the Town Square. Dozens of stalls and vendors. Nearby parking fills up from morning.',
      'kauppatori', 'medium',
      'https://kalenteri.jyvaskyla.fi/'),

    ev('city','festival',
      'Yläkaupungin Yö',
      'Upper Town Night',
      '2026-05-15', '2026-05-16', '17:00', 480,
      '⚠️ SUURI TAPAHTUMA: 262 ohjelmapistettä 48 paikassa ympäri keskustaa! Musiikkia, teatteria, tanssia, sirkusta ja taidetta. Merkittävä liikennevaikutus koko keskustassa – tiekatkoja ja parkkipaikkaruuhkaa. Suositus: julkinen liikenne tai pyörä.',
      '⚠️ MAJOR EVENT: 262 program items at 48 venues across the city center! Music, theatre, dance, circus, and art. Significant traffic impact across the entire center – road closures and parking congestion. Recommendation: public transport or bicycle.',
      'various', 'high',
      'https://www.ylakaupunginyo.fi/'),

    ev('city','concert',
      'PETRUS – LAULUNI',
      'PETRUS – My Songs',
      '2026-05-15', null, '19:00', 150,
      'Petrus Schroderus -konsertti Paviljongissa. Samanaikaisesti Yläkaupungin Yön kanssa.',
      'Petrus Schroderus concert at Paviljonki. Concurrent with Upper Town Night.',
      'paviljonki', 'medium',
      'https://www.lippu.fi/artist/petrus-schroderus/'),

    ev('city','concert',
      'Christoffer Strandberg – standup',
      'Christoffer Strandberg – Stand-up',
      '2026-05-16', null, '19:00', 120,
      'Christoffer Strandbergin standup-show Paviljongissa.',
      'Christoffer Strandberg stand-up show at Paviljonki.',
      'paviljonki', 'low',
      'https://www.paviljonki.fi/tapahtuma/christoffer-strandberg-kansanmies-k18/'),

    // ── KESÄKUU ──
    ev('city','market',
      'Jyväskylän Kansainväliset Suurmarkkinat',
      'Jyväskylä International Grand Market',
      '2026-06-04', '2026-06-07', '10:00', 600,
      '⚠️ SUURI TAPAHTUMA LUTAKONAUKIOLLA: Yrittäjiä yli 30 maasta myymässä erikoistuotteita ja ruokaa. To–la 10–20, su 10–18. Koko Lutakonaukio varattu – merkittävä vaikutus toimiston läheisyyteen, parkkipaikoille ja liikenteeseen. HUOM: Siili-toimisto Lutakonaukio 1:ssä on tapahtuma-alueen vieressä!',
      '⚠️ MAJOR EVENT AT LUTAKONAUKIO: Entrepreneurs from 30+ countries selling specialty products and food. Thu-Sat 10-20, Sun 10-18. Entire Lutakonaukio reserved – significant impact on office proximity, parking, and traffic. NOTE: Siili office at Lutakonaukio 1 is right next to the event area!',
      'lutakonaukio', 'high',
      'https://www.eurooppamarkkinat.fi/jyvaskyla/'),

    ev('city','conference',
      'Kokoomuksen puoluekokous',
      'National Coalition Party Congress',
      '2026-06-05', '2026-06-07', '09:00', 600,
      'Kansallisen Kokoomuksen puoluekokous Paviljongissa. Satoja delegaatteja ympäri Suomea. Hotellit täynnä ja liikenne vilkasta.',
      'National Coalition Party congress at Paviljonki. Hundreds of delegates from across Finland. Hotels full and traffic busy.',
      'paviljonki', 'medium',
      'https://www.kokoomus.fi/vaikuta/puoluekokous/'),

    ev('city','cultural',
      'Sauna Region Week',
      'Sauna Region Week',
      '2026-06-06', '2026-06-14', '10:00', 480,
      'Saunaviikko Jyväskylän seudulla. Erilaisia saunatapahtumia useissa paikoissa. Hajautettu tapahtuma – vähäinen yksittäinen liikennevaikutus.',
      'Sauna week in the Jyväskylä region. Various sauna events at multiple locations. Distributed event – minimal individual traffic impact.',
      'various', 'low',
      'https://visitjyvaskyla.fi/en/saunaregionweek/'),

    ev('city','festival',
      'OlutSatama (Beer Harbor Festival)',
      'OlutSatama (Beer Harbor Festival)',
      '2026-06-11', '2026-06-13', '17:00', 420,
      '⚠️ SUURI TAPAHTUMA LUTAKONAUKIOLLA: 10-vuotisjuhlat! Olutfestivaali satama-alueen asfalttikentällä. To 17–23, pe 15–02, la 14–02. Historiallisesti yli 49 000 kävijää! Sisäänkäynti Paviljongin puolelta. MERKITTÄVÄ liikennevaikutus koko Lutakon alueella – myös illalla ja yöllä. Parkkipaikat täyteen hyvissä ajoin.',
      '⚠️ MAJOR EVENT AT LUTAKONAUKIO: 10th anniversary! Beer festival on the harbour asphalt field. Thu 17-23, Fri 15-02, Sat 14-02. Historically 49,000+ visitors! Entrance via Paviljonki side. SIGNIFICANT traffic impact across the entire Lutakko area – including evenings and nights. Parking fills up well in advance.',
      'lutakonaukio', 'high',
      'https://www.olutsatama.fi/'),

    ev('city','rally',
      'SM Jyväskylä Ralli',
      'Finnish Rally Championship – Jyväskylä Rally',
      '2026-06-12', '2026-06-13', '08:00', 720,
      '⚠️ KRIITTINEN TAPAHTUMA: Rallin SM-osakilpailu keskustassa! Erikoiskokeet lähialueilla ja huoltoalue Paviljongin luona. Ensimmäistä kertaa kesätapahtumana Jyväskylässä. TIENKATKOJA läpi viikonlopun! Samanaikaisesti OlutSataman kanssa → ÄÄRIMMÄINEN ruuhka Lutakon alueella. Suositus: etätyö tai julkinen liikenne pe–la.',
      '⚠️ CRITICAL EVENT: Rally Championship round in the city center! Special stages nearby and service park at Paviljonki. First-ever summer rally in Jyväskylä. ROAD CLOSURES throughout the weekend! Concurrent with OlutSatama → EXTREME congestion in Lutakko area. Recommendation: remote work or public transport Fri-Sat.',
      'paviljonki', 'high',
      'https://www.rallism.fi/'),

    ev('city','sports',
      'Cheerleading SM-kilpailut',
      'Finnish Cheerleading Championships',
      '2026-06-13', '2026-06-14', '09:00', 600,
      'Cheerleadingin SM-kilpailut Paviljongissa. Joukkueita ja katsojia ympäri Suomea. Lisää ruuhkaa jo valmiiksi täydelle Lutakon alueelle (ralli + OlutSatama).',
      'Finnish Cheerleading Championships at Paviljonki. Teams and spectators from across Finland. Adds to already congested Lutakko area (rally + OlutSatama).',
      'paviljonki', 'medium',
      'https://www.scl.fi/tapahtumakalenteri/tapahtuma/sm-2026/'),

    ev('city','concert',
      'Gettomasa-konsertti',
      'Gettomasa Concert',
      '2026-06-13', null, '19:00', 180,
      'Gettomasan konsertti Hippoksen pesäpallostadionilla.',
      'Gettomasa concert at Hippos baseball stadium.',
      'hippos', 'low',
      'https://www.lippu.fi/event/gettomasa-hippoksen-pesapallostadion-21123897/'),

    ev('city','conference',
      'BUS 2026 -näyttely',
      'BUS 2026 Exhibition',
      '2026-06-16', '2026-06-17', '09:00', 480,
      'Linja-autoalan ammattinäyttely Paviljongissa. Isoja ajoneuvoja esillä Messukadun alueella.',
      'Bus industry professional exhibition at Paviljonki. Large vehicles on display around Messukatu.',
      'paviljonki', 'medium',
      'https://www.paviljonki.fi/tapahtuma/bus-2026-nayttely/'),

    ev('city','sports',
      'Kansainvälinen koiranäyttely',
      'International Dog Show',
      '2026-06-20', '2026-06-21', '08:00', 600,
      'Kansainvälinen koiranäyttely Killerin alueella. Kaukana keskustasta – vähäinen vaikutus toimistoalueelle.',
      'International Dog Show at Killeri. Far from center – minimal impact on office area.',
      'killeri', 'low',
      'https://www.jkldogshow.com/'),

    ev('city','cultural',
      'Jyväskylä Knit Festival',
      'Jyväskylä Knit Festival',
      '2026-06-25', '2026-06-28', '10:00', 480,
      'Neulefestivaali Toivolan Vanhassa Pihassa. Workshopeja, näyttelyitä ja myyntikojuja. Pieni tapahtuma keskustassa.',
      'Knitting festival at Toivolan Vanha Piha. Workshops, exhibitions, and sales stalls. Small event in the center.',
      'toivola', 'low',
      'https://jyvaskylaknitfest.com/'),

    ev('city','sports',
      'HeinäCup',
      'HeinäCup',
      '2026-06-26', '2026-06-28', '08:00', 720,
      'Suuri nuorten jalkapalloturnaus eri kentillä ympäri Jyväskylää. Satoja joukkueita ja tuhansia pelaajia. Kohtalainen hajautettu liikennevaikutus.',
      'Large youth football tournament at various fields around Jyväskylä. Hundreds of teams and thousands of players. Moderate distributed traffic impact.',
      'various', 'medium',
      'https://www.heinacup.fi/'),

  ].sort((a, b) => a.date.localeCompare(b.date) || a.time.localeCompare(b.time));
}

/* ── i18n ── */
const i18n = {
  fi: {
    appTitle: 'Siili Jyväskylä',
    appSubtitle: 'Tapahtumat & Kalenteri',
    tabCalendar: 'Kalenteri',
    tabMap: 'Kartta',
    tabEvents: 'Tapahtumat',
    tabAnalytics: 'Analytiikka',
    filterAll: 'Kaikki',
    filterSite: 'Toimisto',
    filterCity: 'Kaupunki',
    searchPlaceholder: 'Hae tapahtumia...',
    trafficAll: 'Kaikki',
    trafficLabel: 'Liikennevaikutus:',
    monthNames: ['Tammikuu','Helmikuu','Maaliskuu','Huhtikuu','Toukokuu','Kesäkuu','Heinäkuu','Elokuu','Syyskuu','Lokakuu','Marraskuu','Joulukuu'],
    dayNames: ['Ma','Ti','Ke','To','Pe','La','Su'],
    more: 'lisää',
    today: 'Tänään',
    noEvents: 'Ei tapahtumia valituilla kriteereillä.',
    eventDetails: 'Tapahtuman tiedot',
    close: 'Sulje',
    time: 'Aika',
    duration: 'Kesto',
    location: 'Paikka',
    category: 'Kategoria',
    trafficImpact: 'Liikennevaikutus',
    description: 'Kuvaus',
    openLink: 'Avaa linkki',
    addToCalendar: 'Lisää kalenteriin',
    downloadICS: 'Lataa .ics',
    downloadCSV: 'Lataa .csv',
    exportTitle: 'Vie tapahtumat',
    totalEvents: 'Tapahtumia yhteensä',
    siteEvents: 'Toimistotapahtumat',
    cityEvents: 'Kaupunkitapahtumat',
    highTraffic: 'Korkea liikennevaikutus',
    officeMarker: 'Siili Solutions Jyväskylä – Toimisto',
    mapLegend: 'Karttaselite',
    min: 'min',
    h: 'h',
    recurring: 'Toistuva',
    warning: 'Varoitus',
    trafficWarning: '⚠️ Merkittävä liikennevaikutus – harkitse etätyötä tai julkista liikennettä',
    byCategory: 'Kategorioittain',
    byMonth: 'Kuukausittain',
    byTraffic: 'Liikennevaikutuksittain',
    byVenue: 'Tapahtumapaikoittain',
    resetFilters: 'Nollaa suodattimet',
  },
  en: {
    appTitle: 'Siili Jyväskylä',
    appSubtitle: 'Events & Calendar',
    tabCalendar: 'Calendar',
    tabMap: 'Map',
    tabEvents: 'Events',
    tabAnalytics: 'Analytics',
    filterAll: 'All',
    filterSite: 'Office',
    filterCity: 'City',
    searchPlaceholder: 'Search events...',
    trafficAll: 'All',
    trafficLabel: 'Traffic impact:',
    monthNames: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    dayNames: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    more: 'more',
    today: 'Today',
    noEvents: 'No events matching selected criteria.',
    eventDetails: 'Event Details',
    close: 'Close',
    time: 'Time',
    duration: 'Duration',
    location: 'Location',
    category: 'Category',
    trafficImpact: 'Traffic Impact',
    description: 'Description',
    openLink: 'Open link',
    addToCalendar: 'Add to calendar',
    downloadICS: 'Download .ics',
    downloadCSV: 'Download .csv',
    exportTitle: 'Export events',
    totalEvents: 'Total events',
    siteEvents: 'Office events',
    cityEvents: 'City events',
    highTraffic: 'High traffic impact',
    officeMarker: 'Siili Solutions Jyväskylä – Office',
    mapLegend: 'Map Legend',
    min: 'min',
    h: 'h',
    recurring: 'Recurring',
    warning: 'Warning',
    trafficWarning: '⚠️ Significant traffic impact – consider remote work or public transport',
    byCategory: 'By Category',
    byMonth: 'By Month',
    byTraffic: 'By Traffic Impact',
    byVenue: 'By Venue',
    resetFilters: 'Reset filters',
  },
};
