// Auto-generated by scraper – 2026-04-16T07:13:29.909Z
// Do not edit manually
const MENUS = {
  "lastUpdated": "2026-04-16T07:13:29.909Z",
  "weekNumber": 16,
  "dateRange": "13.4.–17.4.2026",
  "menus": {
    "2": {
      "maanantai": [
        "Maa-artisokkakeitto L, GRunsas salaattipöytä, leipomon oma leipäkoriJälkkärimakea"
      ],
      "tiistai": [
        "Nuudeli-kanakeitto M,GRunsas salaattipöytä, leipomon oma leipäkori"
      ]
    },
    "3": {
      "tiistai": [
        "Lohiseljankaa",
        "Kasviskaalikääryleitä ja tervapuolukkaa",
        "Jauhelihapihviä ja paistettua sipulia"
      ],
      "keskiviikko": [
        "Peruna-purjokeittoa",
        "Paistettua kirjolohta ja tillivinegretteä",
        "Terva-BBQ porsaanribsiä ja coleslawia",
        "Riekonrintaa ja Viisauden viinikastia"
      ],
      "torstai": [
        "Floridanleikettä",
        "Paahdettua nieriää ja artisokka-perunamuusia"
      ],
      "perjantai": [
        "Yrteillä höystettyä kurpitsakeittoa",
        "Puna-ahventa ja vaaleaa herukkakastia",
        "Naudan petit tenderiä ja juustomoussea"
      ],
      "maanantai": [
        "Kermaista parsakaalikeittoa",
        "Ylikypsää naudan hanger steakia ja punaviinikastia"
      ]
    },
    "4": {
      "maanantai": [
        "Aurajuustobroileria",
        "Kanan paistileikettä (L,G), aurajuustokastiketta (L,G), röstiperunaa (L,G) ja paahdettuja kasviksia (L,G)",
        "Lihapyöryköitä ja choronkastiketta",
        "Lihapyöryköitä (L,G), choronkastiketta (L,G), perunamuusia (L,G) ja paahdettuja kasviksia (L,G)",
        "Crispy Chicken \\u0026 chili-mangokastiketta",
        "Crispy Chicken \\u0026 chili-mangokastiketta (L,G) , lohkoperunaa (VE,G) ja paahdettuja kasviksia (L,G). Lisäksi runsas salaattibuffet, vesi ja kahvi/tee."
      ],
      "tiistai": [
        "Lihapyöryköitä ja choronkastiketta",
        "Lihapyöryköitä (L,G), choronkastiketta (L,G), perunamuusia (L,G) ja paahdettuja kasviksia (L,G)",
        "Crispy Chicken \\u0026 chili-mangokastiketta",
        "Crispy Chicken \\u0026 chili-mangokastiketta (L,G) , lohkoperunaa (VE,G) ja paahdettuja kasviksia (L,G). Lisäksi runsas salaattibuffet, vesi ja kahvi/tee.",
        "Punaviini possua",
        "Ylikypsää possun kassleria (L,G), punaviinikastiketta (L,G), kermaperunaa (L,G) ja paahdettuja kasviksia (L,G)"
      ],
      "keskiviikko": [
        "Crispy Chicken \\u0026 chili-mangokastiketta",
        "Crispy Chicken \\u0026 chili-mangokastiketta (L,G) , lohkoperunaa (VE,G) ja paahdettuja kasviksia (L,G). Lisäksi runsas salaattibuffet, vesi ja kahvi/tee.",
        "Punaviini possua",
        "Ylikypsää possun kassleria (L,G), punaviinikastiketta (L,G), kermaperunaa (L,G) ja paahdettuja kasviksia (L,G)",
        "Burger Mesa",
        "Burger Mesa (L), burger- ja kasvispihvejä, cheddaria, ranskalaisia ja majoneesia. Lisäksi runsas salaattibuffet, vesi ja kahvi/tee."
      ],
      "torstai": [
        "Punaviini possua",
        "Ylikypsää possun kassleria (L,G), punaviinikastiketta (L,G), kermaperunaa (L,G) ja paahdettuja kasviksia (L,G)",
        "Burger Mesa",
        "Burger Mesa (L), burger- ja kasvispihvejä, cheddaria, ranskalaisia ja majoneesia. Lisäksi runsas salaattibuffet, vesi ja kahvi/tee.",
        "Broileria ja valkosipulisalsaa",
        "Kanan paistileikettä (L,G), valkosipulisalsaa (L,G), röstiperunaa (L,G) ja paahdettuja kasviksia (L,G)"
      ],
      "perjantai": [
        "Burger Mesa",
        "Burger Mesa (L), burger- ja kasvispihvejä, cheddaria, ranskalaisia ja majoneesia. Lisäksi runsas salaattibuffet, vesi ja kahvi/tee.",
        "Broileria ja valkosipulisalsaa",
        "Kanan paistileikettä (L,G), valkosipulisalsaa (L,G), röstiperunaa (L,G) ja paahdettuja kasviksia (L,G)",
        "Pippuriset lihapyörykät",
        "Lihapyöryköitä (L,G), pippurikastiketta (L,G), perunamuusia (L,G) ja paahdettuja kasviksia (L,G)"
      ]
    },
    "5": {
      "maanantai": [
        "Porkkanakeitto l g",
        "Katkarapuwok m g",
        "Kevyt, raikas ja täyttävä, nopean lounastajan valinta: Keitto + salaattipöytä + kahvi tai tee & pikkumakea 13,70 €",
        "Runsas ja herkullinen vaihtoehto, tällä jaksaa! Lounasannos + keitto + salaattipöytä + kahvi tai tee & pikkumakea 14,90 €"
      ],
      "tiistai": [
        "Kermainen savulohikeitto l g",
        "Tofubowl m g veg",
        "Kevyt, raikas ja täyttävä, nopean lounastajan valinta: Keitto + salaattipöytä + kahvi tai tee & pikkumakea 13,70 €",
        "Runsas ja herkullinen vaihtoehto, tällä jaksaa! Lounasannos + keitto + salaattipöytä + kahvi tai tee & pikkumakea 14,90 €"
      ],
      "keskiviikko": [
        "Tomaattikeitto l g",
        "Savulohi-Caesarsalaatti l pyydettäessä g",
        "Kevyt, raikas ja täyttävä, nopean lounastajan valinta: Keitto + salaattipöytä + kahvi tai tee & pikkumakea 13,70 €",
        "Runsas ja herkullinen vaihtoehto, tällä jaksaa! Lounasannos + keitto + salaattipöytä + kahvi tai tee & pikkumakea 14,90 €"
      ],
      "torstai": [
        "Feta-parsakaalikeitto l g",
        "Kanabowl m g",
        "Kevyt, raikas ja täyttävä, nopean lounastajan valinta: Keitto + salaattipöytä + kahvi tai tee & pikkumakea 13,70 €",
        "Runsas ja herkullinen vaihtoehto, tällä jaksaa! Lounasannos + keitto + salaattipöytä + kahvi tai tee & pikkumakea 14,90 €"
      ],
      "perjantai": [
        "Kevyt, raikas ja täyttävä, nopean lounastajan valinta: Keitto + salaattipöytä + kahvi tai tee & pikkumakea 13,70 €",
        "Runsas ja herkullinen vaihtoehto, tällä jaksaa! Lounasannos + keitto + salaattipöytä + kahvi tai tee & pikkumakea 14,90 €"
      ]
    },
    "7": {
      "torstai": [
        "16.04.Broileria lime-jalapenokastikkeessa L/M/G (alkuperämaa Suomi)",
        "Tomaattista uunimakkaraa L/G"
      ]
    },
    "8": {
      "maanantai": [
        "Kermaista lohi-seikeittoa",
        "Lihapullia, metsästäjänkastiketta ja perunamuussia",
        "Savuporo-koskenlaskijapastaa",
        "Kukkakaali-koskenlaskijapastaa",
        "(kasvisruoka lautasannoksena keittiöstä)"
      ],
      "tiistai": [
        "Kasvis-juustokeittoa",
        "(kasvisruoka lautasannoksena keittiöstä)"
      ],
      "keskiviikko": [
        "Peruna-fenkolikeittoa",
        "Marry me -kanaa",
        "Lasagnea",
        "Kikherne-porkkanapihvejä ja rakuunamajoneesia",
        "(kasvisruoka lautasannoksena keittiöstä)"
      ],
      "torstai": [
        "Kasvi-borssikeittoa",
        "Kananpojanpaistileikkeitä ja currymajoneesia",
        "Pasta carbonara",
        "Vegaanisia leikkeitä ja currymajoneesia (kasvisruoka lautasannoksena keittiöstä)"
      ],
      "perjantai": [
        "Kermaista metsäsienikeittoa",
        "Meksikolaisia kasvispihvejä ja jogurttikastiketta",
        "Täytettyä kananpojanrintaa ja Amerikan dippiä",
        "Härkää, tummaa pippurikastiketta ja kermaperunagratiinia",
        "Maissipihvejä ja Amerikan dippiä",
        "(kasvisruoka lautasannoksena keittiöstä)"
      ]
    },
    "9": {
      "perjantai": [
        "domain_name: \"houkutus.myshopify.com\",",
        "template: \"index\"",
        "checkout_button: [",
        "'[name=\"checkout\"]',",
        "'[href=\"/checkout\"]',",
        "'form[action=\"/checkout\"] input[type=\"submit\"]',",
        "'.checkout_button',",
        "'.Button--modal_checkout'",
        "cart_subtotal: [",
        "'#main-cart-footer .cart__ctas',"
      ]
    },
    "10": {
      "maanantai": [
        "Rapupastaa, parsaa & gremolataa",
        "Greek scrambled eggs, pitaleipää & tomaatti \"sås"
      ],
      "tiistai": [
        "Kanaa florentine, paahdettua perunaa & foccaciaa",
        "Pasta alla genovese, papua & parmesaania"
      ],
      "keskiviikko": [
        "Chimichurri fish tacos, bataattia & maissisalsaa",
        "Paprikarisottoa, marinoitua munakoisoa, tapenadea & chavrea vegan"
      ],
      "torstai": [
        "Lihapullasub, marinara \"sås\" & burrataa",
        "Paneer pakora, kookoskaalia & minttu-korianterichutney"
      ],
      "perjantai": [
        "Porchetta possunkylkirullaa, perunasalaattia & fenkolimajoneesia",
        "Aura-viikunasalaattia & hasselpähkinä-arancini"
      ]
    },
    "12": {
      "maanantai": [
        "Grillattua broileria timjamikastikkeella",
        "Grillattua broileria, tummaa timjamikastiketta, ranskalaisia perunoita ja raikasta salaattia",
        "Pasta bolognese",
        "Rosson keittiön täyteläistä bolognesekastiketta, pennepastaa ja rucolaa",
        "Friteerattua tofua",
        "Friteerattua tofua, täyteläistä BBQ-kastiketta, paahdettuja perunoita ja raikasta salaattia",
        "Kirjolohta ja creme-hollandaisekastiketta",
        "Paistettua kotimaista kirjolohta, creme-hollandaisekastiketta, perunamuusia, raikasta salaattia, kevätsipulia ja sitruunaa",
        "Lounaspizza kolmella täytteellä",
        "Lounassalaatti",
        "Pannupihvi kermaisella sipulikastikkeella"
      ],
      "tiistai": [
        "Pannupihvi kermaisella sipulikastikkeella",
        "Mehevä naudan pannupihvi, kermaista sipulikastiketta, perunamuusia, suolakurkkua ja puolukkaa",
        "Pasta bolognese",
        "Rosson keittiön täyteläistä bolognesekastiketta, pennepastaa ja rucolaa",
        "Friteerattua tofua",
        "Friteerattua tofua, täyteläistä BBQ-kastiketta, paahdettuja perunoita ja raikasta salaattia",
        "Kirjolohta ja creme-hollandaisekastiketta",
        "Paistettua kotimaista kirjolohta, creme-hollandaisekastiketta, perunamuusia, raikasta salaattia, kevätsipulia ja sitruunaa",
        "Lounaspizza kolmella täytteellä",
        "Lounassalaatti",
        "Grillattua porsaan ulkofileetä"
      ],
      "keskiviikko": [
        "Grillattua porsaan ulkofileetä",
        "Grillattu porsaan ulkofileepihvi, Rosson kermaista pippurikastiketta, ranskalaisia perunoita ja raikasta salaattia",
        "Broileri-pestopasta",
        "Kermaisessa kastikkeessa broileria, tuoretta pinaattia, pikkelöityä punasipulia, pestoa, pennepastaa ja rucolaa",
        "Vege volognesepasta",
        "Rosson keittiön maukasta volognesekastiketta, pennepastaa ja rucolaa",
        "Kirjolohta ja creme-hollandaisekastiketta",
        "Paistettua kotimaista kirjolohta, creme-hollandaisekastiketta, perunamuusia, raikasta salaattia, kevätsipulia ja sitruunaa",
        "Lounaspizza kolmella täytteellä",
        "Lounassalaatti",
        "Grillattua broileria BBQ-kastikkeella"
      ],
      "torstai": [
        "Grillattua broileria BBQ-kastikkeella",
        "Grillattua broileria, Rosson herkullista BBQ-kastiketta, rapeaksi paahdettua perunaa ja raikasta salaattia",
        "Broileri-pestopasta",
        "Kermaisessa kastikkeessa broileria, tuoretta pinaattia, pikkelöityä punasipulia, pestoa, pennepastaa ja rucolaa",
        "Vege volognesepasta",
        "Rosson keittiön maukasta volognesekastiketta, pennepastaa ja rucolaa",
        "Kirjolohta ja creme-hollandaisekastiketta",
        "Paistettua kotimaista kirjolohta, creme-hollandaisekastiketta, perunamuusia, raikasta salaattia, kevätsipulia ja sitruunaa",
        "Lounaspizza kolmella täytteellä",
        "Lounassalaatti",
        "Porsaanleike Aura-cremellä"
      ],
      "perjantai": [
        "Porsaanleike Aura-cremellä",
        "Rapeaksi paistettu porsaanleike, Aura-juusto-cremeä, ranskalaisia perunoita ja raikasta salaattia",
        "Broileri-pestopasta",
        "Kermaisessa kastikkeessa broileria, tuoretta pinaattia, pikkelöityä punasipulia, pestoa, pennepastaa ja rucolaa",
        "Vege volognesepasta",
        "Rosson keittiön maukasta volognesekastiketta, pennepastaa ja rucolaa",
        "Kirjolohta ja creme-hollandaisekastiketta",
        "Paistettua kotimaista kirjolohta, creme-hollandaisekastiketta, perunamuusia, raikasta salaattia, kevätsipulia ja sitruunaa",
        "Lounaspizza kolmella täytteellä",
        "Lounassalaatti"
      ]
    },
    "13": {
      "perjantai": [
        "sin ja lauantaisin olemme auki poikkeuksellisesti klo 22.00 (Keittiö klo 21.30)",
        "TORTELLINI PARMIGIANA",
        "SPECK & QUATTRO FORMAGGi",
        "PINSA TRICOLORE",
        "Lasten Menu",
        "ma-to klo 10.30-14.00 pe klo 10.30-15.00",
        "Ma: Uunipossua Pizzaiolakastikkeella Ja Pennepastaa Kermaisessa Kasviskastikkeessa",
        "Ti: Uunilohta Sitrus – Voikastikkeella Ja Risotto Milanon Tapaan",
        "Ke: Napolilaista Lasagnea Ja Ylikypsää Naudanlihapata",
        "To: Pennepastaa Tomaatti – Ricottakastikkeella Ja Paistettua Kanaa Kermaisessa Kastikkeessa"
      ]
    },
    "14": {
      "perjantai": [
        "hin klo 10.30-14.30 ja lauantaisin klo 10.30-15.00. Meiltä löydät maistuvat lounaat ja kehutun salaattipöydän! Saat meiltä lounaat myös mukaan kotona tai työpaikalla nautittavaksi.",
        "Meille on helppo poiketa niin junalla, bussilla kuin omalla autollakin. Parkkitilaa löytyy sekä Matkakeskuksen edestä että parkkihallista, josta on esteetön kulku ravintolaan.",
        "Remar Portti | Kuopion Matkakeskus",
        "Puutarhakatu 9, 70300 Kuopio",
        "Puh. 041 313 2807",
        "Koko lounas 13,70 €",
        "Kevyt lounas (salaattipöytä ja keitto) 11,60 €",
        "Salaatti- tai keittolounas 10,60 €",
        "Kaikki lounaat sisältävät runsaan salaattipöydän, ruokajuomat sekä kahvin/teen ja jälkiruoan."
      ],
      "maanantai": [
        "Salaattibuffet",
        "Parsakaalikeittoa L, G",
        "Jauhelihapihvejä & muhennettua sipulia L",
        "Kana-chorizopastaa L",
        "Perunasosetta L, G",
        "Porkkana-kikhernepihvejä & kasvis cous cous Veg",
        "Mansikka-raparperirahkaa L, G"
      ],
      "tiistai": [
        "Salaattibuffet",
        "Hirvikeittoa L, G",
        "Karibian kanaa (Suomi) & ananas-salsaa M, G",
        "Kebab-perunavuokaa L, G",
        "Riisiä Veg, G",
        "Pinaattilettuja & puolukkahilloketta Veg, G",
        "Mango-riisifruttia L, G"
      ],
      "keskiviikko": [
        "Salaattibuffet",
        "Peruna-kinkkukeittoa L, G",
        "Juustokuorrutteisia makkarapihvejä L, G",
        "Järvikalapyöryköitä L, G & tartarkastiketta L",
        "Paistettuja perunoita Veg, G",
        "Buffalo-kukkakaalia & tofua Veg, G",
        "Talon porkkanakakkua L"
      ],
      "torstai": [
        "Salaattibuffet",
        "Lohikeittoa L, G",
        "Riistapyöryköitä & kermaista rosmariinikastiketta L, G",
        "Kanapaellaa & aiolia M, G",
        "Keitettyjä perunoita Veg, G",
        "Kirsikkatomaatti-mifupastaa L",
        "Karhunvadelmakiisseliä Veg, G"
      ]
    },
    "15": {
      "maanantai": [
        "Paprika-kukkakaalikeitto l G",
        "Keittolounas 7.50 e.",
        "Sis. keitto, salaatti, leivät ja levitteet, kahvi/tee, jälkiruoka."
      ],
      "tiistai": [
        "Purjo-perunasosekeitto l G",
        "Keittolounas 7.50 e.",
        "Sis. keitto, salaatti, leivät ja levitteet, kahvi/tee, jälkiruoka."
      ],
      "keskiviikko": [
        "Tomaattinen linssikeitto l G",
        "Keittolounas 7.50 e.",
        "Sis. keitto, salaatti, leivät ja levitteet, kahvi/tee, jälkiruoka."
      ],
      "torstai": [
        "Tuorehernekeitto l G Veg",
        "Keittolounas 7.50 e.",
        "Sis. keitto, salaatti, leivät ja levitteet, kahvi/tee, jälkiruoka."
      ],
      "perjantai": [
        "Tomaatti-papukeitto l G Veg.",
        "Keittolounas 7.50 e.",
        "Sis. keitto, salaatti, leivät ja levitteet, kahvi/tee, jälkiruoka."
      ]
    },
    "16": {
      "maanantai": [
        "Flätti-Sänvich Härällä",
        "Pulled beefiä, kurkku-omenapikkeliä, remouladea, bearnaisekastiketta ja balsamicosiirappia. Lisäksi tomaattisuolatut lohkoperunat.",
        "Ehtan Kanapasta",
        "Bearnaise- ja BBQ-kastiketta, parmesaania ja tomaattichutney."
      ],
      "tiistai": [
        "Ehtan Kanapasta",
        "Bearnaise- ja BBQ-kastiketta, parmesaania ja tomaattichutney.",
        "Paahdettua lohta",
        "Sitrus-perunapyreetä, lämpimiä kasviksia ja chimichurrimajoneesia."
      ],
      "keskiviikko": [
        "Paahdettua lohta",
        "Sitrus-perunapyreetä, lämpimiä kasviksia ja chimichurrimajoneesia.",
        "Cheddarbroileririsotto",
        "Parmesaania, tomaattichutney ja rapeaa lehtikaalta."
      ],
      "torstai": [
        "Cheddarbroileririsotto",
        "Parmesaania, tomaattichutney ja rapeaa lehtikaalta.",
        "Mixed Grill",
        "Rapeaksi paneroitua broileria, pulled porkia, inkivääripikkelöityä coleslawia ja blue cheese-majoneesia. Lisäksi basilikalla maustettuja lohkoperunoita."
      ],
      "perjantai": [
        "Mixed Grill",
        "Rapeaksi paneroitua broileria, pulled porkia, inkivääripikkelöityä coleslawia ja blue cheese-majoneesia. Lisäksi basilikalla maustettuja lohkoperunoita.",
        "Paistettua lohta",
        "Skånen perunaa, yrttiöljyä ja kasviksia"
      ]
    },
    "17": {
      "perjantai": [
        "sin tortillabuffa klo 11-14!",
        "Kerää leimoja ja ansaitse täydellä lounaspassilla 14€ arvoinen etu seuraavasta lounaasta!",
        "Today 16.4.",
        "Viikon parila- 13,50€ L, PGPaholaisen broileria",
        "Viikon meksikolainen 12,50€ LQuesadilla ylikypsällä possulla",
        "Viikon kasvisannos 12,50€ LQuesadilla vuohenjuustolla",
        "Friday 17.4.",
        "Viikon parila- 13,50€ L, PGPaholaisen broileria",
        "Viikon meksikolainen 12,50€ LQuesadilla ylikypsällä possulla",
        "Viikon kasvisannos 12,50€ LQuesadilla vuohenjuustolla"
      ]
    },
    "18": {
      "maanantai": [
        "Kanakeittoa L, G",
        "Falafelpyöryköitä L, G",
        "Kookos-kurkumauunikalaa L, G",
        "Kuningatarrahkaa L, G"
      ],
      "tiistai": [
        "Mustajuurikeittoa L, G",
        "Sitruuna-timjamibroileria L, G",
        "Lohimurekepihvejä L, G",
        "Puolukkakiisseliä M, G"
      ],
      "keskiviikko": [
        "Linssi-kasviskeittoa L, G",
        "Suutarin muikkuja L, G",
        "Metsästäjän pihvejä L, G",
        "Jogurtti-marjahyytelöä L, G"
      ],
      "torstai": [
        "Juusto-tuoreherkkusienikeittoa L, G",
        "Jauheliha-perunapaistosta L, G",
        "Broilerimurekepihvejä L, G"
      ],
      "perjantai": [
        "Avoinna klo 11-13",
        "Tomaattikeittoa M, G",
        "Kylmäsavulohirisottoa L, G",
        "Broileria Bonne Femme L, G",
        "Suklaakiisseliä L, G",
        "Viherpippuri-juustokeittoa L, G",
        "Appelsiini-oliivilohta L, G",
        "Aurajuusto-possupataa L, G",
        "Mansikkapannacottaa L, G​",
        "​Salongin juhlalounas"
      ]
    },
    "19": {
      "maanantai": [
        "10.Paistetut katkaravut",
        "6.Kana ja vihannekset wokissa",
        "1.Munalla ja vihanneksilla paistettu riisi",
        "15.Paistetut nuudelit naudanlihalla",
        "3.Tulinen naudanliha-annos",
        "11.Paistetut kanavartaat",
        "8.Isot paistetut kevätkääryleet",
        "2.Paistettu riisi char siu-porsaan kanssa",
        "13.Paistettu riisi kanalla",
        "9.Paistetut kanaharkot (dumplingit)",
        "17.Paistetut nuudelit vihanneksilla",
        "4.Naudanlihaa ja vihanneksia wokissa",
        "14.Paistettu riisi munalla",
        "12.Paistettu riisi naudanlihalla",
        "7.Tofuruoka"
      ],
      "tiistai": [
        "10.Paistetut katkaravut",
        "6.Kana ja vihannekset wokissa",
        "1.Munalla ja vihanneksilla paistettu riisi",
        "15.Paistetut nuudelit naudanlihalla",
        "3.Tulinen naudanliha-annos",
        "11.Paistetut kanavartaat",
        "8.Isot paistetut kevätkääryleet",
        "2.Paistettu riisi char siu-porsaan kanssa",
        "13.Paistettu riisi kanalla",
        "9.Paistetut kanaharkot (dumplingit)",
        "17.Paistetut nuudelit vihanneksilla",
        "4.Naudanlihaa ja vihanneksia wokissa",
        "14.Paistettu riisi munalla",
        "12.Paistettu riisi naudanlihalla",
        "7.Tofuruoka"
      ],
      "keskiviikko": [
        "10.Paistetut katkaravut",
        "6.Kana ja vihannekset wokissa",
        "1.Munalla ja vihanneksilla paistettu riisi",
        "15.Paistetut nuudelit naudanlihalla",
        "3.Tulinen naudanliha-annos",
        "11.Paistetut kanavartaat",
        "8.Isot paistetut kevätkääryleet",
        "2.Paistettu riisi char siu-porsaan kanssa",
        "13.Paistettu riisi kanalla",
        "9.Paistetut kanaharkot (dumplingit)",
        "17.Paistetut nuudelit vihanneksilla",
        "4.Naudanlihaa ja vihanneksia wokissa",
        "14.Paistettu riisi munalla",
        "12.Paistettu riisi naudanlihalla",
        "7.Tofuruoka"
      ],
      "torstai": [
        "10.Paistetut katkaravut",
        "6.Kana ja vihannekset wokissa",
        "1.Munalla ja vihanneksilla paistettu riisi",
        "15.Paistetut nuudelit naudanlihalla",
        "3.Tulinen naudanliha-annos",
        "11.Paistetut kanavartaat",
        "8.Isot paistetut kevätkääryleet",
        "2.Paistettu riisi char siu-porsaan kanssa",
        "13.Paistettu riisi kanalla",
        "9.Paistetut kanaharkot (dumplingit)",
        "17.Paistetut nuudelit vihanneksilla",
        "4.Naudanlihaa ja vihanneksia wokissa",
        "14.Paistettu riisi munalla",
        "12.Paistettu riisi naudanlihalla",
        "7.Tofuruoka"
      ],
      "perjantai": [
        "10.Paistetut katkaravut",
        "6.Kana ja vihannekset wokissa",
        "1.Munalla ja vihanneksilla paistettu riisi",
        "15.Paistetut nuudelit naudanlihalla",
        "3.Tulinen naudanliha-annos",
        "11.Paistetut kanavartaat",
        "8.Isot paistetut kevätkääryleet",
        "2.Paistettu riisi char siu-porsaan kanssa",
        "13.Paistettu riisi kanalla",
        "9.Paistetut kanaharkot (dumplingit)",
        "17.Paistetut nuudelit vihanneksilla",
        "4.Naudanlihaa ja vihanneksia wokissa",
        "14.Paistettu riisi munalla",
        "12.Paistettu riisi naudanlihalla",
        "7.Tofuruoka"
      ]
    }
  }
};
