// Seinäjoen lounasravintolat - data
// Koordinaatit, menut, kategoriat

const OFFICE_LOCATION = {
    lat: 62.7903,
    lng: 22.8403,
    name: 'Siili Solutions Seinäjoki',
    address: 'Kauppakatu 10, 60100 Seinäjoki'
};

const FOOD_TAGS = {
    // Proteiini
    CHICKEN: 'kana',
    BEEF: 'nauta',
    PORK: 'sika',
    FISH: 'kala',
    VEGETARIAN: 'kasvis',
    VEGAN: 'vegaani',
    // Ruokalaji
    SOUP: 'keitto',
    SALAD: 'salaatti',
    BURGER: 'hampurilainen',
    PASTA: 'pasta',
    PIZZA: 'pizza',
    RICE: 'riisi',
    STEW: 'pata',
    CURRY: 'curry',
    SUSHI: 'sushi',
    WRAP: 'wrap',
    NOODLE: 'nuudeli',
    CASSEROLE: 'laatikko',
    STEAK: 'pihvi',
    // Keittiö
    FINNISH: 'suomalainen',
    ASIAN: 'aasialainen',
    MEXICAN: 'meksikolainen',
    ITALIAN: 'italialainen',
    INDIAN: 'intialainen',
    AMERICAN: 'amerikkalainen',
    JAPANESE: 'japanilainen',
    CHINESE: 'kiinalainen',
    SCANDINAVIAN: 'skandinaavinen',
    // Tyyli
    LIGHT: 'kevyt',
    HEAVY: 'ruokaisa',
    COMFORT: 'comfort',
    HEALTHY: 'terveellinen',
    SPICY: 'mausteinen',
    BBQ: 'bbq',
    FRIED: 'paistettu',
    BAKED: 'uuni'
};

const RESTAURANTS = [
    {
        id: 'holy_smoke',
        name: 'Holy Smoke',
        address: 'Koulukatu 20, 60100 Seinäjoki',
        lat: 62.7882,
        lng: 22.8378,
        phone: '+358 44 23 54 113',
        website: 'https://holysmoke.fi',
        hours: 'ma-pe 11:00-14:00',
        price: '12.90-16.90 €',
        priceNum: 14.90,
        cuisineTags: ['amerikkalainen', 'bbq'],
        description: 'Amerikkalaistyyppinen steakhouse ja BBQ-ravintola',
        menuPool: [
            { name: 'Classic Smash Burger ja ranskalaiset', tags: ['nauta', 'hampurilainen', 'amerikkalainen', 'ruokaisa', 'comfort'] },
            { name: 'BBQ Pulled Pork -burger ja coleslaw', tags: ['sika', 'hampurilainen', 'amerikkalainen', 'bbq', 'ruokaisa'] },
            { name: 'Smokehouse Bacon Cheese Burger', tags: ['nauta', 'hampurilainen', 'amerikkalainen', 'bbq', 'ruokaisa'] },
            { name: 'Grillattu ribsit ja maissi', tags: ['sika', 'amerikkalainen', 'bbq', 'ruokaisa'] },
            { name: 'Cajun-kanaburger ja bataattiranskalaiset', tags: ['kana', 'hampurilainen', 'amerikkalainen', 'mausteinen'] },
            { name: 'Texas BBQ Brisket ja perunasalaatti', tags: ['nauta', 'amerikkalainen', 'bbq', 'ruokaisa'] },
            { name: 'Grillipihvi ja pippurikastike', tags: ['nauta', 'pihvi', 'amerikkalainen', 'ruokaisa'] },
            { name: 'Nashville Hot Chicken Burger', tags: ['kana', 'hampurilainen', 'amerikkalainen', 'mausteinen'] },
            { name: 'Savupossumac ja juustokastike', tags: ['sika', 'amerikkalainen', 'bbq', 'comfort'] },
            { name: 'BBQ Bacon Wrapit ja dippi', tags: ['kana', 'wrap', 'amerikkalainen', 'bbq'] },
            { name: 'Double Cheese Burger ja sipulirenkaat', tags: ['nauta', 'hampurilainen', 'amerikkalainen', 'ruokaisa', 'comfort'] },
            { name: 'Pulled Pork Nachos ja guacamole', tags: ['sika', 'amerikkalainen', 'bbq', 'mausteinen'] },
            { name: 'Vegaaninen Beyond Burger', tags: ['vegaani', 'kasvis', 'hampurilainen', 'amerikkalainen'] },
            { name: 'Fish & Chips ja tartarkastike', tags: ['kala', 'paistettu', 'amerikkalainen'] },
            { name: 'Kanawingsit ja blue cheese -dippi', tags: ['kana', 'amerikkalainen', 'bbq', 'mausteinen'] },
            { name: 'Smokehouse Salad ja grillibroileria', tags: ['kana', 'salaatti', 'amerikkalainen', 'terveellinen'] },
            { name: 'BBQ Burger ja savumajoneesi', tags: ['nauta', 'hampurilainen', 'amerikkalainen', 'bbq', 'comfort'] },
            { name: 'Chili Cheese Fries ja kanafileet', tags: ['kana', 'amerikkalainen', 'mausteinen', 'comfort'] },
            { name: 'Steakhouse Salad ja paahdettu nauta', tags: ['nauta', 'salaatti', 'amerikkalainen', 'terveellinen'] }
        ]
    },
    {
        id: 'juku',
        name: 'Ravintola Juku',
        address: 'Koulukatu 22, 60100 Seinäjoki',
        lat: 62.7880,
        lng: 22.8382,
        phone: '+358 44 970 9698',
        website: 'https://ravintolajuku.fi',
        hours: 'ma-pe 10:30-14:00',
        price: '14.90 €',
        priceNum: 14.90,
        cuisineTags: ['japanilainen', 'aasialainen'],
        description: 'Japanilainen ravintola - sushia, ramenia ja dumplingeja',
        menuPool: [
            { name: 'Sushi-lautanen (12 palaa)', tags: ['kala', 'sushi', 'japanilainen', 'aasialainen', 'kevyt', 'terveellinen'] },
            { name: 'Tonkotsu Ramen ja chashu-sika', tags: ['sika', 'nuudeli', 'japanilainen', 'aasialainen', 'keitto', 'ruokaisa'] },
            { name: 'Teriyaki-kanaa ja riisiä', tags: ['kana', 'riisi', 'japanilainen', 'aasialainen'] },
            { name: 'Miso Ramen ja tofua', tags: ['kasvis', 'nuudeli', 'japanilainen', 'aasialainen', 'keitto'] },
            { name: 'Sake-lohi don ja pikkelöidyt kasvikset', tags: ['kala', 'riisi', 'japanilainen', 'aasialainen', 'terveellinen'] },
            { name: 'Gyoza-dumplingit (kana) ja dipit', tags: ['kana', 'japanilainen', 'aasialainen', 'paistettu'] },
            { name: 'Katsu Curry ja japanilainen riisi', tags: ['sika', 'curry', 'riisi', 'japanilainen', 'aasialainen', 'mausteinen'] },
            { name: 'Vegaani Sushi Set (avokado, kurkku)', tags: ['vegaani', 'kasvis', 'sushi', 'japanilainen', 'aasialainen', 'kevyt'] },
            { name: 'Udon-nuudelikeitto ja tempuravihannekset', tags: ['kasvis', 'nuudeli', 'japanilainen', 'aasialainen', 'keitto'] },
            { name: 'Chicken Katsu Don ja terisoija', tags: ['kana', 'riisi', 'japanilainen', 'aasialainen', 'paistettu', 'ruokaisa'] },
            { name: 'Chirashi Bowl ja wasabi', tags: ['kala', 'riisi', 'japanilainen', 'aasialainen', 'terveellinen'] },
            { name: 'Ebi Tempura ja riisi', tags: ['kala', 'riisi', 'japanilainen', 'aasialainen', 'paistettu'] },
            { name: 'Yakisoba-nuudelit ja possua', tags: ['sika', 'nuudeli', 'japanilainen', 'aasialainen'] },
            { name: 'Tofu Donburi ja sesamkastike', tags: ['kasvis', 'vegaani', 'riisi', 'japanilainen', 'aasialainen', 'terveellinen'] },
            { name: 'Spicy Tuna Roll ja miso-keitto', tags: ['kala', 'sushi', 'japanilainen', 'aasialainen', 'mausteinen'] },
            { name: 'Beef Yakiniku Don', tags: ['nauta', 'riisi', 'japanilainen', 'aasialainen', 'ruokaisa'] },
            { name: 'Karaage-kanaa ja japanilainen majoneesi', tags: ['kana', 'japanilainen', 'aasialainen', 'paistettu', 'comfort'] }
        ]
    },
    {
        id: 'marttilan_talli',
        name: 'Marttilan Talli',
        address: 'Puskantie 38, 60100 Seinäjoki',
        lat: 62.7950,
        lng: 22.8250,
        phone: '+358 40 774 8545',
        website: 'https://marttilantalli.fi',
        hours: 'ma-pe 10:30-13:30',
        price: '11.90 €',
        priceNum: 11.90,
        cuisineTags: ['suomalainen'],
        description: 'Perinteistä suomalaista kotiruokaa historiallisessa miljöössä',
        menuPool: [
            { name: 'Lohikeitto ja ruisleipä', tags: ['kala', 'keitto', 'suomalainen', 'comfort'] },
            { name: 'Karjalanpaisti ja perunamuusi', tags: ['nauta', 'sika', 'pata', 'suomalainen', 'ruokaisa', 'comfort'] },
            { name: 'Hernekeitto ja pannukakku', tags: ['kasvis', 'keitto', 'suomalainen', 'comfort'] },
            { name: 'Jauhelihakastike ja perunat', tags: ['nauta', 'suomalainen', 'ruokaisa', 'comfort'] },
            { name: 'Paistettu kuha ja tillikastike', tags: ['kala', 'paistettu', 'suomalainen'] },
            { name: 'Uunilohi ja perunasose', tags: ['kala', 'uuni', 'suomalainen'] },
            { name: 'Lihapullat ja puolukkahillo', tags: ['nauta', 'sika', 'suomalainen', 'comfort'] },
            { name: 'Maksalaatikko ja puolukat', tags: ['sika', 'laatikko', 'suomalainen', 'comfort', 'uuni'] },
            { name: 'Kalakukko ja munavoi', tags: ['kala', 'suomalainen', 'uuni', 'comfort'] },
            { name: 'Nakkikeitto ja sinappi', tags: ['sika', 'keitto', 'suomalainen', 'comfort'] },
            { name: 'Poronkäristys ja perunamuusi', tags: ['nauta', 'suomalainen', 'ruokaisa'] },
            { name: 'Silakkalaatikko ja punajuuri', tags: ['kala', 'laatikko', 'suomalainen', 'uuni'] },
            { name: 'Kaalilaatikko ja ketsuppi', tags: ['sika', 'laatikko', 'suomalainen', 'uuni', 'comfort'] },
            { name: 'Broilerkastike ja riisi', tags: ['kana', 'riisi', 'suomalainen'] },
            { name: 'Siskonmakkarakeitto', tags: ['sika', 'keitto', 'suomalainen', 'comfort'] },
            { name: 'Pyttipannu ja paistettu muna', tags: ['sika', 'nauta', 'paistettu', 'suomalainen', 'comfort', 'ruokaisa'] },
            { name: 'Kasviskeitto ja tuore leipä', tags: ['kasvis', 'keitto', 'suomalainen', 'kevyt', 'terveellinen'] },
            { name: 'Stroganoff ja riisi', tags: ['nauta', 'riisi', 'suomalainen', 'ruokaisa'] }
        ]
    },
    {
        id: 'aarella',
        name: 'Äärellä Kuppi ja Kattila',
        address: 'Nyykoolinkatu 25, 60100 Seinäjoki',
        lat: 62.7918,
        lng: 22.8285,
        phone: '+358 50 350 5312',
        website: 'https://aarella.fi',
        hours: 'ti-la 11:00-14:00',
        price: '13.90 €',
        priceNum: 13.90,
        cuisineTags: ['suomalainen', 'skandinaavinen'],
        description: 'Kotiruokaa luomuraaka-aineista, erinomainen kasvisruoka',
        menuPool: [
            { name: 'Bataattikeitto ja paahdetut siemenet', tags: ['vegaani', 'kasvis', 'keitto', 'suomalainen', 'terveellinen'] },
            { name: 'Vuohenjuusto-punajuurisalaatti', tags: ['kasvis', 'salaatti', 'skandinaavinen', 'kevyt', 'terveellinen'] },
            { name: 'Kasviscurry ja basmati-riisi', tags: ['vegaani', 'kasvis', 'curry', 'riisi', 'mausteinen', 'terveellinen'] },
            { name: 'Pinaattiletut ja puolukkahillo', tags: ['kasvis', 'suomalainen', 'comfort'] },
            { name: 'Linssikeitto ja foccacia', tags: ['vegaani', 'kasvis', 'keitto', 'terveellinen'] },
            { name: 'Savulohisalaatti ja sitruunavinaigrette', tags: ['kala', 'salaatti', 'skandinaavinen', 'kevyt', 'terveellinen'] },
            { name: 'Kasvismoussaka ja tzatziki', tags: ['kasvis', 'uuni', 'terveellinen'] },
            { name: 'Tofu-wokkivihannekset ja nuudelit', tags: ['vegaani', 'kasvis', 'nuudeli', 'aasialainen', 'terveellinen'] },
            { name: 'Porkkanasosekeitto ja yrttileipä', tags: ['vegaani', 'kasvis', 'keitto', 'suomalainen', 'kevyt', 'terveellinen'] },
            { name: 'Kotimainen kirjolohi ja kauden kasvikset', tags: ['kala', 'suomalainen', 'skandinaavinen', 'terveellinen'] },
            { name: 'Härkis-bolognese ja tuorepasta', tags: ['vegaani', 'kasvis', 'pasta', 'italialainen', 'comfort'] },
            { name: 'Falafel-bowl ja hummus', tags: ['vegaani', 'kasvis', 'terveellinen', 'mausteinen'] },
            { name: 'Kantarellirisotto ja parmesaani', tags: ['kasvis', 'riisi', 'italialainen', 'skandinaavinen'] },
            { name: 'Kana-avokadosalaatti ja siemennäkkäri', tags: ['kana', 'salaatti', 'terveellinen', 'kevyt'] },
            { name: 'Kasvislasagne ja vihersalaatti', tags: ['kasvis', 'pasta', 'italialainen', 'uuni', 'comfort'] },
            { name: 'Uunikala ja yrttivoi', tags: ['kala', 'uuni', 'suomalainen', 'skandinaavinen'] },
            { name: 'Quinoa-kasvisbowl ja tahini', tags: ['vegaani', 'kasvis', 'salaatti', 'terveellinen', 'kevyt'] },
            { name: 'Kookos-bataattisosekeitto', tags: ['vegaani', 'kasvis', 'keitto', 'mausteinen', 'terveellinen'] }
        ]
    },
    {
        id: 'uppalan_kartano',
        name: 'Uppalan Kartano',
        address: 'Ilmarisenkatu 14, 60100 Seinäjoki',
        lat: 62.7834,
        lng: 22.8382,
        phone: '+358 6 4141800',
        website: 'https://uppalankartano.fi',
        hours: 'ma-pe 11:00-14:00',
        price: '14.90-18.90 €',
        priceNum: 16.90,
        cuisineTags: ['skandinaavinen', 'italialainen'],
        description: 'Tyylikäs kartanoravintola, pohjoismainen ja eurooppalainen keittiö',
        menuPool: [
            { name: 'Graavilohi ja tillicastike', tags: ['kala', 'skandinaavinen', 'kevyt'] },
            { name: 'Pasta Carbonara ja parmesaani', tags: ['sika', 'pasta', 'italialainen', 'comfort', 'ruokaisa'] },
            { name: 'Paahdettu ankka ja appelsiinglaze', tags: ['kana', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Risotto ai funghi porcini', tags: ['kasvis', 'riisi', 'italialainen', 'skandinaavinen'] },
            { name: 'Lammaspata ja juurekset', tags: ['nauta', 'pata', 'skandinaavinen', 'ruokaisa', 'comfort'] },
            { name: 'Uunissa paistettu siika ja perunakakku', tags: ['kala', 'uuni', 'suomalainen', 'skandinaavinen'] },
            { name: 'Penne arrabiata ja basilika', tags: ['kasvis', 'pasta', 'italialainen', 'mausteinen'] },
            { name: 'Kartanon naudanfilee ja bearnaise', tags: ['nauta', 'pihvi', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Caesarsalaatti ja grillikanaa', tags: ['kana', 'salaatti', 'italialainen', 'terveellinen'] },
            { name: 'Kalakeitto ja aioli', tags: ['kala', 'keitto', 'skandinaavinen'] },
            { name: 'Tagliatelle ja tryffelikastike', tags: ['kasvis', 'pasta', 'italialainen', 'ruokaisa'] },
            { name: 'Hirvipaisti ja puolukat', tags: ['nauta', 'suomalainen', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Gnocchi ja salvia-voi', tags: ['kasvis', 'pasta', 'italialainen'] },
            { name: 'Kuhafilee ja pinaattikastike', tags: ['kala', 'skandinaavinen'] },
            { name: 'Italialainen tomaattikeitto ja focaccia', tags: ['kasvis', 'vegaani', 'keitto', 'italialainen', 'kevyt'] },
            { name: 'Possun ulkofilee ja omenakompotti', tags: ['sika', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Insalata Caprese ja balsamico', tags: ['kasvis', 'salaatti', 'italialainen', 'kevyt', 'terveellinen'] }
        ]
    },
    {
        id: 'pancho_villa',
        name: 'Pancho Villa',
        address: 'Kalevankatu 11-14, 60100 Seinäjoki',
        lat: 62.7895,
        lng: 22.8418,
        phone: '+358 10 320 9890',
        website: 'https://panchovilla.fi',
        hours: 'ma-pe 11:00-14:00',
        price: '12.90-14.90 €',
        priceNum: 13.90,
        cuisineTags: ['meksikolainen'],
        description: 'Meksikolainen ravintola - burritoja, tacoja ja nachoja',
        menuPool: [
            { name: 'Burrito Bowl (kana) ja guacamole', tags: ['kana', 'riisi', 'meksikolainen', 'mausteinen', 'ruokaisa'] },
            { name: 'Beef Tacos ja pico de gallo', tags: ['nauta', 'meksikolainen', 'mausteinen'] },
            { name: 'Quesadilla (juusto ja kana)', tags: ['kana', 'meksikolainen', 'comfort'] },
            { name: 'Nachos Grande ja jalapeno-juusto', tags: ['nauta', 'meksikolainen', 'mausteinen', 'comfort', 'ruokaisa'] },
            { name: 'Chicken Fajitas ja salsa', tags: ['kana', 'meksikolainen', 'mausteinen'] },
            { name: 'Vegaani Burrito ja papu-riisi', tags: ['vegaani', 'kasvis', 'wrap', 'meksikolainen', 'mausteinen'] },
            { name: 'Chili con Carne ja riisi', tags: ['nauta', 'riisi', 'meksikolainen', 'mausteinen', 'pata', 'ruokaisa'] },
            { name: 'Fish Tacos ja lime-crema', tags: ['kala', 'meksikolainen', 'kevyt'] },
            { name: 'Enchiladas (possua) ja juustokastike', tags: ['sika', 'meksikolainen', 'mausteinen', 'uuni', 'comfort'] },
            { name: 'Taco Salad Bowl ja avokado', tags: ['kana', 'salaatti', 'meksikolainen', 'terveellinen'] },
            { name: 'Carnitas Burrito ja chipotle-mayo', tags: ['sika', 'wrap', 'meksikolainen', 'mausteinen', 'ruokaisa'] },
            { name: 'Bean & Cheese Quesadilla', tags: ['kasvis', 'meksikolainen', 'comfort'] },
            { name: 'Steak Burrito ja jalapeño', tags: ['nauta', 'wrap', 'meksikolainen', 'mausteinen', 'ruokaisa'] },
            { name: 'Loaded Nachos (kana) ja smetana', tags: ['kana', 'meksikolainen', 'comfort', 'ruokaisa'] },
            { name: 'Vegaani Taco Bowl ja soijarouhe', tags: ['vegaani', 'kasvis', 'meksikolainen', 'terveellinen'] },
            { name: 'Chimichanga ja salsa roja', tags: ['nauta', 'meksikolainen', 'paistettu', 'ruokaisa', 'comfort'] }
        ]
    },
    {
        id: 'juurella',
        name: 'Ravintola Juurella',
        address: 'Kauppakatu 19, 60100 Seinäjoki',
        lat: 62.7905,
        lng: 22.8395,
        phone: '+358 6 4140720',
        website: 'https://juurella.fi',
        hours: 'ma-pe 11:00-14:00',
        price: '13.90-16.90 €',
        priceNum: 15.40,
        cuisineTags: ['skandinaavinen'],
        description: 'Moderni pohjoismainen keittiö paikallisista raaka-aineista',
        menuPool: [
            { name: 'Paahdettu juuressosekeitto ja ruiscroutonit', tags: ['vegaani', 'kasvis', 'keitto', 'skandinaavinen', 'terveellinen'] },
            { name: 'Graavilohi ja perunarösti', tags: ['kala', 'skandinaavinen', 'paistettu'] },
            { name: 'Nyhtökaura-bowl ja pikkelöidyt kasvikset', tags: ['vegaani', 'kasvis', 'salaatti', 'skandinaavinen', 'terveellinen'] },
            { name: 'Pohjalainen kalakeitto ja ruisleipä', tags: ['kala', 'keitto', 'suomalainen', 'skandinaavinen', 'comfort'] },
            { name: 'Hirvitartar ja sinappi-emulsio', tags: ['nauta', 'skandinaavinen', 'kevyt'] },
            { name: 'Kauden kala ja beurre blanc', tags: ['kala', 'skandinaavinen', 'kevyt'] },
            { name: 'Possun kylki ja omenakompotti', tags: ['sika', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Kasvistalvikko ja vuohenjuusto', tags: ['kasvis', 'uuni', 'skandinaavinen', 'comfort'] },
            { name: 'Ankkaconfit ja punajuuripuré', tags: ['kana', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Paahdettu kukkakaali ja tahinikastike', tags: ['vegaani', 'kasvis', 'uuni', 'skandinaavinen', 'terveellinen'] },
            { name: 'Lammaskarée ja rosmariini', tags: ['nauta', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Nordic Bowl ja marinoitu lohi', tags: ['kala', 'salaatti', 'skandinaavinen', 'terveellinen', 'kevyt'] },
            { name: 'Kanafilee ja kantarellkastike', tags: ['kana', 'suomalainen', 'skandinaavinen'] },
            { name: 'Kotimainen nauta ja juurespyré', tags: ['nauta', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Pinaatti-fetakeitto ja siemenleipä', tags: ['kasvis', 'keitto', 'skandinaavinen', 'terveellinen'] }
        ]
    },
    {
        id: 'valkoinen_puu',
        name: 'Valkoinen Puu',
        address: 'Kalevankatu 11-13, 60100 Seinäjoki',
        lat: 62.7895,
        lng: 22.8415,
        phone: '+358 44 978 4683',
        website: 'https://valkoinenpuu.fi',
        hours: 'ma-pe 11:00-14:00',
        price: '11.50 €',
        priceNum: 11.50,
        cuisineTags: ['suomalainen', 'skandinaavinen'],
        description: 'Tyylikäs kahvila-ravintola, kevyt lounas ja erikoiskahvit',
        menuPool: [
            { name: 'Päivän keitto ja tuore leipä', tags: ['kasvis', 'keitto', 'suomalainen', 'kevyt'] },
            { name: 'Caesar-salaatti ja grillikanaa', tags: ['kana', 'salaatti', 'kevyt', 'terveellinen'] },
            { name: 'Avokado-lohileipä ja munakas', tags: ['kala', 'kevyt', 'terveellinen'] },
            { name: 'Quiche ja vihersalaatti', tags: ['kasvis', 'uuni', 'kevyt'] },
            { name: 'Kanawrap ja hummus', tags: ['kana', 'wrap', 'kevyt', 'terveellinen'] },
            { name: 'Kasvis-feta-piiras ja salaatti', tags: ['kasvis', 'uuni', 'kevyt', 'terveellinen'] },
            { name: 'Lohi-avokado bowl', tags: ['kala', 'salaatti', 'kevyt', 'terveellinen'] },
            { name: 'Tomaattikeitto ja mozzarella', tags: ['kasvis', 'keitto', 'italialainen', 'kevyt'] },
            { name: 'Kana-pastasalaatti ja pesto', tags: ['kana', 'pasta', 'salaatti', 'kevyt'] },
            { name: 'Halloumi-salaatti ja granaattiomena', tags: ['kasvis', 'salaatti', 'kevyt', 'terveellinen'] },
            { name: 'Pulled Oats -wrap ja chipotle', tags: ['vegaani', 'kasvis', 'wrap', 'kevyt', 'terveellinen'] },
            { name: 'Savulohi-bagel ja tuorejuusto', tags: ['kala', 'kevyt'] },
            { name: 'Falafel-pitta ja tahinikastike', tags: ['vegaani', 'kasvis', 'wrap', 'mausteinen', 'terveellinen'] },
            { name: 'Kana-mango-salaatti ja cashew', tags: ['kana', 'salaatti', 'kevyt', 'terveellinen'] },
            { name: 'Vegaani ramen ja tofu', tags: ['vegaani', 'kasvis', 'nuudeli', 'aasialainen', 'keitto'] }
        ]
    },
    {
        id: 'shi_quan',
        name: 'Shi Quan Shi Mei',
        address: 'Kauppakatu 1, 60100 Seinäjoki',
        lat: 62.7915,
        lng: 22.8370,
        phone: '+358 46 5490480',
        website: '',
        hours: 'ma-pe 11:00-14:00',
        price: '11.90 €',
        priceNum: 11.90,
        cuisineTags: ['kiinalainen', 'aasialainen'],
        description: 'Kiinalainen buffet-ravintola edulliseen hintaan',
        menuPool: [
            { name: 'Kanaa ja cashewpähkinää wokissa', tags: ['kana', 'aasialainen', 'kiinalainen', 'paistettu'] },
            { name: 'Kung Pao -kana ja riisi', tags: ['kana', 'riisi', 'kiinalainen', 'aasialainen', 'mausteinen'] },
            { name: 'Hapanimelä possua ja riisi', tags: ['sika', 'riisi', 'kiinalainen', 'aasialainen', 'comfort'] },
            { name: 'Szechuan-naudanlihaa ja paprikaa', tags: ['nauta', 'kiinalainen', 'aasialainen', 'mausteinen'] },
            { name: 'Tofua ja kasviksia mustapapukastikkeessa', tags: ['kasvis', 'vegaani', 'kiinalainen', 'aasialainen', 'mausteinen'] },
            { name: 'Kantonin riisi ja paistettu kana', tags: ['kana', 'riisi', 'kiinalainen', 'aasialainen', 'paistettu'] },
            { name: 'Chow Mein -nuudelit ja katkaravut', tags: ['kala', 'nuudeli', 'kiinalainen', 'aasialainen'] },
            { name: 'Mapo Tofu ja jasmiiniriisi', tags: ['kasvis', 'riisi', 'kiinalainen', 'aasialainen', 'mausteinen'] },
            { name: 'Pekingankkaa ja hoisin', tags: ['kana', 'kiinalainen', 'aasialainen', 'ruokaisa'] },
            { name: 'Wokattuja kasviksia ja tofua', tags: ['kasvis', 'vegaani', 'kiinalainen', 'aasialainen', 'terveellinen', 'kevyt'] },
            { name: 'Spring rolls ja dipit', tags: ['kasvis', 'kiinalainen', 'aasialainen', 'paistettu'] },
            { name: 'Naudanlihaa ja parsakaalia oyster-kastikkeessa', tags: ['nauta', 'kiinalainen', 'aasialainen'] },
            { name: 'Dan Dan -nuudelit (sika)', tags: ['sika', 'nuudeli', 'kiinalainen', 'aasialainen', 'mausteinen'] },
            { name: 'Paistettu riisi ja kananmuna', tags: ['kasvis', 'riisi', 'kiinalainen', 'aasialainen', 'paistettu', 'comfort'] },
            { name: 'Ma La -kanaa ja chili', tags: ['kana', 'kiinalainen', 'aasialainen', 'mausteinen'] }
        ]
    },
    {
        id: 'alma',
        name: 'Ravintola Alma',
        address: 'Ruukintie 4, 60100 Seinäjoki',
        lat: 62.7870,
        lng: 22.8430,
        phone: '+358 6 421 5200',
        website: 'https://hotelalma.fi',
        hours: 'ma-pe 11:00-14:00',
        price: '15.90-29.00 €',
        priceNum: 18.90,
        cuisineTags: ['skandinaavinen'],
        description: 'Hotelliravintola rautatieaseman vieressä, laadukkaat raaka-aineet',
        menuPool: [
            { name: 'Pippuripihvi ja kermaperunat', tags: ['nauta', 'pihvi', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Grillattua lohta ja hollandaise', tags: ['kala', 'skandinaavinen'] },
            { name: 'Burgundinpata ja perunamuusi', tags: ['nauta', 'pata', 'skandinaavinen', 'ruokaisa', 'comfort'] },
            { name: 'Kanafilee ja tryffelikastike', tags: ['kana', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Tartar naudasta ja kapriksia', tags: ['nauta', 'skandinaavinen', 'kevyt'] },
            { name: 'Paahdettu siikafilee ja sitruunavoi', tags: ['kala', 'skandinaavinen'] },
            { name: 'Entrecôte ja béarnaise', tags: ['nauta', 'pihvi', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Ankkarintaa ja kirsikkakastike', tags: ['kana', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Kotimaista possua ja omenasinappi', tags: ['sika', 'skandinaavinen', 'suomalainen'] },
            { name: 'Kasvisrisotto ja griljeerattu vuohenjuusto', tags: ['kasvis', 'riisi', 'italialainen', 'skandinaavinen'] },
            { name: 'Lammaskarée ja minttu-jus', tags: ['nauta', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Salaatti Niçoise ja graavilohi', tags: ['kala', 'salaatti', 'skandinaavinen', 'terveellinen', 'kevyt'] },
            { name: 'Vasikanleike ja sitruuna-kapris', tags: ['nauta', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Kalan päivä - tuoretta kalaa kauden mukaan', tags: ['kala', 'skandinaavinen', 'terveellinen'] },
            { name: 'Päivän keitto ja artesaanileipä', tags: ['kasvis', 'keitto', 'skandinaavinen', 'kevyt'] }
        ]
    },
    {
        id: 'mangal',
        name: 'Ravintola Mangal',
        address: 'Koulukatu 5, 60100 Seinäjoki',
        lat: 62.7888,
        lng: 22.8360,
        phone: '+358 40 867 8226',
        website: 'https://mangal.fi',
        hours: 'ma-pe 11:00-14:00',
        price: '12.90 €',
        priceNum: 12.90,
        cuisineTags: ['intialainen'],
        description: 'Intialainen ja nepalilainen ravintola',
        menuPool: [
            { name: 'Butter Chicken ja naan', tags: ['kana', 'curry', 'intialainen', 'mausteinen', 'comfort'] },
            { name: 'Tikka Masala ja basmati-riisi', tags: ['kana', 'curry', 'riisi', 'intialainen', 'mausteinen'] },
            { name: 'Dal Makhani ja riisi', tags: ['kasvis', 'vegaani', 'curry', 'riisi', 'intialainen', 'mausteinen', 'terveellinen'] },
            { name: 'Lamb Rogan Josh ja naan', tags: ['nauta', 'curry', 'intialainen', 'mausteinen', 'ruokaisa'] },
            { name: 'Palak Paneer ja riisi', tags: ['kasvis', 'curry', 'riisi', 'intialainen', 'mausteinen'] },
            { name: 'Tandoori-kanaa ja raita', tags: ['kana', 'intialainen', 'mausteinen', 'uuni'] },
            { name: 'Chana Masala ja naan', tags: ['kasvis', 'vegaani', 'curry', 'intialainen', 'mausteinen'] },
            { name: 'Vindaloo (nauta) ja riisi', tags: ['nauta', 'curry', 'riisi', 'intialainen', 'mausteinen'] },
            { name: 'Navratan Korma ja naan', tags: ['kasvis', 'curry', 'intialainen', 'mausteinen'] },
            { name: 'Chicken Biryani', tags: ['kana', 'riisi', 'intialainen', 'mausteinen', 'ruokaisa'] },
            { name: 'Aloo Gobi ja chapati', tags: ['kasvis', 'vegaani', 'intialainen', 'mausteinen', 'terveellinen'] },
            { name: 'Fish Curry ja jasmiini-riisi', tags: ['kala', 'curry', 'riisi', 'intialainen', 'mausteinen'] },
            { name: 'Malai Kofta ja riisi', tags: ['kasvis', 'curry', 'riisi', 'intialainen', 'mausteinen', 'comfort'] },
            { name: 'Momo-dumplingit ja tomaattichutney', tags: ['kana', 'intialainen', 'mausteinen'] },
            { name: 'Saag Chicken ja naan', tags: ['kana', 'curry', 'intialainen', 'mausteinen'] },
            { name: 'Vegaani Thali -lautanen', tags: ['vegaani', 'kasvis', 'curry', 'riisi', 'intialainen', 'mausteinen', 'terveellinen'] }
        ]
    },
    {
        id: 'pohjan_purtava',
        name: 'Pohjan Purtava',
        address: 'Väinölänkatu 14, 60120 Seinäjoki',
        lat: 62.7942,
        lng: 22.8355,
        phone: '+358 50 534 8888',
        website: 'https://pohjanpurtava.fi',
        hours: 'ma-pe 06:00-15:00',
        price: '11.50 €',
        priceNum: 11.50,
        cuisineTags: ['suomalainen'],
        description: 'Lounaskahvila - kotiruokaa edullisesti',
        menuPool: [
            { name: 'Makaronilaatikko ja ketsuppi', tags: ['sika', 'laatikko', 'suomalainen', 'uuni', 'comfort', 'ruokaisa'] },
            { name: 'Kanakeitto ja tuore leipä', tags: ['kana', 'keitto', 'suomalainen', 'comfort'] },
            { name: 'Nakkikastike ja perunamuusi', tags: ['sika', 'suomalainen', 'comfort', 'ruokaisa'] },
            { name: 'Lohikeitto ja ruisleipä', tags: ['kala', 'keitto', 'suomalainen', 'comfort'] },
            { name: 'Jauhelihapihvit ja ruskeakastike', tags: ['nauta', 'suomalainen', 'comfort', 'ruokaisa'] },
            { name: 'Kinkkukiusaus ja suolakurkku', tags: ['sika', 'laatikko', 'suomalainen', 'uuni', 'comfort'] },
            { name: 'Broileri-riisivuoka ja curry', tags: ['kana', 'riisi', 'suomalainen', 'uuni', 'comfort'] },
            { name: 'Hernekeitto ja mustikkapiirakka', tags: ['kasvis', 'keitto', 'suomalainen', 'comfort'] },
            { name: 'Paistettu muikku ja munavoita', tags: ['kala', 'paistettu', 'suomalainen'] },
            { name: 'Lihamakaronilaatikko ja salaatti', tags: ['nauta', 'pasta', 'laatikko', 'suomalainen', 'uuni', 'comfort', 'ruokaisa'] },
            { name: 'Porkkanasosekeitto ja juustosämpylä', tags: ['kasvis', 'keitto', 'suomalainen', 'kevyt'] },
            { name: 'Kalapuikot ja perunamuusi', tags: ['kala', 'paistettu', 'suomalainen', 'comfort'] },
            { name: 'Lasagne ja vihersalaatti', tags: ['nauta', 'pasta', 'italialainen', 'uuni', 'ruokaisa', 'comfort'] },
            { name: 'Kaalikääryleet ja puolukat', tags: ['sika', 'suomalainen', 'comfort'] },
            { name: 'Pyttipannu ja punajuurta', tags: ['sika', 'nauta', 'paistettu', 'suomalainen', 'comfort', 'ruokaisa'] }
        ]
    },
    {
        id: 'varicko',
        name: 'Varicko',
        address: 'Vaasantie 11, 60100 Seinäjoki',
        lat: 62.7965,
        lng: 22.8298,
        phone: '+358 44 244 8775',
        website: 'https://varicko.fi',
        hours: 'ma-pe 10:30-14:00',
        price: '13.50 €',
        priceNum: 13.50,
        cuisineTags: ['suomalainen', 'skandinaavinen'],
        description: 'Rytmikorjaamon ravintola - monipuolinen lounasravintola',
        menuPool: [
            { name: 'Kana-pestopasta ja parmesaani', tags: ['kana', 'pasta', 'italialainen', 'comfort'] },
            { name: 'Kalakeitto ja tillivoileipä', tags: ['kala', 'keitto', 'suomalainen', 'comfort'] },
            { name: 'Härkä-stroganoff ja riisi', tags: ['nauta', 'riisi', 'suomalainen', 'ruokaisa', 'comfort'] },
            { name: 'Kasviscurry ja naan', tags: ['kasvis', 'vegaani', 'curry', 'intialainen', 'mausteinen'] },
            { name: 'BBQ-kanakoipia ja ranskalaiset', tags: ['kana', 'amerikkalainen', 'bbq', 'paistettu', 'ruokaisa'] },
            { name: 'Savuporopasta ja kerma', tags: ['nauta', 'pasta', 'suomalainen', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Tomaatti-mozzarellasalaatti ja leipä', tags: ['kasvis', 'salaatti', 'italialainen', 'kevyt', 'terveellinen'] },
            { name: 'Possun fileemedaljongit ja sienicastike', tags: ['sika', 'skandinaavinen', 'ruokaisa'] },
            { name: 'Thai-kanaa ja nuudelit', tags: ['kana', 'nuudeli', 'aasialainen', 'mausteinen'] },
            { name: 'Uuniperuna ja chili-lihakastike', tags: ['nauta', 'uuni', 'suomalainen', 'mausteinen', 'comfort'] },
            { name: 'Lohi-perunasose ja tilli', tags: ['kala', 'suomalainen', 'skandinaavinen'] },
            { name: 'Feta-pinaattipasta ja auringonkukansiemenet', tags: ['kasvis', 'pasta', 'italialainen', 'terveellinen'] },
            { name: 'Tandoori-kanaa ja raita', tags: ['kana', 'intialainen', 'mausteinen', 'uuni'] },
            { name: 'Texmex-salaatti ja nacholastut', tags: ['nauta', 'salaatti', 'meksikolainen', 'mausteinen'] },
            { name: 'Kasvis-quiche ja yrttisalaatti', tags: ['kasvis', 'uuni', 'kevyt'] }
        ]
    },
    {
        id: 'hanna_ja_kerttu',
        name: 'Hanna ja Kerttu',
        address: 'Kalevankatu 11-13, 60100 Seinäjoki',
        lat: 62.7895,
        lng: 22.8412,
        phone: '+358 20 728 8701',
        website: 'https://ojalanpakari.fi/hanna-ja-kerttu',
        hours: 'ma-pe 10:00-15:00',
        price: '9.00 €',
        priceNum: 9.00,
        cuisineTags: ['suomalainen'],
        description: 'Kahvila-konditoria, edullinen kevyt lounas',
        menuPool: [
            { name: 'Päivän keitto ja sämpylä', tags: ['kasvis', 'keitto', 'suomalainen', 'kevyt'] },
            { name: 'Täytetty croissant (kinkku-juusto)', tags: ['sika', 'kevyt', 'suomalainen'] },
            { name: 'Salaattilautanen ja leipä', tags: ['kasvis', 'salaatti', 'kevyt', 'terveellinen'] },
            { name: 'Piiras ja salaatti', tags: ['kasvis', 'uuni', 'suomalainen', 'kevyt'] },
            { name: 'Lohikeitto ja leipä', tags: ['kala', 'keitto', 'suomalainen', 'comfort'] },
            { name: 'Kanasalaatti ja vinaigrette', tags: ['kana', 'salaatti', 'kevyt', 'terveellinen'] },
            { name: 'Täytetty patonki (kasvis)', tags: ['kasvis', 'kevyt', 'terveellinen'] },
            { name: 'Tomaattikeitto ja juustosämpylä', tags: ['kasvis', 'keitto', 'suomalainen', 'kevyt'] },
            { name: 'Kinkkupiiras ja salaatti', tags: ['sika', 'uuni', 'suomalainen', 'kevyt'] },
            { name: 'Wrap (kana-caesar)', tags: ['kana', 'wrap', 'kevyt'] },
            { name: 'Focaccia ja hummus', tags: ['kasvis', 'vegaani', 'kevyt', 'italialainen'] },
            { name: 'Savulohileipä ja tuorejuusto', tags: ['kala', 'kevyt'] }
        ]
    }
];

// Viikon päivät
const DAYS = ['maanantai', 'tiistai', 'keskiviikko', 'torstai', 'perjantai'];
const DAYS_SHORT = ['ma', 'ti', 'ke', 'to', 'pe'];
