/**
 * Security scan findings – generated by OWASP Top 10:2025 static analysis
 * Scan date: 2026-04-16
 * Scope: All Site_Tour sibling applications
 */
const FINDINGS = [
  {
    "app": "scripts",
    "file": "deploy.mjs",
    "line": 25,
    "owasp": "A04",
    "owaspName": "Cryptographic Failures",
    "severity": "Critical",
    "title": "Hardcoded encryption password in source code",
    "description": "The deployment script contains a hardcoded password 'ZiiliToimistojenKierros2026!' used for AES-256-GCM encryption of sub-applications. Anyone with repository access can decrypt all protected content. The password should be stored in an environment variable or a secrets manager, never committed to version control."
  },
  {
    "app": "scripts",
    "file": "deploy.mjs",
    "line": 27,
    "owasp": "A02",
    "owaspName": "Security Misconfiguration",
    "severity": "Medium",
    "title": "Hardcoded absolute filesystem path",
    "description": "OUTPUT_DIR is hardcoded to a user-specific path '/Users/tapio.pitkaranta/Documents/GitHub/public-demos/Site_tour'. This exposes internal directory structure and username. Use environment variables or relative paths."
  },
  {
    "app": "scripts",
    "file": "deploy.mjs",
    "line": 187,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "document.write() used for decrypted content rendering",
    "description": "The generated password page uses document.write() to render decrypted HTML content. If the encrypted content is ever tampered with or a decryption oracle is found, this could execute arbitrary scripts. Consider using a sandboxed iframe or DOM parsing instead."
  },
  {
    "app": "scripts",
    "file": "deploy.mjs",
    "line": 82,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Low",
    "title": "CSS/JS inline injection during build",
    "description": "The inlineAssets function reads local CSS and JS files and injects them directly into HTML via string concatenation. If any of those files were tampered with (supply chain attack), the content would be included without validation."
  },
  {
    "app": "Helsinki_food",
    "file": "index.html",
    "line": 7,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Leaflet CSS loaded from CDN without Subresource Integrity",
    "description": "Leaflet CSS is loaded from unpkg.com without an integrity attribute. A CDN compromise could inject malicious styles or CSS-based attacks. Add integrity='sha256-...' and crossorigin='anonymous' attributes."
  },
  {
    "app": "Helsinki_food",
    "file": "index.html",
    "line": 8,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Leaflet JS loaded from CDN without Subresource Integrity",
    "description": "Leaflet JavaScript library is loaded from unpkg.com without SRI hash verification. A compromised CDN could serve malicious JavaScript that has full access to the page context. Add integrity and crossorigin attributes."
  },
  {
    "app": "Helsinki_food",
    "file": "app.js",
    "line": 213,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML with template literals for restaurant data",
    "description": "Restaurant card rendering uses innerHTML with template literal interpolation of data from restaurants.js/menus.js. Although data is currently static, if the data source changes (e.g., scraped from web), unsanitized fields like restaurant names or menu items could inject HTML/JavaScript."
  },
  {
    "app": "Helsinki_food",
    "file": "app.js",
    "line": 426,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML used for menu item rendering",
    "description": "Menu cards are rendered using innerHTML with interpolated data. Menu items scraped from external websites could contain malicious HTML. Use textContent or a sanitization library."
  },
  {
    "app": "Helsinki_food",
    "file": "index.html",
    "line": 1,
    "owasp": "A02",
    "owaspName": "Security Misconfiguration",
    "severity": "Medium",
    "title": "No Content Security Policy header or meta tag",
    "description": "The application does not define a Content Security Policy. This allows inline scripts, eval, and loading resources from any origin. Add a CSP meta tag or HTTP header to restrict resource loading."
  },
  {
    "app": "Helsinki_food",
    "file": "scraper/scrape.js",
    "line": 82,
    "owasp": "A06",
    "owaspName": "Insecure Design",
    "severity": "Medium",
    "title": "User-Agent spoofing in web scraper",
    "description": "The scraper spoofs its User-Agent to impersonate a real browser (Mozilla/5.0 Macintosh). This violates ethical scraping practices and may violate terms of service of scraped websites. Use an honest User-Agent identifying the scraper."
  },
  {
    "app": "Helsinki_food",
    "file": "scraper/scrape.js",
    "line": 154,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "JSON.parse on untrusted HTML-extracted data",
    "description": "JSON data is extracted from scraped HTML using regex and passed to JSON.parse(). Maliciously crafted JSON in the HTML source could cause unexpected behavior. Wrap in try-catch and validate the parsed structure."
  },
  {
    "app": "Helsinki_food",
    "file": "scraper/scrape.js",
    "line": 79,
    "owasp": "A10",
    "owaspName": "Mishandling of Exceptional Conditions",
    "severity": "Low",
    "title": "Generic catch blocks with minimal error handling",
    "description": "Several try-catch blocks silently swallow errors or only log generic messages. Failed scrape attempts should be properly logged with context for debugging and monitoring."
  },
  {
    "app": "Joensuu_asiakas_projektireferenssit",
    "file": "data.js",
    "line": 54,
    "owasp": "A01",
    "owaspName": "Broken Access Control",
    "severity": "High",
    "title": "Sensitive business data exposed in client-side JavaScript",
    "description": "The data.js file contains real business-sensitive information including contract values (~5 M EUR, ~2.8 M EUR, 6.8 M EUR), customer names, project references, and consultant names with skills. This data is fully accessible to anyone viewing the page source. Sensitive business data should be served from an authenticated backend API."
  },
  {
    "app": "Joensuu_asiakas_projektireferenssit",
    "file": "app.js",
    "line": 167,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Inline onclick handlers with string interpolation",
    "description": "onclick handlers use template literal interpolation like onclick=\"showRefDetail('${ref.id}')\". If ref.id contains single quotes or special characters, it could break out of the string context and execute arbitrary JavaScript. Use addEventListener instead of inline handlers."
  },
  {
    "app": "Joensuu_asiakas_projektireferenssit",
    "file": "app.js",
    "line": 81,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Extensive innerHTML usage with data interpolation",
    "description": "Over 20 instances of innerHTML assignment with template literal data interpolation. Data from data.js is rendered without sanitization. If data ever comes from an external source, this creates XSS vectors."
  },
  {
    "app": "Joensuu_asiakas_projektireferenssit",
    "file": "index.html",
    "line": 1,
    "owasp": "A02",
    "owaspName": "Security Misconfiguration",
    "severity": "Medium",
    "title": "No Content Security Policy defined",
    "description": "The application does not set a Content Security Policy via meta tag or HTTP header. Inline scripts and eval are unrestricted, increasing XSS attack surface."
  },
  {
    "app": "Joensuu_asiakasreferenssit",
    "file": "app.js",
    "line": 555,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for customer reference rendering",
    "description": "Multiple innerHTML assignments (11 instances) with data interpolation for rendering customer references, tech details, and charts. Potential XSS if data source changes from static to dynamic."
  },
  {
    "app": "Joensuu_biljardipöytä",
    "file": "app.js",
    "line": 844,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "High",
    "title": "User chat input rendered via innerHTML without sanitization",
    "description": "The Slack-like chat feature renders user messages using innerHTML with only newline-to-br replacement: msg.text.replace(/\\n/g, '<br>'). The sendUserMessage() function at line 972 takes user input from a text field and adds it directly to the message array. A user could type <script> or <img onerror=...> tags that would execute when rendered."
  },
  {
    "app": "Joensuu_biljardipöytä",
    "file": "app.js",
    "line": 433,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Player data interpolated into innerHTML with template literals",
    "description": "Player names, nicknames, and emojis from the PLAYERS array are interpolated directly into innerHTML via template literals (25 total innerHTML uses). If player data is ever user-editable, this creates XSS vectors."
  },
  {
    "app": "Joensuu_biljardipöytä",
    "file": "index.html",
    "line": 1,
    "owasp": "A02",
    "owaspName": "Security Misconfiguration",
    "severity": "Medium",
    "title": "No Content Security Policy defined",
    "description": "The 1525-line single-page application with massive inline CSS and JavaScript has no CSP. The large inline script surface area makes CSP particularly important."
  },
  {
    "app": "Joensuu_myynnistä_projektiin",
    "file": "index.html",
    "line": 1249,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML used for content rendering",
    "description": "Multiple innerHTML assignments including rendering of content from data objects. Detail views inject data.content[lang] directly into the DOM without sanitization."
  },
  {
    "app": "Joensuu_neukkarit",
    "file": "app.js",
    "line": 1,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for meeting room management rendering",
    "description": "12 instances of innerHTML usage for rendering meeting room data, booking information, and UI components. Data interpolation via template literals."
  },
  {
    "app": "Joensuu_neukkarit",
    "file": "index.html",
    "line": 1243,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "Low",
    "title": "GoatCounter analytics loaded without SRI",
    "description": "GoatCounter analytics script loaded from gc.zgo.at without integrity verification. While GoatCounter is a lightweight tracker, CDN compromise could inject malicious analytics code."
  },
  {
    "app": "Joensuu_site_tapahtumat",
    "file": "index.html",
    "line": 293,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Chart.js loaded from CDN without Subresource Integrity",
    "description": "Chart.js library loaded from cdn.jsdelivr.net without integrity hash. A CDN compromise would allow arbitrary JavaScript execution in the application context."
  },
  {
    "app": "Joensuu_site_tapahtumat",
    "file": "app.js",
    "line": 1,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for event data rendering",
    "description": "19 instances of innerHTML with template literal interpolation for rendering event information, calendar views, and analytics."
  },
  {
    "app": "Joensuu_toimiston_laskut",
    "file": "app.js",
    "line": 562,
    "owasp": "A04",
    "owaspName": "Cryptographic Failures",
    "severity": "Medium",
    "title": "Sensitive invoice statuses stored in localStorage without encryption",
    "description": "Invoice status data including business IDs (Y-tunnus) is stored in localStorage as plain JSON. localStorage is accessible to any JavaScript running on the same origin, including XSS payloads. Sensitive data should be encrypted before storage or handled server-side."
  },
  {
    "app": "Joensuu_toimiston_laskut",
    "file": "app.js",
    "line": 644,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for invoice data rendering",
    "description": "11 instances of innerHTML with template literal interpolation for rendering invoices, supplier details, and financial data. Invoice data containing special characters could be used for XSS."
  },
  {
    "app": "Joensuu_toimiston_laskut",
    "file": "app.js",
    "line": 1,
    "owasp": "A01",
    "owaspName": "Broken Access Control",
    "severity": "Medium",
    "title": "Financial invoice data embedded in client-side code",
    "description": "The application generates and displays invoice data with company business IDs (Y-tunnus), invoice amounts, and supplier details. While simulated, the structure and patterns reveal business process details that should be server-side."
  },
  {
    "app": "Kuopio_haastattelija",
    "file": "app.js",
    "line": 1,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Extensive innerHTML usage (44 instances)",
    "description": "The interview tool application has 44 instances of innerHTML usage for rendering interview questions, candidate data, and results. This is the highest innerHTML density of any scanned application."
  },
  {
    "app": "Kuopio_lounas",
    "file": "index.html",
    "line": 7,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Leaflet CSS loaded from CDN without SRI",
    "description": "Leaflet CSS loaded from unpkg.com without integrity verification. Same vulnerability pattern as Helsinki_food."
  },
  {
    "app": "Kuopio_lounas",
    "file": "index.html",
    "line": 8,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Leaflet JS loaded from CDN without SRI",
    "description": "Leaflet JavaScript loaded from unpkg.com without integrity hash. Compromised CDN could inject arbitrary code."
  },
  {
    "app": "Kuopio_lounas",
    "file": "app.js",
    "line": 1,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for lunch restaurant data rendering",
    "description": "7 instances of innerHTML usage for rendering restaurant cards and menu data, mirroring the Helsinki_food pattern."
  },
  {
    "app": "Kuopio_pienkehittäjä",
    "file": "app.js",
    "line": 1733,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "document.write() used for print preview rendering",
    "description": "The application uses window.document.write() to render print preview content. This is a legacy DOM manipulation method that bypasses CSP and could execute injected scripts."
  },
  {
    "app": "Kuopio_pienkehittäjä",
    "file": "app.js",
    "line": 1,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for code review rendering (19 instances)",
    "description": "19 instances of innerHTML for rendering code snippets, review comments, and development task details. Code content rendered via innerHTML could contain executable HTML."
  },
  {
    "app": "Kuopio_testausagentit",
    "file": "index.html",
    "line": 7,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Chart.js loaded from CDN without SRI",
    "description": "Chart.js v4.4.4 loaded from cdn.jsdelivr.net without integrity attribute. No verification of script authenticity."
  },
  {
    "app": "Kuopio_testausagentit",
    "file": "index.html",
    "line": 1,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage in testing agent dashboard (19 instances in inline script)",
    "description": "19 instances of innerHTML in the inline script for rendering test results, agent statuses, and analytics data."
  },
  {
    "app": "Oulu_kulttuuripaakaupunki",
    "file": "index.html",
    "line": 355,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Leaflet JS loaded from CDN without SRI",
    "description": "Leaflet library loaded from unpkg.com without integrity hash verification."
  },
  {
    "app": "Oulu_kulttuuripaakaupunki",
    "file": "index.html",
    "line": 356,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Chart.js loaded from CDN without SRI",
    "description": "Chart.js loaded from cdn.jsdelivr.net without version pinning or integrity verification. The URL 'https://cdn.jsdelivr.net/npm/chart.js' resolves to latest version, which could change without notice."
  },
  {
    "app": "Oulu_kulttuuripaakaupunki",
    "file": "index.html",
    "line": 906,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "document.write() used for event detail window",
    "description": "A new browser window is opened and populated using win.document.write(html) with event data interpolated into the HTML string. Event data sourced from external APIs could contain malicious content."
  },
  {
    "app": "Oulu_kulttuuripaakaupunki",
    "file": "index.html",
    "line": 1,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for event rendering (13 instances)",
    "description": "13 instances of innerHTML in the inline script for rendering cultural event data, map popups, and calendar views."
  },
  {
    "app": "Oulu_kulttuuripaakaupunki",
    "file": "process_events.py",
    "line": 363,
    "owasp": "A04",
    "owaspName": "Cryptographic Failures",
    "severity": "Low",
    "title": "MD5 hash used for ID generation",
    "description": "hashlib.md5 is used to generate numeric IDs from event IDs. While not used for security purposes (only ID derivation), MD5 is a deprecated hash function. Use hashlib.sha256 for consistency with security best practices."
  },
  {
    "app": "Seinajoki_ruokabotti",
    "file": "index.html",
    "line": 15,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Leaflet CSS loaded from CDN without SRI",
    "description": "Leaflet CSS loaded from unpkg.com without integrity attribute."
  },
  {
    "app": "Seinajoki_ruokabotti",
    "file": "index.html",
    "line": 16,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Leaflet JS loaded from CDN without SRI",
    "description": "Leaflet JavaScript loaded from unpkg.com without integrity hash."
  },
  {
    "app": "Seinajoki_ruokabotti",
    "file": "index.html",
    "line": 17,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Chart.js loaded from CDN without SRI",
    "description": "Chart.js loaded from cdn.jsdelivr.net without integrity verification."
  },
  {
    "app": "Seinajoki_ruokabotti",
    "file": "app.js",
    "line": 1,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for food bot rendering (23 instances)",
    "description": "23 instances of innerHTML for rendering restaurant data, chat messages, and map popups."
  },
  {
    "app": "Seinajoki_tuntikirjanpito",
    "file": "app.js",
    "line": 22,
    "owasp": "A04",
    "owaspName": "Cryptographic Failures",
    "severity": "Medium",
    "title": "Work hour data stored in localStorage without encryption",
    "description": "Employee work hour entries, project names, and weekly summaries are stored in localStorage as plain JSON (keys: tk2_h, tk2_wp, tk2_saved). This data is accessible to any script on the same origin."
  },
  {
    "app": "Seinajoki_tuntikirjanpito",
    "file": "app.js",
    "line": 182,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for timesheet rendering (24 instances)",
    "description": "24 instances of innerHTML including complex grid rendering with string concatenation (+=). Project names and hour entries are interpolated without sanitization."
  },
  {
    "app": "Seinajoki_tuntikirjanpito",
    "file": "index.html",
    "line": 374,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "Low",
    "title": "GoatCounter analytics loaded without SRI",
    "description": "GoatCounter tracking script loaded from gc.zgo.at without integrity verification."
  },
  {
    "app": "Tampere_golfapuri",
    "file": "index.html",
    "line": 7,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Leaflet CSS loaded from CDN without SRI",
    "description": "Leaflet CSS loaded from unpkg.com without integrity attribute."
  },
  {
    "app": "Tampere_golfapuri",
    "file": "index.html",
    "line": 201,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Leaflet JS loaded from CDN without SRI",
    "description": "Leaflet JavaScript loaded from unpkg.com without integrity hash."
  },
  {
    "app": "Tampere_golfapuri",
    "file": "app.js",
    "line": 1,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for golf app rendering (24 instances)",
    "description": "24 instances of innerHTML for rendering golf course data, scorecards, map popups, and weather information."
  },
  {
    "app": "Tampere_muistuttaja",
    "file": "index.html",
    "line": 140,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Chart.js loaded from CDN without SRI",
    "description": "Chart.js v4.4.1 loaded from cdn.jsdelivr.net without integrity hash verification."
  },
  {
    "app": "Tampere_muistuttaja",
    "file": "app.js",
    "line": 97,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for meeting reminder rendering (17 instances)",
    "description": "17 instances of innerHTML for rendering meeting reminders, notification content, and analytics charts."
  },
  {
    "app": "Tampere_muistuttaja",
    "file": "data.js",
    "line": 1059,
    "owasp": "A04",
    "owaspName": "Cryptographic Failures",
    "severity": "Medium",
    "title": "Meeting data persisted in localStorage without encryption",
    "description": "The localStorage persistence layer stores meeting schedules, participant names, and reminder settings as unencrypted JSON. Any XSS vulnerability could exfiltrate this data."
  },
  {
    "app": "Tampere_myyntitavoittet",
    "file": "index.html",
    "line": 7,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Chart.js loaded from CDN without SRI or version pinning",
    "description": "Chart.js loaded from cdn.jsdelivr.net/npm/chart.js@4.4.1 without integrity hash."
  },
  {
    "app": "Tampere_myyntitavoittet",
    "file": "index.html",
    "line": 8,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Font Awesome loaded from CDN without SRI",
    "description": "Font Awesome v6.5.1 CSS loaded from cdnjs.cloudflare.com without integrity verification. CDN compromise could inject malicious CSS."
  },
  {
    "app": "Tampere_myyntitavoittet",
    "file": "index.html",
    "line": 1581,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for sales target rendering (11 instances)",
    "description": "11 instances of innerHTML for rendering sales targets, pipeline data, and business metrics. Template literals interpolate sales data without sanitization."
  },
  {
    "app": "Tampere_myyntitavoittet",
    "file": "index.html",
    "line": 1511,
    "owasp": "A04",
    "owaspName": "Cryptographic Failures",
    "severity": "Low",
    "title": "Language preference stored in localStorage",
    "description": "User language preference stored in localStorage. While not sensitive, it contributes to the pattern of unencrypted client-side storage across the application suite."
  },
  {
    "app": "Tampere_serttiapuri",
    "file": "index.html",
    "line": 869,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "innerHTML usage for certification management rendering (14 instances)",
    "description": "14 instances of innerHTML for rendering certification catalogs, learning paths, people profiles, and analytics dashboards."
  },
  {
    "app": "Tampere_serttiapuri",
    "file": "index.html",
    "line": 1,
    "owasp": "A02",
    "owaspName": "Security Misconfiguration",
    "severity": "Medium",
    "title": "No Content Security Policy defined",
    "description": "Single-page application with large inline script blocks has no CSP. All inline scripts execute without restriction."
  },
  {
    "app": "Helsinki_food",
    "file": "app.js",
    "line": 193,
    "owasp": "A09",
    "owaspName": "Security Logging and Alerting Failures",
    "severity": "Low",
    "title": "No error logging for failed data operations",
    "description": "The application silently fails when restaurant data loading or rendering encounters issues. No logging mechanism exists to track rendering errors or data integrity issues."
  },
  {
    "app": "Joensuu_biljardipöytä",
    "file": "app.js",
    "line": 1,
    "owasp": "A09",
    "owaspName": "Security Logging and Alerting Failures",
    "severity": "Low",
    "title": "No audit logging for game data modifications",
    "description": "Pool table bookings, game results, and chat messages have no audit trail. Any data manipulation goes undetected."
  },
  {
    "app": "Joensuu_toimiston_laskut",
    "file": "app.js",
    "line": 1,
    "owasp": "A09",
    "owaspName": "Security Logging and Alerting Failures",
    "severity": "Low",
    "title": "No audit logging for invoice status changes",
    "description": "Invoice status modifications are persisted to localStorage without any audit trail or change history. In a real invoice system, this would be a compliance issue."
  },
  {
    "app": "Seinajoki_tuntikirjanpito",
    "file": "app.js",
    "line": 900,
    "owasp": "A08",
    "owaspName": "Software or Data Integrity Failures",
    "severity": "Low",
    "title": "Data version migration without integrity verification",
    "description": "The data version check (tk2_ver) migrates localStorage data based on a simple integer comparison without verifying data integrity. Corrupted or tampered localStorage data would be accepted."
  },
  {
    "app": "Oulu_kulttuuripaakaupunki",
    "file": "index.html",
    "line": 7,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Leaflet CSS loaded from CDN without SRI",
    "description": "Leaflet CSS loaded from unpkg.com without integrity attribute."
  },
  {
    "app": "Oulu_kulttuuripaakaupunki",
    "file": "index.html",
    "line": 356,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "Medium",
    "title": "Chart.js loaded without version pinning",
    "description": "Chart.js is loaded from 'https://cdn.jsdelivr.net/npm/chart.js' without a specific version. The CDN will serve the latest version, which could introduce breaking changes or vulnerabilities without notice. Pin to a specific version."
  },
  {
    "app": "Kuopio_testausagentit",
    "file": "index.html",
    "line": 1184,
    "owasp": "A04",
    "owaspName": "Cryptographic Failures",
    "severity": "Low",
    "title": "Language preference in localStorage",
    "description": "User language setting stored unencrypted in localStorage. Low risk but part of the systemic pattern of using localStorage without considering data classification."
  },
  {
    "app": "Joensuu_asiakas_projektireferenssit",
    "file": "app.js",
    "line": 278,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Customer name interpolated into onclick handler",
    "description": "onclick=\"showCustomerDetail('${c.name}')\" interpolates customer names directly into JavaScript event handlers. Customer names with apostrophes or HTML special characters could cause injection."
  },
  {
    "app": "Joensuu_asiakas_projektireferenssit",
    "file": "app.js",
    "line": 320,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Technology name interpolated into onclick handler",
    "description": "onclick=\"showTechDetail('${item.name}')\" interpolates technology names into inline handlers. Names containing quotes or angle brackets could break the handler context."
  },
  {
    "app": "Kuopio_haastattelija",
    "file": "feedback-data.js",
    "line": 8,
    "owasp": "A01",
    "owaspName": "Broken Access Control",
    "severity": "High",
    "title": "PII exposed in client-side JavaScript: names and email addresses",
    "description": "feedback-data.js contains records with full names (e.g. Matti Virtanen, Liisa Korhonen) and personal email addresses (matti.virtanen@email.fi, jukka.makinen@gmail.com) hardcoded in client-side code. This data is downloaded to every visitor's browser and visible in source. Sensitive personal data should be served from an authenticated backend API, not embedded in client-side code."
  },
  {
    "app": "Kuopio_haastattelija",
    "file": "app.js",
    "line": 559,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "XSS via innerHTML with feedback text and user names",
    "description": "User-submitted feedback text (p.palaute) and user name (p.nimi) are interpolated directly into innerHTML at lines 559-570 without sanitization. If feedback data contains HTML/script payloads, they will execute in the browser. Use textContent for user-supplied strings or sanitize with DOMPurify."
  },
  {
    "app": "Kuopio_haastattelija",
    "file": "app.js",
    "line": 911,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Chat messages rendered via innerHTML without sanitization",
    "description": "Chat messages at lines 911-918 are rendered using innerHTML with m.text interpolated directly. If chat input is not sanitized before storage, this creates a stored XSS vector. Use textContent or sanitize with DOMPurify."
  },
  {
    "app": "Kuopio_pienkehittäjä",
    "file": "app.js",
    "line": 1733,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "document.write() used for PDF export with unsanitized data",
    "description": "document.write() generates a print/PDF window with audit report data including r.title, r.auditor, r.date, r.standard, and r.scope interpolated into the HTML string without sanitization. document.write() is inherently dangerous and bypasses CSP. Use DOM APIs to construct the print document."
  },
  {
    "app": "Kuopio_lounas",
    "file": "app.js",
    "line": 213,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "XSS via innerHTML with scraped restaurant menu content",
    "description": "Restaurant cards render r.name, r.address, r.website, r.description, and scraped menu items via innerHTML without sanitization. Menu data is auto-generated by scraping external restaurant websites, meaning attacker-controlled content from third-party sites flows directly into the DOM."
  },
  {
    "app": "Kuopio_lounas",
    "file": "scraper/scrape.js",
    "line": 61,
    "owasp": "A06",
    "owaspName": "Insecure Design",
    "severity": "Low",
    "title": "User-Agent spoofing in web scraper",
    "description": "The scraper sends a fake User-Agent header impersonating a real browser. This violates ethical scraping practices and may violate terms of service. Use a descriptive User-Agent identifying the scraper and its purpose."
  },
  {
    "app": "Oulu_kulttuuripaakaupunki",
    "file": "process_events.py",
    "line": 312,
    "owasp": "A02",
    "owaspName": "Security Misconfiguration",
    "severity": "Low",
    "title": "Hardcoded /tmp path for input data allows local file manipulation",
    "description": "The script reads from hardcoded path /tmp/oulu2026_all_events_complete.json. The /tmp directory is world-readable/writable, allowing other local users to replace the file with malicious content that flows into events_data.js. Use a configurable path and validate input data."
  },
  {
    "app": "Tampere_muistuttaja",
    "file": "data.js",
    "line": 1191,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "High",
    "title": "User-provided transcript text parsed and rendered without sanitization",
    "description": "simpleParseTranscript() parses user-pasted meeting transcript text into structured data (participant names, task descriptions). This parsed output is later rendered via innerHTML in app.js without HTML encoding. An attacker who crafts a transcript with embedded HTML/JavaScript tags can achieve stored XSS since the parsed data is persisted to localStorage."
  },
  {
    "app": "Tampere_muistuttaja",
    "file": "app.js",
    "line": 327,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Task cards use innerHTML with string-interpolated onclick handlers",
    "description": "Task cards (lines 327-383) are rendered via innerHTML with onclick handlers like onclick=\"updateTaskStatus('${task.id}', 'in_progress')\". Task IDs originate from transcript parsing. If a task ID contains single quotes, it can break out of the onclick string and inject JavaScript."
  },
  {
    "app": "Tampere_serttiapuri",
    "file": "index.html",
    "line": 1196,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Certificate detail modal renders tip text and external URLs via innerHTML",
    "description": "showCertDetail() renders certification tips including tip.text directly in innerHTML. The function also renders external URLs from cert data using href=\"${c.url}\" which could be exploited for javascript: URL injection if data were compromised."
  },
  {
    "app": "Tampere_serttiapuri",
    "file": "index.html",
    "line": 847,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Low",
    "title": "AI chat bot renders response HTML and user input via innerHTML",
    "description": "The chat bot system stores messages with HTML markup in the text field. User chat input is processed through getBotResponse() and the user's message text is also rendered via innerHTML in the chat display, creating a self-XSS vector."
  },
  {
    "app": "Seinajoki_tuntikirjanpito",
    "file": "app.js",
    "line": 892,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "HTML escaping function exists but is applied inconsistently",
    "description": "An esc() function is defined at line 892 that escapes &, <, and \". However, it is only used in a few places while the vast majority of innerHTML assignments do not use it. Inconsistent output encoding means most dynamic content is still vulnerable to XSS if data is tainted."
  },
  {
    "app": "Seinajoki_tuntikirjanpito",
    "file": "app.js",
    "line": 592,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "High",
    "title": "Complex onclick handlers with multi-parameter string interpolation",
    "description": "Lines 592-604 construct complex onclick handler strings like onclick=\"drillTo({type:'project-day',id:'${dr.id}',...})\" within innerHTML assignments. These multi-parameter inline event handlers with string-interpolated values create injection risk. A malicious project ID could break out of the string context and execute arbitrary JavaScript."
  },
  {
    "app": "Tampere_myyntitavoittet",
    "file": "index.html",
    "line": 1946,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Drilldown modal accepts arbitrary HTML content via innerHTML",
    "description": "createDrilldownModal() accepts a title and contentHTML parameter and inserts them directly into innerHTML of a dynamically created modal overlay. The title parameter is placed inside an <h2> tag without encoding. If any title value contains HTML, it will be rendered as markup."
  },
  {
    "app": "Joensuu_biljardipöytä",
    "file": "app.js",
    "line": 999,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "High",
    "title": "Bot response interpolates player nicknames into HTML span elements",
    "description": "Bot responses construct HTML with player nicknames: <span class=\"mention\">@${...nick}</span>. If player data contains HTML metacharacters, this produces unintended markup. Combined with the innerHTML rendering at line 844, this creates a full XSS chain through the Slack chat feature."
  },
  {
    "app": "Joensuu_toimiston_laskut",
    "file": "app.js",
    "line": 1529,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Uploaded file name rendered in innerHTML without escaping",
    "description": "In processUploadedFile(), the uploaded file's name is rendered via innerHTML. A crafted filename containing HTML (e.g. <img src=x onerror=alert(1)>.pdf) would execute as JavaScript. Escape file.name before interpolation."
  },
  {
    "app": "Helsinki_food",
    "file": "scraper/scrape.js",
    "line": 1070,
    "owasp": "A08",
    "owaspName": "Software or Data Integrity Failures",
    "severity": "High",
    "title": "Scraped HTML written directly as JavaScript module without sanitization",
    "description": "The scraper writes restaurant menu data (scraped from external websites) into menus.js using fs.writeFileSync with JSON.stringify. The scraped HTML content is then loaded by the browser app and rendered via innerHTML. If a restaurant website contains malicious HTML/JS, the scraper captures it and the app executes it."
  },
  {
    "app": "Kuopio_haastattelija",
    "file": "app.js",
    "line": 432,
    "owasp": "A02",
    "owaspName": "Security Misconfiguration",
    "severity": "Low",
    "title": "Links with target=\"_blank\" missing rel=\"noopener noreferrer\"",
    "description": "Agency modal link uses target=\"_blank\" without rel=\"noopener noreferrer\". This can allow the opened page to access window.opener and potentially redirect the original page (reverse tabnapping). Add rel=\"noopener noreferrer\" to all target=\"_blank\" links."
  },
  {
    "app": "Kuopio_lounas",
    "file": "app.js",
    "line": 223,
    "owasp": "A02",
    "owaspName": "Security Misconfiguration",
    "severity": "Low",
    "title": "Links with target=\"_blank\" missing rel=\"noopener noreferrer\"",
    "description": "Restaurant links at lines 223 and 431 use target=\"_blank\" without rel=\"noopener noreferrer\", enabling potential reverse tabnapping attacks."
  },
  {
    "app": "Kuopio_pienkehittäjä",
    "file": "app.js",
    "line": 911,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Chat messages rendered via innerHTML without sanitization",
    "description": "Chat messages are rendered using innerHTML with m.text directly interpolated. System, agent, and user messages all flow through the same rendering path. If any message text contains HTML, it will be executed."
  },
  {
    "app": "Kuopio_testausagentit",
    "file": "index.html",
    "line": 1722,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Observation data rendered via innerHTML with onclick interpolation",
    "description": "Recent observations table renders o.id, o.testCase, o.severity, o.status, and o.site via innerHTML template literals. The onclick handler also interpolates o.id into a string. Use DOM APIs or sanitize data before innerHTML assignment."
  },
  {
    "app": "Oulu_kulttuuripaakaupunki",
    "file": "index.html",
    "line": 505,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "Event card data rendered via innerHTML with imported third-party event data",
    "description": "Event cards render ev.name, ev.dates, ev.location, and ev.description via innerHTML. Event data is generated by process_events.py from an external JSON source, meaning data from third parties flows into the DOM unsanitized."
  },
  {
    "app": "Tampere_muistuttaja",
    "file": "i18n.js",
    "line": 312,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Low",
    "title": "Reminder message template uses string replacement with user data",
    "description": "formatReminderMessage() performs .replace('{name}', name).replace('{task}', task) on i18n templates. The resulting string is later used in innerHTML contexts. If name or task contain HTML, the replacement produces injectable content."
  },
  {
    "app": "Tampere_golfapuri",
    "file": "app.js",
    "line": 452,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Medium",
    "title": "onclick handler with string-interpolated parameters in map popup innerHTML",
    "description": "Line 452 constructs onclick=\"addToPollFromPopup('${dateStr}','${timeStr}','${course.id}')\" within innerHTML. If any of these values contain single quotes or HTML entities, the handler string can be broken, potentially leading to JavaScript injection."
  },
  {
    "app": "Tampere_myyntitavoittet",
    "file": "index.html",
    "line": 8,
    "owasp": "A03",
    "owaspName": "Software Supply Chain Failures",
    "severity": "High",
    "title": "Font Awesome loaded from CDN without Subresource Integrity",
    "description": "Font Awesome v6.5.1 CSS loaded from cdnjs.cloudflare.com without integrity or crossorigin attributes. A CDN compromise could inject malicious CSS content. Add SRI attributes."
  },
  {
    "app": "Seinajoki_tuntikirjanpito",
    "file": "app.js",
    "line": 21,
    "owasp": "A04",
    "owaspName": "Cryptographic Failures",
    "severity": "Info",
    "title": "Application state persisted in localStorage without integrity checks",
    "description": "The save() and load() functions persist application state to localStorage as plain JSON. localStorage is accessible to any script running on the same origin. If XSS is achieved, an attacker can read or tamper with all persisted data including work hour records."
  },
  {
    "app": "Joensuu_site_tapahtumat",
    "file": "app.js",
    "line": 755,
    "owasp": "A05",
    "owaspName": "Injection",
    "severity": "Info",
    "title": "Good practice: escapeHtml function implemented and used",
    "description": "This application defines and uses an escapeHtml() function at lines 755-758 to sanitize user input in the Slack chat feature. This is the correct approach and is noted as a positive finding. Other applications in this suite should adopt the same pattern."
  }
];
